### ISSUE TITLE
convert 'make run' to use Perl 6

### ISSUE THREAD

**Issue by coke** [Raku/doc#1057]
Perhaps a Bailador app (instead of a p5 Mojo App)

**Comment by coke** [comment]
Related to #1246

**Comment by coke** [comment]
http://mi.cro.services/

**Comment by coke** [comment]
Also needed to move the 'make assets' step to Perl 6.

**Comment by tbrowder** [comment]
Also need a way to kill the html run process so it can be started again.

**Comment by tison1** [comment]
Cro is reasonable

**Comment by coke** [comment]
I'm not sure why I originally thought this was different than #1246 - Closing this ticket in favor of that.

**Comment by coke** [comment]
With the build/run moved/moving outside of this repo, this ticket is obsolete.

**Comment by Altai-man** [comment]
>With the build/run moved/moving outside of this repo, this ticket is obsolete.

How so? The site became dynamic && implemented in Raku while I was not looking? ~Can I drop efforts to write it then?~

**Comment by JJ** [comment]
No, simply static and it can use any or no webserver, just the files...

**Comment by JJ** [comment]
Actually, come to think of it, I still use make run...

**Comment by Altai-man** [comment]
I mean, how is this ticket obsolete? If there is some other repo where it belongs, it should be transferred.

**Comment by coke** [comment]
My mistake, I was under the impression that the code to build the site had been removed from the repo, and that therefore the 'make run' target was obsolete. Re-opened.

**Comment by JJ** [comment]
It's not totally removed. "make assets", for instance, still works.

**Comment by coke** [comment]
Make run has now been removed from the repo, all logic around building and running the site is now part of doc-website
