### ISSUE TITLE
Extra info in search criteria

### ISSUE THREAD

**Issue by coke** [Raku/doc#1086]
_from README.md_

*  Search terms like `.any`, `any()`, `&any`, `::Any`, etc. can be
    used to disambiguate whether information is sought on a method,
    subroutine, type, etc.

**Comment by coke** [comment]
The items need explanation on how to work.

Guessing that '.' implies method. Maybe :: implies Type, but shouldn't it be (Any) ?

**Comment by JJ** [comment]
The intention of this issue here is to make what the README.md says effectively work? Change that description? Check that it works that way?

**Comment by JJ** [comment]
It's not in the README.md, now... So I guess it really belongs to the wishlist, right?

**Comment by coke** [comment]
This ticket was to get it into our TODO list (the issues) instead of in a user facing doc.

**Comment by JJ** [comment]
So what the OP want is to index a term differently depending on what it is. If it's a method, always index it as .method; if it's a routine, &routine, and so on, right? 
Not sure about that. Searching is smart enough to figure out by having just the letters, but it would need a good amount of work if we are going to do it systematically. And it does not seem to be a problem right now.

**Comment by coke** [comment]
"problem right now" ... it's a wishlist item, so no it's not a problem right now.

"always index as" no. This means if someone enters ".foo" as a search criteria, only return results that match foo that are also categorized as a method.

It doesn't actually need to change what the indexed value is. I expect that will remain unchanged as "foo"

**Comment by coke** [comment]
Followup on linked ticket.

**Comment by Altai-man** [comment]
@coke this was already implemented on my website, so if @finanalyst copied the search_template it means this is already working (or should be so). Can anyone please follow up if it's really so?
