### ISSUE TITLE
Search for operator name with p6doc

### ISSUE THREAD

**Issue by coke** [Raku/doc#1088]
_from README.md_

 *  Searching for an operator name returns the documentation for
    the operator.  (`p6doc '%%'`  returns the documentation for
    `&infix:<%%>`.)

Note - this already works in the web search.

**Comment by JJ** [comment]
Related p6doc problems/wishlist: #2166

**Comment by coke** [comment]
p6doc is no longer a part of this repository; it is now called rakudoc and is part of http://github.com/raku/rakudoc
