### ISSUE TITLE
docs.perl6.org design

### ISSUE THREAD

**Issue by hankache** [Raku/doc#1090]
It would be nice if the docs have the same design as the main perl6.org website. For consistency.

**Comment by gfldex** [comment]
http://examples.perl6.org/ is a related project and may need the same treatment.

**Comment by hankache** [comment]
Indeed an issue has been opened in the examples repo https://github.com/perl6/perl6-examples/issues/46

**Comment by coke** [comment]
Turns out that because of how we build the docs, this isn't a simple cut and paste fix. Working on it now.

**Comment by coke** [comment]
This is kind of blocked by https://github.com/perl6/Pod-To-HTML/issues/23

**Comment by W4anD0eR96** [comment]
@coke 

perl6/Pod-To-HTML#26

**Comment by zoffixznet** [comment]
> perl6/Pod-To-HTML#26
(the module on hack already updated with that PR so the docs build uses it)

**Comment by JJ** [comment]
That issue has been solved, so I guess this is no longer blocked. Are we still interested in this?

**Comment by zoffixznet** [comment]
> Are we still interested in this?

IMO it'd be nice for them to be *themed* the same, but not necessarily to have the exact same design/layout, as they have different purposes and can be best fine-tuned for them. Rust lang does it how I'm picturing it: both [main site](https://www.rust-lang.org/en-US/) and the [The Book](https://doc.rust-lang.org/book/second-edition/) have the same minimalistic theme, but their designs are different, to suit different purposes of the sites.

So if, say, all of our sites would be using BootStrap 4, they could have their own layouts they need, but they could share a single theme file and so any changes to the theme would propagate to main site, docs, and examples site automatically.

---------

That said, I'd say it's a waste of time to try to do that with the current `htmlify.p6`-based site. A dynamic site that has the docs stored in some database is a higher priority and would annul all the efforts spent into design/markup changes to `htmlify.p6`-based site.

----------

> same design as the main perl6.org website

P.S. in 2-3 months, perl6.org will see an update that'll have it upgraded to BootStrap 4 and the design might change slightly too.

**Comment by coke** [comment]
New site layout is available for review at raku/doc-website - please provide any feedback there.
