### ISSUE TITLE
Add new top level search page

### ISSUE THREAD

**Issue by coke** [Raku/doc#1099]
Add a new top level index/search page.

* Display every category/item currently available in the existing search box.
* Categories ordered by either a hardcoded ranking, or alphabetically.
* Within a section, items are ordered alphabetically.
* Provide a search box separate from the existing search, which has the result of hiding the links that do not match.
* Should be able to link to this page and pass in a search string - when loading the page, show the string in the search box and perform the search. (preferably before loading the page).

Once this is in place, we can start making the dropdown search a little smarter and link to this as a fallback when users want to see all possible search results.

We may also want to make it a top level link in the docs menu.

**Comment by JJ** [comment]
Are we still interested in this?

**Comment by coke** [comment]
Yes

**Comment by coke** [comment]
So, this was about 4 years ago, so let me see if I can remember what I was thinking. This was intended as a top level static page - a dynamic search page could probably be done cleaner.

> Display every category/item currently available in the existing search box.

I imagined the categories as headers, with a list of items below. In retrospect, I suspect having all the items visible would just be too cluttered. (but you could have them present if a partial search was present)

> Provide a search box separate from the existing search, which has the result of hiding the links that do not match.

Ah. so if we do show all the links by default, as you start typing, hide those that don't match.

> Should be able to link to this page and pass in a search string - when loading the page, show the string in the search box and perform the search. (preferably before loading the page).

This'd be a little tricky but should be doable with some javascript.

... If you're working on this, please consider these suggestions for the UI, but not gospel.

**Comment by MorayJ** [comment]
I'm not clear if this is intended as a full page search, a headline and first paragraph search or just a headline search that has a first para in the results. Any thoughts?

**Comment by Altai-man** [comment]
I think it describes a separate page (with url say `/search`) with a big nice input where user types queries and gets results based on the index entries we already have.

So it uses the same data the search in the header users, just presents it more clearly and allows goodies like connecting search engines.

Maybe I misunderstood your question, can you please clarify with examples of what you think about?

**Comment by MorayJ** [comment]
That's pretty much what I was querying, I think. The example page has extra text but, from a search point of view, I guess this is cosmetic and gives more information on what you've found. Thanks

**Comment by Altai-man** [comment]
For now let's omit the detailed text in a result item (so, leaving only the headlines).

**Comment by coke** [comment]
This is available as part of raku/doc-website - in the header nav, select "Extended Search".
