### ISSUE TITLE
type images generation should be smarter

### ISSUE THREAD

**Issue by coke** [Raku/doc#1206]
Currently the type graph images are generated or not based on the presence of a single file.

Ideally we should only be generating the files we need (and that includes only a subset of these files if we do a --sparse run)

This is a low priority item.

**Comment by JJ** [comment]
I wonder if this is needed. After all, it's much faster now after the latest changes to htmlify.p6

**Comment by 2colours** [comment]
First, this issue would probably belong to the [doc-website repo](https://github.com/Raku/doc-website) now - and is it even relevant these days?

**Comment by coke** [comment]
Correct, this ticket no longer relevant on this repo.
