### ISSUE TITLE
doc/Type/X/Syntax/Comment/Embedded.pod6 and #`

### ISSUE THREAD

**Issue by coke** [Raku/doc#1385]
Says that it's an error to do

#`

with no bracket, but this appears to be fine.

**Comment by coke** [comment]
Found a roast test that is todo'd, which points to https://rt.perl.org/Ticket/Display.html?id=124679.

The exception does appear in the rakudo source, but isn't current thrown anywhere in roast.

**Comment by JJ** [comment]
Would this be a not-specced? NYI?

**Comment by JJ** [comment]
Still todo: 
https://github.com/perl6/roast/blob/693fff436180a8f2d876f0399a9080f9bbcbd90e/S32-exceptions/misc2.t#L185-L188

**Comment by coke** [comment]
Just tested with Rakudo™ v2022.07 and the expected error is thrown.
