### ISSUE TITLE
Examples compilation should check output

### ISSUE THREAD

**Issue by coke** [Raku/doc#1424]
We have a lot of "OUTPUT: " markers embedded in the example code. It would be great if we could compare the output of the code to verify that the output is what we declared.

**Comment by Altai-man** [comment]
Looked a bit into this issue. It is relatively easy to execute examples and compare output with comment, but a lot(_a lot_) of code compiles fine, but dies on execution. This is a log of first attempt - https://gist.github.com/Altai-man/99ee1610d4a9af1d6631b90c7d1b4321
Missing variable values, undefined classes and the like.

Do we want to complement it with hidden code so those can be executed or skip eventually?

**Comment by coke** [comment]
It's a hard question - with the compile only, we don't have to worry about bad code; if we're running it, there's a a lot of potential bad behavior for those running the tests. I'm not sure there's a good way to do this safely. (But thank you for doing the first pass!)

**Comment by coke** [comment]
rejecting based on @Altai-man 's prototype work.
