### ISSUE TITLE
html build process tries to run bash code on Windows

### ISSUE THREAD

**Issue by lefth** [Raku/doc#1480]
Environment: Windows 10, and the build tools from both Strawberry Perl and MSYS.

Steps: I cloned the p6doc repository to a local directory (the result is the same if I use "zef look p6doc"), entered the directory with the windows command shell, and ran "gmake html". 

Result:
- Lots of output about pods being successfully processed:
"processed ./doc\Type\X\Role\Initialization.pod6"
- several warnings about duplicate index entries were printed
- The following linux shell code and error were printed:
```
ATOMDIR="./highlights/atom-language-perl6";  \
if [ -d "$ATOMDIR" ]; then (cd "$ATOMDIR" && git pull); \
else git clone https://github.com/perl6/atom-language-perl6 "$ATOMDIR"; \
fi; cd highlights; npm install .
'ATOMDIR' is not recognized as an internal or external command,
operable program or batch file.
makefile:11: recipe for target 'init-highlights' failed
gmake: *** [init-highlights] Error 1
```

**Comment by JJ** [comment]
Can someone who uses Windows take care of this? Maybe port to powershell?

**Comment by coke** [comment]
if we move this part of the build into perl6, that will also cover it.

**Comment by JJ** [comment]
@coke Are we going to do that? Is that in another issue?

**Comment by coke** [comment]
No, there is no other issue specifically devoted to my particular suggestion here.

**Comment by JJ** [comment]
Can someone who uses Windows check this out?

**Comment by coke** [comment]
This will be obsolete (or at least a whole different problem on Windows) with the new site; we'll do the build there and get it working on windows if possible.
