### ISSUE TITLE
Linking to pragmas

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#1488]
Some time ago [I attempted](https://github.com/perl6/doc/blob/30f6e1a9673f05eb8367408c64958d8f2831bd39/doc/Language/traps.pod6#L592) to add a link to MONKEY-SEE-NO-EVAL.

It created this link:
https://docs.perl6.org/type/MONKEY-SEE-NO-EVAL (404)

But I needed this:
https://docs.perl6.org/language/pragmas#index-entry-MONKEY-SEE-NO-EVAL-MONKEY-SEE-NO-EVAL

Is there any better way than hardcoding ``language/pragmas#index-entry-MONKEY-SEE-NO-EVAL-MONKEY-SEE-NO-EVAL``?

**Comment by W4anD0eR96** [comment]
It's because our `htmlify.p6` treat `Upper` as `Type` and `lower` as `routine`.

You can modify `htmlify` logic(it's a bit messy though, remind of 'write-only' :-( ) or improve the `#index-entry-MONKEY-SEE-NO-EVAL-MONKEY-SEE-NO-EVAL` part to make hard-code not so ugly.

**Comment by JJ** [comment]
Wow, it's a thousand lines of early Perl6... Maybe use this to refactor the thing?

**Comment by JJ** [comment]
Besides, I think this would call for major refactoring. Would pragmas go to a separate directory? This is related to #802 and others, also. Should we document pragmas in a separate directory?

**Comment by JJ** [comment]
Related: #1823

**Comment by coke** [comment]
htmlify is long gone, but the best way to link to that these days is:

```
L</language/pragmas#MONKEY-SEE-NO-EVAL>
```
