### ISSUE TITLE
How to use WinCompose (unicode_entry)

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#1532]
We should mention https://github.com/Lexikos/AutoHotkey_L/ on https://docs.perl6.org/language/unicode_entry

**Comment by JJ** [comment]
Same as the other one... I can link and put something sensible, but I don't have Windows boxes handy to actually test it.

**Comment by JJ** [comment]
Walk the user through what needs to be done to download the application and define a key to combine other keys and generate symbols such as « or →

**Comment by Xliff** [comment]
Ouch. 

I think this fell off my radar, somehow.

I think AutoHotKey is a bad idea for something like this. A better one would be [WinCompose](https://github.com/samhocevar/wincompose), which has all of the instructions you'd need to get a proper setup working on windows.

**Comment by JJ** [comment]
@Xliff unassignment was automatic, when the repo was moved. I'll add you to the repo, and reassign this issue, if you want.

**Comment by coke** [comment]
WinCompose is already in the docs.
