### ISSUE TITLE
404 links in perl6.html

### ISSUE THREAD

**Issue by JJ** [Raku/doc#1825]
They seem to be of two different types:
- [x] Linking HTML entities:
```
https://docs.perl6.org/(&lt;=)
```

- [x] "spans" linked 
```
https://docs.perl6.org/%3Cspan%20class=%22code%22%3Eunique%3C/span%3E	
```
Related to #561

**Comment by JJ** [comment]
No linking of HTML entities, either. I'm checking for other 404 (there will probably some, re: #561) but if there's nothing outstanding, I'm closing it.

**Comment by JJ** [comment]
Actually, those links are not in the source, but generated for some reason.

**Comment by JJ** [comment]
In fact, those 404 are due to these errors
![screenshot from 2018-04-24 19 15 15](https://user-images.githubusercontent.com/500/39203010-f45d0c36-47f3-11e8-92ff-78c3f12cbf90.png)
It was fixed for first-level headings, but they are still there for other levels...

**Comment by W4anD0eR96** [comment]
@JJ for `<a name="159"></a>` pattern, it is generated by https://github.com/perl6/perl6-pod-to-bigpage/blob/c3410958c5ccc778dd9f62f6af5f62df5092863e/lib/Pod/To/BigPage.pm6#L454-L458

for, emm..., useless X<> tag. Maybe we can just safely remove those logic.

**Comment by coke** [comment]
will track in https://github.com/Raku/doc-website/issues/72 on new site.
