### ISSUE TITLE
Be mindful of external references when breaking links

### ISSUE THREAD

**Issue by zoffixznet** [Raku/doc#1838]
I noticed a [commit](https://github.com/perl6/doc/commit/bc72bc3c5b826b79e830f7f22ed1779734818f73) fixed some links that are 404s and I clearly remembered using those links recently-ish, but I can't remember where exactly. It could've been a blog post, a response on social media, or an email. Regardless of what it was, those links are now broken due to some changes to our site.

We should be more mindful when changing links. If we're to fulfill the [Vision for the site](https://github.com/perl6/doc#vision), we can't continually break 3rd party communications and content (especially tutorials, blogs, videos, and books).

That point should be made in the contributing guide and some common forms of links should probably be tested (e.g. `/type/` and `/routine/` links). For example, https://docs.perl6.org/type/Proc$COLON$COLONAsync used to be a working link and I even remember [adding `.htaccess` rewrite rules](https://github.com/perl6/doc/commit/3feecce1fd1671ab446a0faa6b9dd305ca23ea5b#diff-5537a4ed70cfb8fdbdad0926c6e51757) to keep that form working when we got rid of `$COLON` stuff in URLs. However, it appears [a more recent commit](https://github.com/perl6/doc/commit/a9d617aad30e1699c93862fdc21525ae0643d700) to `.htaccess` broke those rewrites

-----

I ran a small Perl 6 one liner over the content of my 2-year old [blog](https://rakudo.party/) and these links turned up as broken:

- https://docs.perl6.org/language/functions#index-entry-nextsame-nextsame
- https://docs.perl6.org/language/functions#index-entry-nextwith-nextwith
- https://docs.perl6.org/language/regexes#%3C%3C_and_%3E%3E_,_left_and_right_word_boundary
- https://docs.perl6.org/syntax/$
- https://docs.perl6.org/syntax/CONTROL
- https://docs.perl6.org/syntax/LEAVE
- https://docs.perl6.org/type/Proc$COLON$COLONAsync

The pages for https://docs.perl6.org/syntax/CONTROL and https://docs.perl6.org/syntax/LEAVE now require [a space](https://docs.perl6.org/syntax/%20CONTROL) before the keyword so those two along with the `$COLON` stuff looks to me like accidental breakage of external links that should've been caught by something IMO.

**Comment by JJ** [comment]
Hum. That would explain lots of things...

**Comment by JJ** [comment]
Could this be related to #1835 ?

**Comment by JJ** [comment]
This is definitely related to this:
```
https://docs.perl6.org/routine/.$CIRCUMFLEX_ACCENT	
  Line: 158
  Code: 404 Not Found
 To do: The link is broken. Double-check that you have not made any typo,
	or mistake in copy-pasting. If the link points to a resource that
	no longer exists, you may want to remove or fix the link.
```

**Comment by JJ** [comment]
And... It might have caused the Great Broken Link Explosion... #561 
![screenshot from 2018-03-09 20 05 17](https://user-images.githubusercontent.com/500/37224943-491c3780-23d5-11e8-8840-dcdd77611f67.png)
Pretty much matches the dates...

**Comment by JJ** [comment]
Could we maybe add a `xt` test to check for this kind of things?

**Comment by JJ** [comment]
What is your suggestion in this case? Should we revert the change in .htaccess? Should we try and combine the two to see what happens?

**Comment by JJ** [comment]
We should also try and have some test files for this.

**Comment by coke** [comment]
The original breakages are unfortunately long gone at this point.

Going forward, we can do better to not break old links, and the new raku/doc-website will have a link checker available, and hopefully we can also track web server log info and track 404s so we can fix breakages sooner.
