### ISSUE TITLE
Add Code of Conduct, issue and PR templates.

### ISSUE THREAD

**Issue by JJ** [Raku/doc#1847]
As recommended by the [Community profile](https://github.com/perl6/doc/community)

**Comment by AlexDaniel** [comment]
Heh. I hope we won't have a war over this. It seems like the idea of having a Code of Conduct is rather controversial, and I'm also sitting on the fence.

**Comment by JJ** [comment]
The first article in the Code of Conduct is not to go to war over Codes of
Conduct.

I'm happy one way or the other. Slightly tipped towards having one, since
GitHub advises us to do so.

**Comment by AlexDaniel** [comment]
Well, here's a TODO list they give:

- [ ]  Research different codes of conduct designed for open source projects. Choose one that reflects your community's standards.
- [ ]  Consider carefully whether you are willing and able to enforce it.

And they propose these:
* https://contributor-covenant.org/
* https://www.djangoproject.com/conduct/
* http://citizencodeofconduct.org/

**IF** we were to add a code of conduct, which one would it be?

**Comment by JJ** [comment]
The second issue is way more important than the first. I don't know how we
would do that.
Besides, there's the issue of having a code just for this site, which is
osmotically related to the rest of the Perl6 repos. It's the whole
community that should take that decision, not us in this corner of the
Perl6 universe.
I think we should better leave that aside for the time being.

**Comment by AlexDaniel** [comment]
IMO that particular template is completely useless, but realistically I hate all issue templates…

> I'm reporting … … …

Well, that's why there are labels, but people can't add these themselves. So if in the end someone will have to look at the issue and add appropriate labels anyway, so why should we make it harder for bug reporters?

>  `+<!-- describe the problem, the page where you have found it --> `

Well, dah, that's exactly why the user ended up here anyway.

> If applicable, state what could be done to solve the problem, such as "Rephrase the description" or "Use an example program that actually runs"

Could be left there, but still rather obvious.

The only part I have no problems with is:

> `+<!-- Thanks a lot for your contribution. --> `


<br>

And yes, this is not minimalistic to me. It's some bloated paperwork that I as a contributor will have to read for no good reason.

**Comment by nxadm** [comment]
The COC was discussed last year. The consensus was this:
"We are a bunch of volunteers developing Perl 6 and Perl 6 applications, and try real hard to be nice to each other."

https://perl6.org/community/

**Comment by JJ** [comment]
We already dismissed the CoC...

**Comment by JJ** [comment]
This issue has been open for some time now. It's better if you say your
opinion before somebody acts on it, because if you do it after, it's
useless work done by someone.
You are right about the TODOs. It's a nuisance. You are also right about
the stub. Another nuisance. Both things can probably be fixed, but we can
also just take templates away.
Everyone is still on time to decide on the PR template. If no one is
strongly *for* it, I'll close this issue removing the existing template and
that's that.

**Comment by AlexDaniel** [comment]
> It's better if you say your opinion before somebody acts on it

I agree, of course, but there are many tickets across many repos and I'm not omnipresent unfortunately. Sorry.

FWIW we do have a template in [rakudo repo](https://raw.githubusercontent.com/rakudo/rakudo/master/.github/ISSUE_TEMPLATE.md), which I also don't like… but most people seem to be OK with it, so maybe they'll also be OK with this doc issue template (as long as mentioned problems are resolved of course).

**Comment by JJ** [comment]
I might go for using the initial sentence, and also eliminating the ticks,
which might be useful for the PR template (if eventually adopted)

In fact, the issue that has used the template (besides mine) is a good
example of what I was looking for. It provided all the information needed
to fix it, and I could act straight away. I'm looking at old issues, and
it's almost impossible in many cases to figure out what is actually what is
expected from us.

**Comment by JJ** [comment]
Just to round up the discussion, the code of conduct has been raised repeatedly in the #perl6 IRC channel. [Here's one of the earliest references](http://irclog.perlgeek.de/perl6/2017-03-17#i_14281232).

**Comment by JJ** [comment]
I'm restoring the original title and reopening the issue.

**Comment by JJ** [comment]
There is [something like a code of conduct as a draft in the specs repo](https://github.com/perl6/specs/blob/master/S27-perl-culture-draft.pod6). Never made it to the specs, apparently.

**Comment by CIAvash** [comment]
The draft sounds good.

Also might be worth a mention here: [GNU Kind Communications Guidelines](https://www.gnu.org/philosophy/kind-communication.html)

**Comment by coke** [comment]
https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Code_of_Conduct.md
