### ISSUE TITLE
execute code on glot.io

### ISSUE THREAD

**Issue by ufobat** [Raku/doc#1866]
It would be a nice feature if you could edit and execute the code of the documentation.

See also: https://github.com/perl6/perl6.org/issues/99

**Comment by JJ** [comment]
Not all the code is executable... And I have no idea how to do that. We can
try, of course.

**Comment by zoffixznet** [comment]
> And I have no idea how to do that.

glot.io provides an API. perl6.party already has [the backend](https://github.com/zoffixznet/perl6.party/blob/2236f355ebdb54ac80558be3db62ed3b1464142c/app.pl#L52-L73) and [the frontend](https://github.com/zoffixznet/perl6.party/blob/2236f355ebdb54ac80558be3db62ed3b1464142c/assets/js/main.js#L14-L73) code that's almost complete.

Upcoming perl6.org update (in next ~2 months) will have it implemented and docs site could use its backend, unless we want to have its own runner.

**Comment by JJ** [comment]
Which we don't. It will be great to use that.

**Comment by 2colours** [comment]
Aaand https://github.com/Altai-man/docs.raku.org indeed targets this issue.

**Comment by Altai-man** [comment]
@2colours yes, it's assigned to me, so that when the new website is finally published, we'll be able to cleanup this repo by closing those tickets.

**Comment by coke** [comment]
Discussion for this issue now here: https://github.com/Raku/doc-website/discussions/54
