### ISSUE TITLE
Supply.reduce waits for the Supply to finish

### ISSUE THREAD

**Issue by lizmat** [Raku/doc#1875]
I think Supply.reduce should be listed as one of the methods that wait for the Supply to finish.

**Comment by JJ** [comment]
I'm not totally sure about this. It does create another supply, on one hand. Will it only work if all elements in the supply are available?

**Comment by JJ** [comment]
Yep, looking at source:

https://github.com/rakudo/rakudo/blob/5c8c7324e64d1edef0a07515e52bde8c56663717/src/core.c/Supply-factories.pm6#L481-L493

It totally does. So let's move it around.
