### ISSUE TITLE
Convert 1-file docs to epub with TOC

### ISSUE THREAD

**Issue by evb0110** [Raku/doc#1981]
## The problem
It would be very convenient to have the whole docs file in epub (or mobi, or fb2) format to use it on Kindles and other e-ink devices. The crucial thing is to convert the documents multilevel structure into epub/mobi's bookmarks, otherwise it's impossible to navigate a file of several thousand kindle screens.

## Suggestions
To have epub/mobi versions of the docs with TOC, which should be kept up-to-date to reflect current updates to the docs.

**Comment by JJ** [comment]
Converting HTML to epub is relatively straightforward; generating a table of contents is not big deal either. However, creating a concept index could be a problem, because the generated HTML links do not seem to be compatible with ePub. Would the first be OK?

**Comment by W4anD0eR96** [comment]
Treat index as an item of toc. Be an appendix.

**Comment by JJ** [comment]
But pandoc generates TOC automatically. And I think the way the index is
generated now (using 'id' attribute) does not work in ePub.

**Comment by JJ** [comment]
I don't know how useful is that kind of index in an ePub, though. You can
simply search for whatever you're looking for. Maybe for navigation, but
will have to see...

**Comment by evb0110** [comment]
I always navigate an epub with TOC, and when I make epub with calibre from html, there are usually problems with multi-level TOC.

**Comment by JJ** [comment]
So word and concept index might not be necessary, right?

**Comment by evb0110** [comment]
For me — no, I can live without them, especially on Kindle.

**Comment by FCO** [comment]
I don’t know if it’s my iphone’s Issue, but the ePub version is all blank for me...

**Comment by JJ** [comment]
Well, I've opened it in Firefox and it overlaps a bit, but other than that,
it looks OK...

**Comment by JJ** [comment]
Since the bigpage target has been eliminated because it does not work now, I'm reopening this issue to get it to work again...

**Comment by mendel** [comment]
I managed to generate the "bigpage" HTML with a patched `pod2bigpage`: https://github.com/perl6/perl6-pod-to-bigpage/pull/36. Apparently in the meantime the `epub` and `bigpage` Makefile targets were removed as broken, so those need to be restored, too: #3599.

**Comment by coke** [comment]
https://github.com/Raku/doc-website/issues/75
