### ISSUE TITLE
Object Equality Documentation

### ISSUE THREAD

**Issue by mcmillhj** [Raku/doc#2004]
## The problem

[Classes and Objects](https://docs.perl6.org/language/classtut) and [Object-Orientation](https://docs.perl6.org/language/objects) documentation does not talk about how to compare objects for equality.

## Suggestions

- add a section that documents how Objects should be compared for equality.

**Comment by fluca1978** [comment]
Does it suffice to add a section about `===` <https://docs.perl6.org/routine/===>?

**Comment by JJ** [comment]
Probably not; besides, that's object identity, not equality. But it's a
place to start...

**Comment by JJ** [comment]
A bit of documentation here: https://www.learningraku.com/2017/04/07/a-wealth-of-comparison-operators/
