### ISSUE TITLE
Collect repo traffic stats

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2045]
## The problem

The GitHub API [returns only traffic stats for the last 14 days](https://developer.github.com/v3/repos/traffic/#views). It would be interesting to check longer-term terms.

## Suggestions

It's a single query and it can be done every 7 days or so from some site, stored in JSON form and processed somehow. A cron job would probably do the trick.

**Comment by coke** [comment]
@dontlaugh  - would it make sense to add this as an infra task across all the raku repositories?

**Comment by dontlaugh** [comment]
All things considered, it sounds interesting, yea. In the past GitHub has been brutal with their API limits, so we have to proceed carefully.

Let's close this here and open on Raku/infra?

**Comment by coke** [comment]
> Let's close this here and open on Raku/infra?

Done here, I'll let you open the infra ticket. Thanks!
