### ISSUE TITLE
Page on type system could be more systematic

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2063]
## The problem

It is not too clear [in this page](https://docs.perl6.org/language/typesystem#Attributes) what is the structure or context. Type declarators includes a section on "Introspecton", another subsection on "Attributes" with a subsection on "private attributes" and that's it... 

## Suggestions

The general text seems to be OK, but it could use some systematization and organization in sections and subsections and introductions to them, at least at the first and second level.

**Comment by coke** [comment]
This page has gone through many changes since the original ticket and I think the original items have been addressed.
