### ISSUE TITLE
 submethods concept from nowhere

### ISSUE THREAD

**Issue by eiro** [Raku/doc#2152]
## The problem

here

https://github.com/perl6/doc/blob/master/doc/Language/classtut.pod6#L36

is the use of submethod concept with no explaination about this concept

## Suggestions

explain the difference between a method and a submethod ?

**Comment by AlexDaniel** [comment]
FWIW there's a short but perhaps sufficient description on https://docs.perl6.org/type/Submethod, so maybe `X<submethods>` should be simply removed. I'm not sure why it was put there in the first place.

**Comment by eiro** [comment]
hello Aleks,

On Fri, Jul 06, 2018 at 02:10:42AM -0700, Aleks-Daniel Jakimenko-Aleksejev wrote:
> FWIW there's a short but perhaps sufficient description on
> https://docs.perl6.org/type/Submethod, so maybe `X<submethods>` should
> be simply removed. I'm not sure why it was put there in the first
> place.

written too late in the night ? :)

if you want me to provide a patch, i'll be glad but i don't know how
to test if my fix work.

marc

**Comment by eiro** [comment]
hello,

On Fri, Jul 06, 2018 at 02:10:42AM -0700, Aleks-Daniel Jakimenko-Aleksejev wrote:
> FWIW there's a short but perhaps sufficient description on
> https://docs.perl6.org/type/Submethod, so maybe `X<submethods>` should
> be simply removed. I'm not sure why it was put there in the first
> place.

putting the 2 bugs together, makes sense now: it was a L<>, not a X<> :)

for this i can provide a patch :)

marc

**Comment by JJ** [comment]
Reopening since this probably deserves a better page like #3062

**Comment by coke** [comment]
The new version of classtut addresses this.
