### ISSUE TITLE
TODOs all over

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2277]
## The problem

Several TODOs found in different pages. Check them out and work on them.

* [x] `5to6-nutshell`
* [x] `control`
* [x] `glossary`
* [x] `haskell-to-p6`
* [x] `js-nutshell`
* [x] `list`
* [x] `operators`
* [ ] `packages`
* [x] `setbagmix`
* [ ] `subscripts`
* [x] `syntax`
* [x] `typesystem` but this is already covered by #2232 
* [x] `Cool`
* [x] `IO::Path`
* [x] `Type::IO::Spec::Unix`
* [x] `Type::IO::Spec::Windows`
* [x] `Mix`
* [x] `Bag`
* [x] `Str`
* [x] `Submethod`

In the case they merit it, turn an item into a separate issue.

**Comment by Kaiepi** [comment]
I'll keep up with my work on the js-nutshell page. Sorry I've been absent so much lately, but I'll be able to work more next week.

If others familiar with JS want to help out with it, that'd be really helpful

**Comment by MorayJ** [comment]
I couldn't find any TODO in list (language/list or type/List) so have checked it as done...

**Comment by MorayJ** [comment]
I'm looking at the 'Cool' page. I'm not clear on when it's a routine and when it's a sub. I had assumed that routines that were only defined with 'method' were methods and anything that either was a sub, or has a sub alternative, is a routine. This isn't the pattern though. Any advice?

**Comment by zoffixznet** [comment]
> I had assumed that routines that were only defined with 'method' were methods and anything that either was a sub, or has a sub alternative, is a routine

It's easy to understand if you look at the types these objects are:

```
@Zoffix │ m: &say.^mro.say                                                                            │
1140   +camelia │ rakudo-moar b22edce40: OUTPUT: «((Sub) (Routine) (Block) (Code) (Any) (Mu))␤»               │
1140    @Zoffix │ m: "x".^lookup("say").^mro.say                                                              │
1140   +camelia │ rakudo-moar b22edce40: OUTPUT: «((Method) (Routine) (Block) (Code) (Any) (Mu))␤»
```

Subroutines are of type `Sub`, so they're subs. Methods are of type `Method`, so they're methods. Both of them inherit from `Routine` so you can refer as "routine" to either a method or a sub, and in the docs if both a method and a sub is provided, we generally use "routine" as the heading or whatever.

**Comment by coke** [comment]
Package covered by the explicit #4123

subscripts covered by the explicit  #4124

With that, all original items are closed or have their own tickets.
