### ISSUE TITLE
xt test for missing C in C<> (and let's use a allow-list for doc text)

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#2306]
See http://colabti.org/irclogger/irclogger_log/perl6?date=2018-09-13#l952

Basically:

https://docs.perl6.org/language/objects
> `Everything that is not a native value is an <object>`

https://docs.perl6.org/language/5to6-perlvar#General_variables
> `for more information use <.^methods> to introspect all the above.`

I think the easiest way is to have a whitelist of characters for the doc text where `<`, `>`, `^` and others are not allowed. The idea is that code-like thingies should be wrapped in `C<>` or something like that, and everything else is likely a mistake.

**Comment by JJ** [comment]
You lost me here. One thing is using `<Object>` instead of `C<Object>` (which is wrong) and other completely different is not using C<> at all, which is what I understand from your last sentence. Is that correct?

**Comment by AlexDaniel** [comment]
@JJ the point is that when using `<foo>` you end up with angle brackets in the rendered text. If we can check if rendered text includes weird symbols (like `<`) then we can find way more issues I think.

**Comment by coke** [comment]
The check would have to be on the rendered pod (we have Pod::Cache to generate the text file to test), but then creating a regex about what's allowed and what's not is problematic. If someone wants to write up the regex, I can put it into a test.

Note that several files include generated HTML, or discuss operators that include ```<``` and ```>```

I would be happy to close this out as "nice to have, but too much work"

**Comment by coke** [comment]
... Having re-read what I *just* wrote, perhaps testing the raw POD is a better solution after all, limiting the false positives and allowing us to work with a smallish window, say a few dozen characters.

Also, I wonder if a strict mode (for us) when generating pod would be better, forcing us to escape ```<``` if we're using it not as a POD directive; then this would be caught by one of the existing tests.

**Comment by JJ** [comment]
The wishlist label is more or less a synonymous for that. So you can just add that.

**Comment by AlexDaniel** [comment]
> I would be happy to close this out as "nice to have, but too much work"

No-no-no. I keep seeing a lot of missed tags and other shit in the docs. Even if we can get a list where half is false positives that'd help us to fix so many things at once.

**Comment by coke** [comment]
With the recent tests that go against the POD objects themselves, this was easier to implement than I original thought.

Created a draft PR for this: https://github.com/Raku/doc/pull/4257
