### ISSUE TITLE
Should CArray be documented as a type?

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2345]
## The problem

Awaiting answer to perl6/roast#478, for the time being it's only part of the nativecall and nativelanguage pages, it does not get its own reference page.

## Suggestions

Add that page, which will help also to place it within the class hierarchy and avoid errors

**Comment by JJ** [comment]
NativeCall is Rakudo-only, and not spec.

**Comment by Altai-man** [comment]
The answer is given already: we should not document CArray as a type of the language.
However, it is mentioned on nativecall page (https://docs.raku.org/language/nativecall#index-entry-CArray) and can be searched with "CArray". Closing, re-open if disagree.

**Comment by JJ** [comment]
This is a judgment call, actually, since CArray is part of the Synopsis, so it's an actual Raku type. The fact that, for the time being, is only found in NativeCall does not mean it's going to be there forever. Anyway, we can always re-open this when (or if) that happens, so I guess it's OK.
