### ISSUE TITLE
Suggest appearance improvements for the site

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2429]
## The problem

The web site is OK, but it could use some improvements from the UI design/UX point of view. We have no such kind of experts onboard, any kind of help would be welcome.

## Suggestions

Propose changes, mock them up and show them here before actually including them in the site.

**Comment by zoffixznet** [comment]
It'd be good to do this while at the same time also swapping to a dynamic app to resolve a bunch of other issues (like better controls for lang-versioned stuff and search).

I think @coke had some sort of design work done in a [private] branch.

**Comment by JJ** [comment]
@zoffixznet you mean #1246. That kind of thing is actually orthogonal to this issue, which was intended solely to encourage people to consider new CSS appearance.

**Comment by coke** [comment]
This ticket is superseded by the new site at raku/doc-website; any suggestions for style changes should now be solicited there.
