### ISSUE TITLE
LTA placement of collation docs

### ISSUE THREAD

**Issue by zoffixznet** [Raku/doc#2434]
As of Rakudo 2018.11, [the collation stuff](https://docs.perl6.org/language/experimental#index-entry-%24%2ACOLLATION-%24%2ACOLLATION) will no longer require `use experimental :collation;`. However, the way that feature is currently documented is under the title "Experimental features".

It probably should be changed now or some time in the future, after 2018.11 release.

![image](https://user-images.githubusercontent.com/5747918/47945630-b9b95300-ded9-11e8-91ef-266b2eacf5ac.png)

-----------------

Also https://docs.perl6.org/routine/unicmp has (so far experimental) note in it.

**Comment by zoffixznet** [comment]
> That probably means that the API will no longer change, right?

Correct. It's being released as part of 6.d language

**Comment by zoffixznet** [comment]
Also https://docs.perl6.org/routine/unicmp has `(so far experimental)` note in it.

**Comment by JJ** [comment]
What's not so clear to me is what to do with this. Creating a new page would probably be the best way, because sticking it into the operator page would be a bit too much.
