### ISSUE TITLE
Runnable snippets using Rakudo-JS

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#2454]
It would be nice if it was possible to edit and run provided snippets directly in your browser.
See https://perl6.github.io/6pad/

**Comment by JJ** [comment]
Related: #1866

**Comment by pmurias** [comment]
I could look into it.
For now the big technical obstacle is that compiled rakudo.js is big and
takes long to load so it's not something that we might want to be on by
default on the docs page.

**Comment by AlexDaniel** [comment]
Hmmm. It seems to be 10.34 MB. Not sure if it's a big problem.

**Comment by JJ** [comment]
Still. Not something you would want in every page. A server side solution
(as the one suggested) might be a better option...

**Comment by pmurias** [comment]
Parsing the js is the bigger problem. The rakudo.js size should go down
once I put effort in it but for now putting in by default might not be a
clear win.

**Comment by 2colours** [comment]
@Altai-man essentially solved this via https://github.com/Altai-man/docs.raku.org (although not with Rakudo-JS but I'd assume that was the less important point)

**Comment by coke** [comment]
if this is closed by the new site, assigning to @Altai-man to resolve once the deploy occurs.

**Comment by coke** [comment]
Followup discussion here: https://github.com/Raku/doc-website/discussions/54
