### ISSUE TITLE
Drop different renderings (italics vs. upright) of class and role descriptions in type table

### ISSUE THREAD

**Issue by lucasbuchala** [Raku/doc#2477]
In the page https://docs.perl6.org/type.html, since there already is a column saying if the type is a class or role, I don't see the need to render the description text differently. In fact, I think this diminishs the readability. The change was introduce here: https://github.com/perl6/doc/commit/7ec008ca6d46c2aa8db2e631d2066d8abeadd69f. Please, can this distinction be removed and both descriptions rendered the same?

**Comment by coke** [comment]
This change was in htmlify, and is no longer an issue in the new site build at raku/doc-website
