### ISSUE TITLE
Indexing of % and %% is wrong

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2502]
## The problem

Searching for them takes you to [this fragment](https://docs.perl6.org/language/regexes#index-entry-regex_%2525-regex_%2525%2525-Modified_quantifier%3A_%2525%2C_%2525%2525), which does not exist.

## Suggestions

The real fragment is much simpler: https://docs.perl6.org/language/regexes#Modified_quantifier:_%,_%%

Maybe we are overdoing a bit the whole substitution thing...

**Comment by Altai-man** [comment]
Now it seems to work for `%`, `%%`, `%% (regex)` and `% (regex)` just fine and point to correct things. Can this be closed?
