### ISSUE TITLE
Create site-specific Mustache templates

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2508]
## The problem

After the excellent work done by @finanalyst , Pod::To::HTML is now templatable (since version 0.4.1). We're still, however, relying on Pod::To::HTML default templates for rendering this site.

## Suggestions

Spin off templates and put them in this repository, so that we don't depend on that other module for them.

**Comment by antoniogamiz** [comment]
Documentable supports this since version 1.3.0. If https://github.com/softmoth/p6-Template-Mustache/issues/34 moves forward, every type of page will be generated from its own template.

**Comment by JJ** [comment]
Thanks, @antoniogamiz

**Comment by antoniogamiz** [comment]
[Documentable v2.0.0](https://github.com/Raku/Documentable/releases/tag/v2.0.0) has been released with this feature, I will add the template to this repo.

**Comment by antoniogamiz** [comment]
From now on, the `head`, `header` and `footer` templates can be deleted. If you want to preview the result of the documentation using the new version, you can check https://raku.github.io/Documentable/integration-test/.

**Comment by coke** [comment]
This is superseded by the work in raku/doc-website.
