### ISSUE TITLE
Add navigation sidebar to docs website

### ISSUE THREAD

**Issue by ryn1x** [Raku/doc#2509]
## The problem
The docs are not as easy to navigate as they could be.

## Suggestions
Add a navigation sidebar to the docs website.

A really nice example is the one Elixir uses: https://hexdocs.pm/elixir/Kernel.html

Julia also does something similar, but not as nice as Elixir in my opinion: https://docs.julialang.org/en/v1/

<img width="1281" alt="screen shot 2018-12-11 at 9 50 27 pm" src="https://user-images.githubusercontent.com/19897899/49847732-e1c88b80-fd8e-11e8-8215-dd735b5b46b4.png">

**Comment by uzluisf** [comment]
Probably related: #2138

**Comment by coke** [comment]
there is now a sidebar in raku/doc-website; Any feedback, please report there.
