### ISSUE TITLE
Hiding something from indices does not seem to work.

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2531]
## The problem

The [`CONTRIBUTING`](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md) document says:

>  If you wish to hide a heading from any index, prefix it with the empty comment Z<>.

There seem to be a few instances of that being used, for instance [here](https://github.com/perl6/doc/blob/master/doc/Language/functions.pod6#L523). However, there does not seem to be any support for it in the generating script (`htmlify.p6`) and it does not seem to actually be working, since that function is actually inserted.

## Suggestions

That paragraph was inserted by @gfldex, apparently, [3 years ago](https://github.com/perl6/doc/commit/1fb0a757490fbeb06171fffae9d8ea34d7578c46). I don't know if it's simply a non-working feature or something that should be removed from the site. Some clarification from someone who remembers the rationale about it will help.

**Comment by coke** [comment]
Suggestion: if it doesn't work, let's remove the comment and close this ticket, esp. in the absence of an issue asking for the feature.

**Comment by coke** [comment]
Looks like this text was already removed.
