### ISSUE TITLE
"p6doc -f exit" doesn't work

### ISSUE THREAD

**Issue by arnesom** [Raku/doc#2532]
## The problem
> p6doc -f exit
No documentation found for a routine named 'exit'

it doesn't show up in "p6doc list" either.

## Suggestions

Is shown as "sub exit" on these pages
https://docs.perl6.org/routine/exit
https://docs.perl6.org/language/routines#sub_exit

So perhaps rename from "sub exit" to "exit"?

**Comment by JJ** [comment]
Thanks for the report. We really have to do something about p6doc #2166 #2014 #2103

**Comment by JJ** [comment]
In my case it answers "no documentation exists for *method* exit". So we'll have to check this out really well.

**Comment by frithnanth** [comment]
Here everything is working fine and I get this:
```
$ p6doc -f exit
In Any
  sub exit

Defined as:

    sub exit(Int() $status = 0)

Exits the current process with return code $status.
```
```
$ perl6 -v
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```
```
$ zef info p6doc
[…]
- Info for: p6doc
- Identity: p6doc:ver<1.002001>
[…]
```

**Comment by JJ** [comment]
I'm using it locally. Maybe I need to build some stuff. What Perl 6 version
are you using?

**Comment by arnesom** [comment]
@JJ 2018.12

**Comment by JJ** [comment]
I have built the documentation, and used bin/p6doc exit, and it still does
not work. Are you doing the same, or are you installing the documentation
as indicated by @frithnanth?

**Comment by arnesom** [comment]
I have installed p6doc. It is the same version (1.002001).

**Comment by stmuk** [comment]
I wouldn't expect "p6doc -l" to show "exit" and can't reproduce any failure of "p6doc -f exit"  with a fresh build (everything fresh from git). I think there is something broken in your environments and "p6doc" is fine.

Are you trying to run p6doc "uninstalled" (directly from the source directory) or maybe the index is corrupted? What does "p6doc path-to-index" say? If you delete the index file and recreate it using "p6doc build" does that fix things? Does "P6DOC_DEBUG=1 p6doc -f exit" offer any insight?

Does fully installing via "zef install p6doc" fix your problems?

**Comment by stmuk** [comment]
> Thanks for the report. We really have to do something about p6doc #2166 #2014 #2103

You are mistaken. None of these tickets are to do with the p6doc command line utility. They all refer to installing this whole repo (which is confusingly also called p6doc in module land and by zef) and all are CLOSED.

**Comment by coke** [comment]
p6doc is no longer a part of this repository; it is now called rakudoc and is part of http://github.com/raku/rakudoc
