### ISSUE TITLE
Colon-pair details in REPL look buggy

### ISSUE THREAD

**Issue by fecundf** [Raku/doc#2536]
https://docs.perl6.org/type/Pair says "Colon pairs can be chained without a comma to create a List of Pairs. Depending on context you may have to be explicit when assigning colon lists." - and follows with examples, which led me to experiments, that raise more questions. I would think all 5 of these should say the same thing but instead give 3 different answers. Does the doc need an addition to describe this? Is it a problem with Rakudo Star 2018.10?
```
$ perl6
To exit type 'exit' or '^D'
> (:a1:b2:c3)
(a1 => True b2 => 1 c3 => 1)
> (:a1,:b2,:c3)
(a1 => True b2 => True c3 => True)
> :a1,:b2,:c3
(a1 => True b2 => True c3 => True)
> :a1:b2:c3
a1 => True
> :a1 :b2 :c3
a1 => True
```

**Comment by cfa** [comment]
This behaviour appears to be unchanged since 2015.12:

```
15:27 | cfa         | bisectable6: my @a = :a1:b2:c3; say @a.elems
15:27 | bisectable6 | cfa, On both starting points (old=2015.12 new=f2ed3db) the exit code is 0 and the output is identical as well
15:27 | bisectable6 | cfa, Output on both points: «1␤»
```
FYI, documentation was added in [this](https://github.com/perl6/doc/commit/31ac0d1) commit.

(CC @AlexDaniel, who mentioned an old RT ticket about this just now.)

**Comment by AlexDaniel** [comment]
* RT#131089 [open]: https://rt.perl.org/Ticket/Display.html?id=131089 `Different parsing of combined colonpairs`
* RT#125353 [open]: https://rt.perl.org/Ticket/Display.html?id=125353 `[BUG] %(:a:b) ignores all elements after the first one`
* RT#124553 [new]: https://rt.perl.org/Ticket/Display.html?id=124553 `Roast rakudo skip/todo test:./S03-operators/adverbial-modifiers.t line:170 reason: 'Multi colonpair syntax not yet understood'`

**Comment by cfa** [comment]
Thanks.

**Comment by JJ** [comment]
Added [this question in stackoverflow too](https://stackoverflow.com/questions/54050635/nosink-in-ast-nodes)

**Comment by coke** [comment]
Links to the bug reports & SO cover this, closing doc issue.
