### ISSUE TITLE
“interpolate”

### ISSUE THREAD

**Issue by isomorphisms** [Raku/doc#2588]
## The problem

https://docs.perl6.org/language/variables.html#Twigils

Interpolation and symbol tables. What?

## Suggestions

Explain at different levels, using useful, interesting examples for beginners (no calculators, no foo), time saving jargon for experts, and a short explanation of words like “interpolate” somewhere. All without creating so much documentation I could never get through it.

**Comment by AlexDaniel** [comment]
Honestly I have no idea what it's talking about.

> Twigils influence the scoping of a variable

That's clear to me, but to beginners reading the docs it probably isn't. So that part should be explained a bit more, I think.

> they have no influence over whether the primary sigil interpolates. That is, if $a interpolates, so do $^a, $*a, $=a, $?a, $.a, etc. It only depends on the $.

Interpolates what? i guess it's trying to say that the twigil doesn't have any effect on the sigil, but I still don't get it.

**Comment by finanalyst** [comment]
'interpolates' here is a long way from my understanding of the word. `"$a is here"` interpolates the value of $a into the string.

If $a is defined eg `my $a = 'ten'` then it will interpolate. But that does not mean $^a is defined, so it will not interpolate, irrespective of the sigil. So this section confuses me too.

**Comment by pmurias** [comment]
Maybe we should link it to a page that explains what interpolation is?

**Comment by treyharris** [comment]
I wonder if the original thinking of the author of this line (Felix Hermann in August 2012!) was to contrast Perl 6, not with Perl 5, but with the shell, where the sigil is an interpolation operator (you can assign `var=value` but not `$var=value` and `var=$value` is different from `var=value`.

I’d vote for simply removing the mention of interpolation here entirely.
