### ISSUE TITLE
Change UI for docs pages, shortening and adding a "expand" option

### ISSUE THREAD

**Issue by isomorphisms** [Raku/doc#2593]
## The problem
There is too much detail and the docs are too long, although I’m sure someone needs each individual piece.

## Suggestions

The perlpod files should use a couple expander commands, like “people who need to know more about ___ will want this extra paragraph.”

In the display end this could be rendered in different ways but one would be a + that expands more text for those who want it.

**Comment by JJ** [comment]
Sorry, add what?
If you're talking about a redesign of the documentation system, there are several issues open for that: #2392 for instance.

**Comment by coke** [comment]
Before someone works on the tech to enable this, can you provide a concrete example of contents on a page you'd want this applied to?

**Comment by coke** [comment]
Rejecting ticket for now; if we decide we want something like this, it's going to be website specific and should be opened on raku/doc-website.

Thanks for the suggestion.
