### ISSUE TITLE
EVAL with Perl5

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2643]
## The problem

EVAL can use `lang => Perl5` as a parameter, according to the source. However, it needs to have Inline::Perl5 installed.

## Suggestions

Since Inline::Perl5 clarify what is the status of this, and add to documentation if necessary.

**Comment by stoned** [comment]
I believe this is now documented, and can be closed, am I wrong ?
See https://github.com/Raku/doc/blob/d59669f39b83aa23aa7ee98e9231c9102f52a8c0/doc/Type/independent-routines.pod6#L93

**Comment by JJ** [comment]
Please refer to it from the current PR so that it can be closed when merged.

**Comment by stoned** [comment]
Also see #3733.
