### ISSUE TITLE
Too many :skip-tests

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2738]
## The problem

This issue #2737 fixed incorrect code that was skipped because it dutifully raised a syntax error. There are 377 `:skip-test` in the documentation; quite a lot don't have anything in the way of explanation. 

## Suggestions

It's a bit too many to check out exhaustively, but at least those that have no explanation should be revised. In some cases it might be better to use :preamble so that they compile, in others offer something as an explanation of why they are skipped; in yet other cases they might actually be incorrect and we would be skipping compilation for no reason.

**Comment by coke** [comment]
Just reviewed all the remaining :skip-tests, unskipped several, changed some to `:lang` declarations. Remaining ones are fine.

**Comment by coke** [comment]
btw, there is also util/unskip.raku added in 2021 that converts skips to solos if needed or just runs them if possible.
