### ISSUE TITLE
Create a deployable version of the doc infrastructure

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2756]
## The problem

The (hopefully provisional) demise of the docs.perl6.org has made clear we don't really have a reproducible way to deploy the document server infrastructure. Even if it's simply a set of static pages, rebuilding them, putting it behind a static server such as nginx, and the infrastructure to trigger a rebuild every time there's a new push is not, as far as I can tell, done in a deployable way.

## Suggestions

Create, possibly in a separate repo, the infrastructure to deploy docs.perl6.org whenever and wherever it's needed, including triggering of rebuilds and setting up everything that's needed in order to get it running. 
A Docker-based container would really help, but it would be an alternative, since some people would want to deploy in a virtual machine or in some other way.

**Comment by coke** [comment]
Infra team handling this in regards to doc-website.

@dontlaugh
