### ISSUE TITLE
Lock::ConditionVariable is undocumented

### ISSUE THREAD

**Issue by Kaiepi** [Raku/doc#2788]
## The problem
See title. The article on `Lock` briefly mentions that the class exists, but doesn't mention how to use it or the fact that it can be accessed using `Lock::ConditionVariable`.

## Suggestions
Document it, preferably also explaining when you should use `Lock.condition`.

**Comment by JJ** [comment]
Also covered by #3844  (sorry, I didn't see this one when I created the other)
