### ISSUE TITLE
Try out EVAL :compile-only

### ISSUE THREAD

**Issue by coke** [Raku/doc#2819]
See https://github.com/rakudo/rakudo/commit/d41f162da02916eebc27018d918a556e9c9e71b3

Might be possible to switch back to EVAL testing if this  helps address the memory issue recently raised.

**Comment by JJ** [comment]
That was pretty much fixed after the latest addition by @taboege. It's using a stable feature of NQP, which I guess is as stable (or not) as an experimental feature in current Rakudo master. Using that has got its disadvantages (like no error message if it fails, although that can be fixed easily), but speed _and_ memory are both taken care of.
