### ISSUE TITLE
Keep an eye on 6.e.PREVIEW

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2831]
## The problem

The pragma is going to be available from 2019.06, and we need to keep an eye on features releases under the preview to incorporate them in the documentation.

## Suggestions

Let's keep this issue open, and list below what we will incorporate into the documentation. 

Don't close it until 6.e.PREVIEW becomes 6.e (or all features have been incorporated).

**Comment by coke** [comment]
This is covered by the checklist tickets created for each release (new things that may or may not be scoped to 6.e), and by #302
