### ISSUE TITLE
xt/aspell.t crashes

### ISSUE THREAD

**Issue by coke** [Raku/doc#2832]
Noticed a hanging file with aspell.t, fixed in 2d276d10.

However, then when running a full test of xt/aspell.t to insure no other breakages, noticed this:

```
$ xt/aspell.t
...
ok 234 - doc/Type/Scalar.pod6 has no spelling errors
ok 235 - doc/Type/Scheduler.pod6 has no spelling errors
ok 236 - doc/Type/Semaphore.pod6 has no spelling errors
ok 237 - doc/Type/Seq.pod6 has no spelling errors
ok 238 - doc/Type/Set.pod6 has no spelling errors
Unhandled exception in code scheduled on thread 4
too many open files

# Looks like you planned 389 tests, but ran 238
```

**Comment by JJ** [comment]
We can work around this, but this is not really a doc repo bug. Did you open an issue in Rakudo?

**Comment by coke** [comment]
I did not triage it to know it's a problem with rakudo and not the script. In the meantime, our test is failing, so we need to track that here.

**Comment by coke** [comment]
the Proc::Async bug has been fixed, xt/aspell.t now runs to completion if you're using a (very) recent rakudo.
