### ISSUE TITLE
(External) links to fragments not working

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2836]
## The problem

This is related to #2833, but it's a different problem. Apparently, links to fragments such as [this one](https://docs.perl6.org/type/Any#method_unique) have stopped working in Firefox, they do work in Chromium; they don't go do the part in the page where that link is, but to the top of the page. I have no idea why that happens. If you click on the index on the left it goes to an URL that looks exactly the same and does work. Is there some hidden character I'm missing? 

## Suggestions

This seems to happen since we have changed from a real-web-server to the default Mojo based server in the new (hopefully temporary) infrastructure. But I didn't know you needed something from the server to do this.

**Comment by chloekek** [comment]
It seems to happen because the focus is placed on the search field after opening the page. The search field is at the top of the page, and takes focus, which means it scrolls to near the top instead of to the targeted heading.

**Comment by JJ** [comment]
Oh, wow. Good catch!

**Comment by JJ** [comment]
This was broken by @antoniogamiz when he fixed #2657

**Comment by antoniogamiz** [comment]
As @rfold said in [the IRC Channel](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-07-19#l125) it looks a bug.

Anyway, my changes fix the problem.

**Comment by JJ** [comment]
Now it's broken in a different way:
![Screenshot from 2019-07-19 18-39-07](https://user-images.githubusercontent.com/500/61551104-8a8d4680-aa54-11e9-8937-3d1f63419cc5.png)
I don't understand why, but it's definitely related.

**Comment by JJ** [comment]
It does reach the fragment, that's true.

**Comment by Altai-man** [comment]
I don't see the rendering problem you mentioned on "Modules" page and URLs are working now. Please, re-open if disagree.
