### ISSUE TITLE
The binary-based CI test is broken

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2859]
## The problem

Travis uses Ubuntu 14.04, but the current HEAD binary apparently is compiled in another version that needs a GLIBC version higher than what can be currently installed. This produces this error:

```
perl6: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by //tmp/whateverable/rakudo-moar/6f8442ada535b58806ee82d07124de45d5f6a739/lib/libmoar.so)
```

## Suggestions

* We could eliminate this test
* We could use another binary, but I don't know which.
* We could try and upgrade GLIBC, but I really have no idea how. I have tried to search for repos where it's available for this specific version, but it does not seem to be.

Any other idea?

**Comment by JJ** [comment]
Apparently the only way out of this is to upgrade the environment to 18.04. So I guess the only solution will be to change the binary...

**Comment by AlexDaniel** [comment]
See https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270/20

And somebody says:

> My interpretation is that, Bionic is available, but in beta since it isn’t announced. Time to add them to the matrix!

So can you just disable the test until travis adds 18.04 (probably soon?).

**Comment by AlexDaniel** [comment]
Also, can you try changing this:

https://github.com/perl6/doc/blob/86954b9cf86ec3a867e21f097dcb26df5200a34a/.travis.yml#L7

To `bionic` to see what happens?

**Comment by AlexDaniel** [comment]
OK, `bionic` does seem to work but the issue is still there. Turns out bionic has 2.27 and 2.28 is needed. Uhhh… I don't know then.

**Comment by JJ** [comment]
Well, we're getting closer...

**Comment by JJ** [comment]
2.28 is Cosmic... I don't think Travis supports that.

**Comment by JJ** [comment]
I am not closing because
* It would be better to find another binary environment. Just are minder, this was a *canary in a mine* kind of feature that was a binary version of HEAD and told us also if something was wrong, or too slow, with the current Rakudo HEAD
* If we're note, we will have to simply disable everything and maybe opt for two different docker environments or whatever. In any case, the script is prepared to work with the two possible environments, so there's some dead code there we might want to get rid of.

**Comment by coke** [comment]
the CI test was for testing the site build, which we no longer do in this repo - .circleci was removed
