### ISSUE TITLE
Declarator token is part of declarator rule

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2872]
## The problem

Rule appears as part of [declarator token](https://docs.perl6.org/syntax/rule)

## Suggestions

Check how it's indexed and fix it.

**Comment by Altai-man** [comment]
Hmm, where? It does not seem to me, can you please clarify?

**Comment by coke** [comment]
Is this because the heading is "Declarator rule rule"?

**Comment by coke** [comment]
See discussion linked ticket.
