### ISSUE TITLE
Create a "How to blog about Raku" page here.

### ISSUE THREAD

**Issue by ghost** [Raku/doc#2898]
*(Originally the issue was titled “TIOBE” and was later repurposed)*

I use these sites as part of research for programming languages:

- https://tiobe.com/tiobe-index
- https://tiobe.com/tiobe-index/programming-languages-definition

I noticed that Perl is listed, but not Perl 6. I contacted the site runners and
received this response:

> In order to qualify for the TIOBE index one of the requirements is that you
> have at least 5,000 Google hits for your programming language. Here is the
> result for Perl 6: Unfortunately, there are only 4,010 hits.

Here is the link they are using:

https://google.com/search?q=%22perl+6+programming%22

Perhaps this phrase could be placed in some prominent places to get the results
up?

**Comment by AlexDaniel** [comment]
Oops, sorry about the labels, I didn't notice the issue moved :)

**Comment by JJ** [comment]
@AlexDaniel no problem :-)

**Comment by coke** [comment]
IMO, this isn't a topic for the official documentation; I suggest adding a discussion one one of the community based raku/ sites to track this topic.
