### ISSUE TITLE
Is there a good reason why we're not using jQuery CDNs?

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2906]
## The problem

The files [are in `assets` directory](https://github.com/perl6/doc/tree/master/assets/js) in this repo.

## Suggestions

Eliminate them and just point the HTML snippets to one of the official CDNs.

**Comment by AlexDaniel** [comment]
I am against the use of CDNs when we can easily serve the files ourselves. Some people agree https://github.com/perl6/doc/issues/652#issuecomment-230087753.

**Comment by JJ** [comment]
Can you please clarify why?

Using CDNs allows us to use the latest version so that we don't have to
worry about updating these files from time to time. But if we decide to
have them in our very repo, the right way to do it would be to create a
webpack deployment file that downloads and generates whatever version we
have. Having them in the repository is the least optimal option.

**Comment by AlexDaniel** [comment]
Yeah, and it also will make users execute unknown third-party javascript from a third-party source. You can fix that [using SRI](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/), but that negates the benefit of having ever-changing versions.

**Comment by JJ** [comment]
El jue., 18 jul. 2019 a las 19:40, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> Yeah, and it also will make users execute unknown third-party javascript
> from a third-party source. You can fix that using SRI
> <https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/>,
> but that negates the benefit of having ever-changing versions.
>
We'll, it still is third-party javascript, only we're also hosting it in
our own repo. I don't think anything is going to be safer than the official
CDNs.

I'll check and see what are the best practices in this area and try and
stick to them.

**Comment by AlexDaniel** [comment]
There was one unnecessary “third-party” in my comment :)

See also: https://meta.stackoverflow.com/questions/258288/use-of-ajax-googleapis-com-not-china-friendly

**Comment by JJ** [comment]
But check out #3 in the answer. We can use MAXCDN, for instance.

**Comment by JJ** [comment]
The advice here is to use jQuery's own CDN with a statically hosted
fallback version
https://www.dotnetcurry.com/jquery/1020/jquery-cdn-fallback-best-practices

**Comment by AlexDaniel** [comment]
You sure about 3? :)

![image](https://user-images.githubusercontent.com/5507503/61480332-6d963c00-a99e-11e9-95db-14bbed47f3f7.png)


Can we discuss this in problem-solving, btw? I see that what we do is inconsistent. rakudo.org selfhosts everything, moravm.org uses https://code.jquery.com/jquery.js, perl6.org uses https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js.

I think deciding what to do once and then using that for every web resource is a good idea.

**Comment by JJ** [comment]
Yep, what it says is that you're not going to get the same performance out
of your local, non-replicated server than from a CDN.
I don't see why this should be consistent across all repos. It's not as if
we're deciding on a new mascot... But whatever. The more opinions are
heard, the better.

**Comment by AlexDaniel** [comment]
> I don't see why this should be consistent across all repos

For example, if `googleapis` is fragile for countries with restricted access to the internet, then we want to have fallbacks everywhere we use it.

> what it says is that you're not going to get the same performance

It depends. https://thethemefoundry.com/blog/why-we-dont-use-a-cdn-spdy-ssl/

**Comment by AlexDaniel** [comment]
Also, it doesn't look like our performance is bound by jquery, and instead search.js is an issue:

![image](https://user-images.githubusercontent.com/5507503/61483111-cec10e00-a9a4-11e9-8e59-abab8884e523.png)

**Comment by coke** [comment]
search.js is definitely an issue - was hoping most of it would eventually go away by making the site dynamic instead of static.

**Comment by JJ** [comment]
We could create a deploy script that downloaded jquery _and_ minified
search.js...

**Comment by coke** [comment]
followup on https://github.com/Raku/doc-website/discussions/115
