### ISSUE TITLE
Create a web deployment script

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2909]
## The problem

For the time being, it would download needed scripts and minify search.js. I don't know if something else would be needed. This would solve #2906 in a satisfactory (I guess) manner.

## Suggestions

Use whatever JS tool is fashionable nowadays. I think it's webpack, but will have to dig a bit deeper.

**Comment by JJ** [comment]
This would also offload all the JS-related things from the build script that is taking now a long time #2498

**Comment by coke** [comment]
This issue is obsoleted by the work in raku/doc-website repository.
