### ISSUE TITLE
Migrate from Mojolicious to Cro

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2910]
## The problem

In general, the doc site can be deployed as a set of static pages. Far as I can tell, what the Mojolocious app does is to check if some asset for generating CSS has changed and recompile it.

## Suggestions

I'm not sure we even need to do that. As a matter of fact, if we use a deploy script as indicated in #2909 we might include it there so that it's run every time it's deployed. But it would be interesting to explore the possibility anyway.

**Comment by coke** [comment]
Can already run the new doc-website in Cro (even if the prod site there is static to start).
