### ISSUE TITLE
Seq MRO is wrong

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2919]
## The problem

It's

    class Seq is Cool does Iterable does PositionalBindFailover

it [should be](https://github.com/rakudo/rakudo/blob/090f3f1b45c1af1e3550eaf32159fe88b7a43c04/src/core/Seq.pm6)

    class Seq is Cool does Iterable does Sequence

> This code is [two years old](https://github.com/rakudo/rakudo/commit/cc2a064395aa4849208bb553bda699b8252c910f). We really are going to need some tooling to keep stuff in sync.

## Suggestions

Wait until #2918 is solved, fix it and review the whole document looking for any other error.

**Comment by dumarchie** [comment]
Resolved by 1b1fe100b294b6e9b59843890118d91d432bb7c6.
