### ISSUE TITLE
build broken (OS X)

### ISSUE THREAD

**Issue by coke** [Raku/doc#2926]
## The problem

`make` dies for me (on OS X) with:

```
===SORRY!=== Error while compiling /Users/coke/sandbox/perl6-doc/./build/Type/Enumeration.pod6
Colon pair value 'enum Norse-gods <Þor Oðin Freija>;' too complex to use in name
```

git blame shows these were added back in 2018, so this isn't a recent doc change causing the issue. (I haven't tried to build in some time)

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
$ perl6 --version
This is Rakudo version 2019.07-91-gdcf8c16d4 built on MoarVM version 2019.07-17-ga7563e71b
implementing Perl 6.d.
```

**Comment by Altai-man** [comment]
Can you bisect it between vanilla 2019.07 and your version? It works for me on 2019.07.

**Comment by JJ** [comment]
I don't think it's going to be specific of OSX either. Also, most probably not a doc bug...

**Comment by coke** [comment]
I cannot easily bisect this, no.

**Comment by JJ** [comment]
This probably no longer applies with the new build system, right?

**Comment by coke** [comment]
Tried running 'make html' (close as I can get to the original task), after installing Documentable. It took 43 minutes but did eventually complete.

**Comment by JJ** [comment]
43 minutes is *a lot*. But I've been avoiding the latest versions for that
reason.
