### ISSUE TITLE
Move HTML/CSS/js out of the repo

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2931]
## The problem

Right now there's an external repo (https://github.com/perl6docs/perl6docs.github.io) which includes all the static pages, as well as the static assets. That might or might not be the final destination, but the point is that all assets in the assets and html folders are copied there to be deployed. 

## Suggestions

We could simply host them there as the primary source, and delete them from here. That repo could be included as a subtree of this one, instead of using rsync to copy (as I do now)

**Comment by antoniogamiz** [comment]
Maybe create an orphan branch called `doc-assets` would be a better solution.

**Comment by coke** [comment]
-1 on removing them from the repo. If we're generating the site, the fact that it's a static site is an implementation detail. We should be able to build/deploy a self-contained site (whether it's static or dynamic) without having html/css on a separate static site.

**Comment by coke** [comment]
We've split the website into a separate repo, so all the assets should be in that repo, not this one, as JJ intended. I'll make sure the assets are removed (along with all of html/) as part of this migration (which is targeted for end of this month)

**Comment by coke** [comment]
We got there.
