### ISSUE TITLE
My document on Perl 6 Regex for non-Perl languages

### ISSUE THREAD

**Issue by ajs** [Raku/doc#2942]
## The problem

I've written a fairly long document, modeled on the Perl 6 Regex page in this documentation suite, that is aimed at non-Perl languages thinking about integrating Perl 6 Regex. It attempts to isolate language-specific features from non-language-specific features and document only the latter as a stand-alone standard. It has a very distant and half-hearted secondary goal of listing everything that it doesn't include form Perl 6 Regex in that standard.

So, why do you all care? The document may have some sections that, because they're attempting to explain the same things as the Perl 6 Regex doc, would be useful to lift.

If so, I'm offering the entire document under the Artistic 2.0 License, to the Perl community. Take from it what you wish.

## Suggestions

Here's the posting:

http://ajs.github.io/tools/your-regex-here/

and here is the Markdown:

https://raw.githubusercontent.com/ajs/tools/master/docs/_posts/2019-08-06-your-regex-here.md

There is no POD format version.

**Comment by JJ** [comment]
Thanks a lot for the link, but I'm not sure what the issue is here... If you want to add something to the documentation, we'll happily review your PR and accept it when it's ready. 
Anyway, I'll check and maybe add a link from some relevant section. Thanks!

**Comment by ajs** [comment]
There's no "issue" per se. It's just that there may or may not be elements of this document that you find helpful in expanding the Perl 6 Regexes document. If so, I'm giving you this doc under the appropriate license to make use of as/if you wish. It's also moved since I sent you this, and is being maintained here:

https://github.com/ajs/Gen6-Regex/blob/master/YOUR-REGEX-HERE-POSTING.md

Also, I've posted some specific concerns about the Perl 6 Regex documentation to reddit here:

https://old.reddit.com/r/perl6/comments/cp743r/some_regex_questions_not_clear_in_the_docs/

I can submit each of those as issues if you like. I wish I had time to update the docs, but having taken on my own major documentation task, my tuits are getting thin.

**Comment by coke** [comment]
Thanks for the submission, but we don't have enough staff to review our own docs, and we don't have the ability to review your docs for potential submissions. We'll add a link to our wiki so perhaps future authors can take advantage.

**Comment by raiph** [comment]
It makes sense to me to close this issue but I've created [a PR to add this important blog post to CCR](https://github.com/Raku/CCR/pull/5).
