### ISSUE TITLE
How was type-graph.txt generated. Can we update?

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#2945]
## The problem
Main reference is Issue #2584

TypeGraph has been spun off. The data comes from a file type-graph.txt.

Problems:
1. It would seem that 'type-graph.txt' was generated 7 years ago, but it is not systematically updated. There are undocumented classes.
1. Whilst in principle the diagrams are useful to some, they are often too small (too much detail is included, making the diagram small when rendered).
1. Generating the data from class introspection has the drawback that some classes/methods are implementation dependent, not Perl 6 language dependent

## Suggestions
1. Create a program to generate a primary list of strings for `type-graph.txt` by introspection
1. Create a black list of implementation classes/methods to be eliminated from `type-graph.txt`

Not sure how to handle the problem of generated graphs being too small. Is it possible to generate linked graphs so that a dependence chain over eg. 3 links long is generated in another svg file that can be opened?

**Comment by antoniogamiz** [comment]
Maybe @moritz can add some useful info about how it was generated.

**Comment by JJ** [comment]
They can be blown up by clicking on them; a legend was added to that extent. It's been proposed to do away with type-graph.txt by using introspection, but since it's been spun off, we don't need to change the interface. As such, this issue maybe corresponds more to that module, not to this one.
Also, type-graph.txt has been changed quite extensively in the last years...

**Comment by coke** [comment]
There is a test that checks to see if the file is correct ```xt/type-graph.txt``` - Run with a current Raku, it will report any errors found. There's also a script in the linked ticket.

I think those two items leave nothing left for this particular ticket to do, let's close it.

**Comment by 2colours** [comment]
This issue is not relevant for this repository anymore.

**Comment by coke** [comment]
Closing this in favor of #2584
