### ISSUE TITLE
Type graphs are generated, with very slight changes, every single time.

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2958]
## The problem

With very slight changes, SVG files for typegraph are regenerated every single time.
![Captura de pantalla de 2019-08-20 10-50-35](https://user-images.githubusercontent.com/500/63332843-98c2d100-c338-11e9-90e5-91692ffb13b7.png)

## Suggestions

This is still done by Perl6::Typegraph, but I'm not really sure at this time if this has been integrated to this site. At any rate, type graph does not change, so generated files should not change either.

**Comment by coke** [comment]
We no longer generate items in this repo, but as part of doc-website.
