### ISSUE TITLE
Clarify differences between .head and .first

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#2961]
Sometimes I use `.first` when I mean `.head`, just because I confuse them often. Example:

> \<AlexDaniel\> c: HEAD ```my @a = <foo bar baz>; my Seq $s = @a.Seq; say $s.first; @a[0] = 20; say $s.first```
> …
> \<lizmat\> AlexDaniel: not sure why you use .first instead of .head

It made me wonder if I'm not the only one, and indeed:
* ```\.first;``` 68 lines, 36 modules: https://gist.github.com/9293e27affd6d158e897650fa9584b02

Moreover, people often use `.grep().first` too (when they can just use `first` instead):
* ```grep.*\.first;``` 18 lines, 13 modules: https://gist.github.com/b8cc1f7fdbce9163c0a3e7b5a9467710

I think there's something wrong when a specifically dedicated feature is not being used. That being said, I don't see any downside in using `.first` instead of `.head`…

**Comment by coke** [comment]
I agree with @jnthn, closing ticket.
