### ISSUE TITLE
Parameterization vs. parametrization

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2967]
## The problem

We seem to using the [UK spelling of the word](https://wikidiff.com/parametrized/parameterized). One of them, at least (we could have gone all British and say *parameterise*)

## Suggestions

It seems weird that we *parameterize* a *parametric* Role. But I don't think we  have a policy on enforcing a certain kind of spelling here. Certainly parameterize is used consistently in the documentation now, with not a single instance of the other option. So we might just leave it as it is now, but with a test (or a rule) that it should remain so in the future.

**Comment by coke** [comment]
Historically we have leaned to us spellings in general. There's an Xtra test that will let us catch this already. I can add this word, sign the ticket to me if you like

**Comment by jnthn** [comment]
The spelling `parameterize` is used in the metamodel's method naming, and I doubt we'll be changing that, so it's probably best to stick with it in the docs also. That's what you get for having somebody British (increasingly ish... :)) design the MOP, I guess.

**Comment by JJ** [comment]
We should then add a test indicating we prefer this version

**Comment by coke** [comment]
test added in ddf8c69ab
