### ISSUE TITLE
Difference between rotor($batch, :partial) and batch isn't described enough

### ISSUE THREAD

**Issue by titsuki** [Raku/doc#2969]
## The problem

See:
+ https://docs.perl6.org/routine/rotor
+ https://docs.perl6.org/routine/batch

The `batch` document says:
```
If the number of elements is not a multiple of $batch, the last batch may have less than $batch elements, similar to .rotor($batch, :partial).
```

This explanation just say they are "similar" and doesn't provide a hint which one to use (i.e., `batch` or `rotor($batch, :partial)`.

## Suggestions

+ If there is a difference: This explanation should provide a hint which one to use.
+ If there aren't any differences: This explanation should say they are same.

**Comment by JJ** [comment]
Thanks for the report. We'll try to address it ASAP.
