### ISSUE TITLE
Create a principled way to test documentable on the actual documentation

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2972]
## The problem

In a first approximation, `documentable` needs to generate exactly the same URLs that there are now. Although these URLs are ad-hoc and not really specified (see [this issue in the problem-solving repository](https://github.com/perl6/problem-solving/issues/93)) we don't want to lose them in the process of revamping tooling.

## Suggestions

Test `documentable` with current static web pages and check that everything is OK. Or mostly OK.

**Comment by coke** [comment]
Since we've cutover, can we close this out?

**Comment by JJ** [comment]
I'm not totally sure this should be closed. Documentable testing is still hit and miss, and this specific aspect, for instance, is not really tested. Even if there are unit tests all over, there are integration tests that are not really there. The problem also is that there's actually no spec for how URLs should be generated. There's this [issue](https://github.com/Raku/problem-solving/issues/93), and then a [proposal](https://gist.github.com/antoniogamiz/9f7feb5b93a95d0c121ec0ba03d28b6a), but it's impossible to test without specs...

**Comment by coke** [comment]
So let's get a ticket for the specs, and the tests for Documentable can go in Documentable, and then this ticket is done.

**Comment by JJ** [comment]
I've edited the title. It's not really about testing Documentable, but about testing generated docs. And about specs we haven't even agreed we need one yet. I'll make this external, because I sill think there's some need for this. Besides, I see @Altai-man has self-assigned it.

**Comment by coke** [comment]
doc-website is using Collection; any future Documentable tests should be covered in https://github.com/Raku/Documentable, any tests of generated documentation files for Collection can go there.
