### ISSUE TITLE
When files in the cache are moved, documentable freezes

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2987]
## The problem

Once @tbrowder has added the new file, we have tried to generate the documentation and it stops.

## Suggestions

Opened [this bug report in Pod::To::Cached](https://github.com/finanalyst/pod-cached/issues/21) and [this one in Documentable](https://github.com/perl6/Documentable/issues/16)

**Comment by coke** [comment]
With the other repositories spun off this one, it's unclear to me that there's anything left for us to do in this repo.
