### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2988]
## The problem

The new documentation at https://docs-stage.p6c.org returns this error:

```
DevTools failed to parse SourceMap: https://docs-stage.p6c.org/e130654ff5/style.css.map
```

## Suggestions

This might or might not be related to #2986 , but who knows...

**Comment by Altai-man** [comment]
Still easily reproducible:
```
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://docs.raku.org/css/app.css?v=7
Source Map URL: ../a49185b3f5/style.css.map
```
on latest firefox.

**Comment by JJ** [comment]
The error is still there, in the developer console. [This is what Mozilla says about it](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors)

**Comment by coke** [comment]
What is generating the sourceMappingURL?

**Comment by Altai-man** [comment]
If the website replacement happens, this is no longer relevant.

**Comment by coke** [comment]
website replacement in progress on doc-website. Closing ticket
