### ISSUE TITLE
Include document specification in the documentation

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2994]
## The problem

Metadata is now included in the documents as part of the configuration.

## Suggestions

Spread the word via a document, and also the utilities that generate new documents.

**Comment by coke** [comment]
I'm not clear what the ask here is; which documents, which configuration?

**Comment by raiph** [comment]
@coke 

> I'm not clear what the ask here is; which documents, which configuration?

# "Documents"

> Metadata is now included in the documents

By that I think he means Raku documentation pages in this repo. An example of including metadata in documents is [this commit]((https://github.com/Raku/doc/commit/5b097bdedf0984a567418c824cb773133f0e0d5f) (one of several I see in the days leading up to JJ opening this issue).

> Spread the word via a document, and also the utilities that generate new documents.

The document he's suggesting is presumably one that says something like:

> We want 'metadata' added to doc blocks, or at least the main one for a page. Here's the guidelines blah blah.

# "Configurations"

"Configuration" is the term Damian Conway came up with for the hashes that can annotate a delimited Pod block as explained in detail in [Delimited Block](https://design.raku.org/S26.html#Delimited_blocks).
