### ISSUE TITLE
Remove htmlify.p6

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2996]
## The problem

It's been superseded by [Documentable](https://github.com/perl6/documentable). From today, documentation is being generated using documentable, so it's no longer needed.

Since this might cause problems down the line, and some issues, I'm creating this issue that will be closed when all problems have been ironed out.

## Suggestions

Check everything, from documentation to tests, for traces of use of htmlify.p6 and depending libraries.

**Comment by coke** [comment]
htmlify no longer appears anywhere in the repo. @JJ this can be closed now.

**Comment by JJ** [comment]
Thanks, @coke
