### ISSUE TITLE
Docker container build is broken

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3034]
## The problem

We need to adapt it to the new infrastructure, since [it's using the old make](https://cloud.docker.com/repository/docker/jjmerelo/perl6-doc/builds/c0abbf72-ab8c-4f38-a788-d4350efa3005)

## Suggestions

Rewrite the container.

**Comment by coke** [comment]
Another suggestion: update the make build rule to match the new build instructions.

**Comment by JJ** [comment]
The problem is that, as discussed elsewhere, that is no longer supposed to happen in this repository, according to the roadmap #2983 . So another, better, option would be to make this depend on spinning off the Dockerfile along with all other website-building tools...

**Comment by coke** [comment]
We are migrating the site build to doc-website, and the infra team has a build process that is working.
