### ISSUE TITLE
Some targets in the Makefile do not work any more

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3035]
## The problem

As a matter of fact, Makefile has been growing by accretion quite some time and this might or might not be totally related to #2983, but come from way before. It's quite clear from #3034 and #2998 that in many cases, maybe in most, Makefile is no longer current.
Check out #1057 too.

## Suggestions

Decide what to do about it, up to and including eliminating it and using Sake instead. And, of course, including it in the big spin-off that we should be doing.

**Comment by coke** [comment]
All the make targets relating to the build should be removed (build of site now handled in doc-website). Once that's done, any remaining items can be addressed one at a time.

**Comment by coke** [comment]
Done, only remaining Makefile targets are test related.
