### ISSUE TITLE
There's an infix <cmp>, an infix <<cmp>> and a routine cmp

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3038]
## The problem

Range use the first form, but [`DateTime`](https://docs.perl6.org/routine/infix:%C2%ABcmp%C2%BB) uses the second, most use a simple routine.

## Suggestions

Use a single angle everywhere.

**Comment by caseyjackmiles** [comment]
First time contributing; thinking of picking up this issue since it's labeled easy to resolve.

It's also labeled RFE: Is there some additional wording that needs to be added to classes that use `<cmp>`?

**Comment by JJ** [comment]
@caseyjackmiles thanks a lot! Well, it's an enhancement because it's not really a bug.

**Comment by caseyjackmiles** [comment]
Question on `=head` blocks: The end goal is to have all entries for `cmp` appear on https://docs.raku.org/routine/cmp correct? 

To do that, it looks like headings need to be updated to use `=head infix cmp` (without `sub`).
DateTime and Range use `sub` in their headings, which causes them to appear on separate listings:
* DateTime uses `=head2 sub infix:«cmp»` and appears on https://docs.raku.org/routine/infix:%C2%ABcmp%C2%BB by itself
* Range uses `=head2 sub infix:<cmp>` and appears on https://docs.raku.org/routine/infix:%3Ccmp%3E by itself

**Comment by JJ** [comment]
El dom., 24 may. 2020 a las 22:22, Casey Jack Miles (<
notifications@github.com>) escribió:

> Question on =head blocks: The end goal is to have all entries for cmp
> appear on https://docs.raku.org/routine/cmp correct?
>
> To do that, it looks like headings need to be updated to use =head infix
> cmp (without sub).
>

No, it indexes any kind of sub declaration, including infix

> DateTime and Range use sub in their headings, which causes them to appear
> on separate listings:
>
>    - DateTime uses =head2 sub infix:«cmp» and appears on
>    https://docs.raku.org/routine/infix:%C2%ABcmp%C2%BB by itself
>    - Range uses =head2 sub infix:<cmp> and appears on
>    https://docs.raku.org/routine/infix:%3Ccmp%3E by itself
>
>
The problem is the different type of quotes used, basically.
