### ISSUE TITLE
pod2onebigpage still uses the gen-pod-source that has been deleted

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3042]
## The problem

The program itself does not need it, but this generation script does, which means that we need to change that.

## Suggestions

Pod2onebigpage needs to be overhauled; maybe do this at the same time.

**Comment by coke** [comment]
Wasn't this removed around the time we stopped using htmlify?

**Comment by JJ** [comment]
No, it simply stopped working. We really need to fix it, we use it, for instance, to generate a single .epub.

**Comment by coke** [comment]
Now in https://github.com/Raku/doc-website/issues/75
