### ISSUE TITLE
Document if as adverb for use

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3049]
## The problem

These lines:

https://github.com/skinkade/crypt-random/blob/c1bf9393ab736ac5e5de2d0c3f56078c178cc071/lib/Crypt/Random.pm6#L5-L6

Seem to use `:if` as an adverb for selectively importing modules.

## Suggestions

Check out its usage, and document it.

**Comment by JJ** [comment]
It does not seem to be [in the Synopsis](https://design.perl6.org/S11.html#Compile-time_Importation)

**Comment by JJ** [comment]
It's using [`if`](https://github.com/FROGGS/p6-if), a very clever module from the ecosystem. Might be interesting to document it anyway, since it adds a small twist to the usual syntax.

**Comment by coke** [comment]
If it's using an ecosystem module, then we can close this ticket.
