### ISSUE TITLE
independent-routines is missing

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3051]
## The problem

[here's the URL](https://docs.perl6.org/language/independent-routines#sub_shell)

## Suggestions

Maybe some quirk in Documentable.

**Comment by antoniogamiz** [comment]
Mmm, what do you mean by "missing"? The url works fine.

**Comment by JJ** [comment]
It didn't when I checked. No idea.

**Comment by JJ** [comment]
[This one is missing](https://docs.perl6.org/type/independent-routines#routine_unique) There are some links in language, some in type. It's now in language, probably should be in /type: see #3059

**Comment by coke** [comment]
I can't find the missing link mentioned on Oct 16 in the source. Closing ticket, items like this will be caught by whatever solves https://github.com/Raku/doc-website/issues/72
