### ISSUE TITLE
Change all ocurrences of "Perl 6" to Raku

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3054]
## The problem

Part of #3046, the name of the language, if not the tools, has changed. We need to change all occurrences of the name to Raku.

## Suggestions

It's probably something that can be done automatically, although a manual review would not be a bad idea.

**Comment by nxadm** [comment]
We need to coordinate on timing. It would be confusing if the doc already referers to raku when most distributions only generate a perl6 binary (so far as I know all except rakudo-pkg).

**Comment by JJ** [comment]
This issue is specifically _not_ about the binaries. It's about the name of
the language, which I understand has already changed.

**Comment by coke** [comment]
This work is already done; any "Perl 6" left in the repo at this point is there for historical accuracy; any current references are now Raku.
