### ISSUE TITLE
docs.perl6.org looks bad in dark-themed browsers

### ISSUE THREAD

**Issue by 532910** [Raku/doc#3055]
Both bg and fg colors should be defined.
![image](https://user-images.githubusercontent.com/14617699/66762365-87b4bd00-eeae-11e9-9566-ee51849d6dfb.png)

**Comment by AlexDaniel** [comment]
Right, I used to see things like this in Firefox too but then somehow it stopped. What's your browser?

Either way, the proposed solution is right, both background and font colors should be explicitly defined.

**Comment by 532910** [comment]
Firefox + `$GTK_THEME=Adwaita:dark` + `browser.display.use_system_colors=true` + `browser.in-content.dark-mode=true` (not sure if the last one matters)

**Comment by 532910** [comment]
BTW, perl6.org looks fine.

**Comment by coke** [comment]
Much theming work has been done on the new site at https://github.com/raku/doc-website. Please review and if you find it still has issues, open a ticket

**Comment by 532910** [comment]
Is it available online?

**Comment by coke** [comment]
https://github.com/Raku/doc-website/blob/main/README.md#running-site

**Comment by 532910** [comment]
Looks nice, thank you!
