### ISSUE TITLE
Remove the vim mode line.

### ISSUE THREAD

**Issue by antoniogamiz** [Raku/doc#3058]
# Problem 

This issue comes from https://github.com/perl6/Documentable/issues/51, it's the same here.

# Solution 

~Add the line where missing~ Remove the line from every file.

**Comment by JJ** [comment]
Hum, I'm not sure it's that useful... I'm using Comma now...

**Comment by jonathanstowe** [comment]
I'd actually go with globally removing the vim modelines, there are other ways of determining the filetype and not everyone uses vim.

**Comment by vrurg** [comment]
@jonathanstowe I'm not really against removing these lines, but if memory serves me right, some editors recognizes the format to determine filetype. So, it could be useful sometimes.

Removal would make more sense when we move to `.rakudoc`.

**Comment by Altai-man** [comment]
>I'd actually go with globally removing the vim modelines, there are other ways of determining the filetype and not everyone uses vim.

Please.

Vim users should just configure their vim so that it applies the correct style for the file type, which would be a polite and simple solution that works for every file for them, instead of adding config lines in every single file which are redundant for a great chunk of other users.

**Comment by antoniogamiz** [comment]
The problem is that GitHub only recognises Pod6 files if you add the vim mode line.

**Comment by JJ** [comment]
Are sure it's that?

**Comment by antoniogamiz** [comment]
Check this:

- [Without vim line](https://github.com/antoniogamiz/Documentable/blob/fix-documents/docs/Language/configuration-file.pod6)
- [With vim line](https://github.com/perl6/Documentable/blob/master/docs/Language/configuration-file.pod6)

You can also check perl6/doc/doc, all files not rendering correctly do not have that line at the bottom.

**Comment by jonathanstowe** [comment]
Eugh

**Comment by JJ** [comment]
But I think the right way to address this is at the @github level. I'll try
and find the repo for the renderer, and raise an issue.

**Comment by AlexDaniel** [comment]
Support for Pod 6 was added here https://github.com/github/linguist/pull/4083/files.

@Tyil maybe you have an idea why it would work this way? It's really weird, my understanding is that `.pod6` files should just work.

**Comment by AlexDaniel** [comment]
Ah, I see. I uploaded these files as gists and peeked at them through github api:

* [without vim mode line](https://api.github.com/gists/336fedca4d120662501cb10655a4b4ba) – `language: "Pod 6"`
* [with vim mode line](https://api.github.com/gists/651865854d2663d5b962ed29ac66e303) – `language: "Perl 6"`

So there are two problems with it:
1. RakuDoc renderer seems to be broken, at least for that particular file
2. Vim mode line overrides correct language detection. Does it mean that the right vim mode line should mention rakudoc, or does it mean that it shouldn't override the correct detection?

Anyway, this should be fixed in linguist.

**Comment by Altai-man** [comment]
>The problem is that GitHub only recognises Pod6 files if you add the vim mode line

This is a github bug then. I believe we should investigate why https://github.com/github/linguist does that (https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3915 ?) and send a patch.

**Comment by JJ** [comment]
@AlexDaniel linguist is used to find out the language, but a different thing is used for rendering pages.
I've added a comment to the issue. The examples and heuristcs added to linguist do not have anything to do with the modeline, so the error must be somewhere else. However, the issue has been sitting there for a few months and it's not being addressed...

**Comment by coke** [comment]
Looking at the API results, if the vim mode is present, it's consider a Raku file. If not, it's considering a pod6 file. This is correct:

The files are all named pod6, so the type should default to pod6. With the vim mode present, it's showing as Raku (and the ft line includes ft=perl6).

The rendering for both files appears correct (pod syntax is highlighted in the gists I tried this in) as of now.

So, we should be clear to remove the mode line in the repository.

**Comment by coke** [comment]
Also, add an author test to avoid them sneaking back in.
