### ISSUE TITLE
"routine unique" page has a dead link (at bottom)

### ISSUE THREAD

**Issue by jubilatious1** [Raku/doc#3059]
## The problem

"routine unique" page has a dead link (at bottom):

https://docs.perl6.org/routine/unique

## Suggestions

Make this link live:

https://docs.perl6.org/type/independent-routines#routine_unique

**Comment by JJ** [comment]
Thanks for the report, we'll check it out.

**Comment by JJ** [comment]
This might be some problem with the *old* site, because it's generated correctly in the [new one](https://rakudocs.github.io/type/independent-routines#routine_unique)
(as a matter of fact, it's generated in both). So it might be a deployment problem that we'll have to check anyway.

**Comment by jubilatious1** [comment]
I see the page working for rakudocs.github.io , but I'm still seeing a dead link on the old docs.perl6.org site with both Safari and Firefox browsers:

https://docs.perl6.org/type/independent-routines#routine_unique

**Comment by JJ** [comment]
@jubilatious1 that's correct, which is why I say it's a deployment problem... I'll try to fix it anyway, even if the "old" site is not going to be updated (much) from now on.

**Comment by Prince213** [comment]
Doesn't seem to be a problem anymore. Closing...
