### ISSUE TITLE
p6doc finds all versions of installed Net::IP and displays all pod found

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3060]
## The problem

I'm working on my Net::IP module and have two different versions installed. When I execute:

    $ p6doc Net::IP

I get pod output from both versions.

I have not yet tested for this problem with any other module but mine as specified.

## Suggestions

Make the default operation show only the pod from the latest installed module version.

**Comment by JJ** [comment]
This is the *old* p6doc, right?

**Comment by tbrowder** [comment]
On Wed, Oct 16, 2019 at 13:44 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> This is the *old* p6doc, right?
>

Hm, good question. Let me check...

**Comment by tbrowder** [comment]
According to zef it's p6doc version 1.003.

**Comment by JJ** [comment]
That might be the version that's included here.

**Comment by coke** [comment]
p6doc is no longer a part of this repository; it is now called rakudoc and is part of http://github.com/raku/rakudoc
