### ISSUE TITLE
FAQ gives wrong advice about NativeCall

### ISSUE THREAD

**Issue by niner** [Raku/doc#3094]
## The problem

https://doc.perl6.org/language/faq#Nativecall_can't_find_libfoo.so_and_I_only_have_libfoo.so.1.2!
Answers the issue of "Nativecall can't find libfoo.so and I only have libfoo.so.1.2!" with:
"This is commonly seen on Debian-like systems. You need to install libfoo-dev package, to set a symlink for the missing file."

This advice is wrong.

## Suggestions

The correct solution is to add version information to the `is native` trait.
Wrong: `is native('foo')`
Right: `is native('foo', v1)` or: `is native('foo', v1.2)` depending on the library's API stability guarantees.

Of course it doesn't help that the nativecall documentation uses the unsafe variant throughout except for the ["ABI/API version" section](https://docs.raku.org/language/nativecall#ABI/API_version).

**Comment by JJ** [comment]
Thanks for the report. We'll get to it ASAP.

**Comment by JJ** [comment]
Would it better to start by improving the Native documentation?

**Comment by niner** [comment]
Of course, best would be to fix both. But the one does not depend on the other.

**Comment by JJ** [comment]
I've been having a look at the documentation, and it's true that the only reference to versions is in that section, even if it says there that the only safe way to use shared libraries is to refer to the version. As a matter of fact, all shared libraries are symbolic links to the real thing, so we might as well use the thing they link to. I'm working on an example that uses that.

**Comment by niner** [comment]
The only exception to this would probably be bundled libraries like libp5helper.so which comes with Inline::Perl5. Those will be unversioned.
