### ISSUE TITLE
Wrong advice in modules documentation

### ISSUE THREAD

**Issue by niner** [Raku/doc#3095]
`# Note that %?RESOURCES provides a C<IO> path object`
is wrong. It provides Distribution::Resource objects. %?RESOURCES provides access to additional resources bundled with the distribution. One should not think of those as files on a file system. The best way to use them is to pass them *unmodified* to the `is native` trait in the case of libraries or to call `.open` on them to get a file handle or to use one of `.slurp`, `.lines`, `.split`, `.words` or `.copy`.
Thus the sentence "Their installed location can be determined through the %?RESOURCES Hash indexed on the name provided" is quite harmful. The location should not matter! It is subject to arbitrary changes and it may change between compilation time and runtime, so it must not end up in constants.

"If your module requires extra processing during installation to fully integrate with and use non-Perl operating system resources, you may need to add a Build.pm6 file (a "build hook") to the top-level directory."

No, you need not and you should not. Build.pm6 has not been the tool of choice for this for years.
Use a `Distribution::Builder` like `Distribution::Builder::MakeFromJSON`

**Comment by JJ** [comment]
Thanks for the report. We'll take a look as soon as possible.

**Comment by JJ** [comment]
See also #3205

**Comment by cfa** [comment]
Related: #4248

**Comment by coke** [comment]
Finally resolved after a huge delay, thank you for the note!
