### ISSUE TITLE
Change templates and the rest of the code to point to the new repo

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3101]
## The problem

We have a new repository under a new organization. We need to change that.

## Suggestions

Do it fast.

**Comment by AlexDaniel** [comment]
I appreciate the effort but this just dropped all assignments from this repo. See https://colabti.org/irclogger/irclogger_log/raku?date=2019-11-25#l164 (also includes my angry rant).

**Comment by JJ** [comment]
Not a big deal. If someone wants to work on that specific issue, they'll
get reassigned to them all over again. They were never intended as hard
assignments, anyway.

**Comment by JJ** [comment]
Most of them are also closed. So, as I said, no big deal.

**Comment by AlexDaniel** [comment]
OK. I'm not sure what's going to happen with CI because IIRC that needs to be enabled in the organization separately, but I'm not sure. Let me know if you see any problems.

**Comment by JJ** [comment]
Sure. I think I have privs for that.

**Comment by JJ** [comment]
I can also use this chance to set up new GitHub actions instead.

**Comment by Altai-man** [comment]
@JJ this seems resolved with the relevant commit, is there anything else to update or can it be closed?

**Comment by JJ** [comment]
Besides translations of the README, only this line seems to be using the old repo

    util/issue-with-all-pod6.p6:    my $repo-path =  S[doc] = '/perl6/doc/blob/master/doc' with $d;

I think we still need to check it out...
