### ISSUE TITLE
Change the perl6 command line to raku

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3105]
## The problem

Since 2019.11, raku is available as an alias, and can be used like that.

## Suggestions

Look for occurrences in tooling and documentation and change it.

**Comment by veb7vmehra** [comment]
Hi sir, I am quite interested in contributing for raku and can solve this issue  but am not able to find out the website code in this repository. Where should I find it out @JJ

**Comment by JJ** [comment]
Hi, @veb7vmehra , thanks a lot for your interest. The website is generated from the /docs directory in this repo, using the Documentable utility, as specified in [the README.md](https://github.com/Raku/doc#building-the-html-documentation). In principle you needn't worry abou that: just check for "perl6" in examples using 

    `git grep perl6`

and where you find it (in examples), change it to `raku`. As you probably know, you should work in a fork of this repository, and when you're done, create a pull request and make a reference to this issue (saying simply #3105 in the commit, or closes #3105 if you think it's all that needs to be done).
Thanks a lot again and gold luck. We'll be around here (and in the #raku and #raku-dev IRC channels) just in case you need help.

**Comment by veb7vmehra** [comment]
@JJ Thanks for your help, Will make a pull request by tomorrow. Please also tell me how can I contribute more for Raku

**Comment by JJ** [comment]
Thanks! You can check any of the repositories in the perl6/ organization,
which are community-maintained sites and modules, as well as the Rakudo
organization, which includes the interpreter. Any contribution to any
module will be probably appreciated too.

**Comment by tinmarino** [comment]
I did change the command line command In #3272.
As done by hand, I listed other `perl6` appearance left

* Editor

ft=perl6
atom-language-perl6
\`\`\`perl6

* Site

doc.perl6.org
github.com/perl6
perl6maven
perl6advent
https://raw.githubusercontent.com/perl6

* Modules

Perl::ToPerl6
Perl6::Metamodel
PERL6LIB
PERL6_EXCEPTIONS_HANDLER
~/.perl6/
lang = 'perl6'   <- compiler language ('Raku' apparently)

**Comment by coke** [comment]
Did another pass just now, added some comments where I felt we needed to keep the perl6 but it looked out of place, left any external URLs, updated a few incidental references.
