### ISSUE TITLE
Populate results for "rakulang" query

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3108]
## The problem

If these pages are difficult to find with the raku query, it's almost impossible to find them using "rakulang" as part of the query.

## Suggestions

Use all available means to make search engines return this official documentation for rakulang queries too.

**Comment by lizmat** [comment]
Not sure what this is about?

**Comment by JJ** [comment]
Basically, modify templates and maybe content so that search engines are able to find the documentation pages using "rakulang", as in "rakulang maps", for instance. Right now, there are no results from these pages (or almost anywhere else) if you use rakulang to search for anything related to the Raku language.

**Comment by lizmat** [comment]
ah, ok.  do we do something wrt to TIOBE on the doc site, like mentioning "Raku Programming Language" on every page ?

**Comment by JJ** [comment]
Right now, for instance, [searching for rakulang concurrency](https://www.google.com/search?client=ubuntu&channel=fs&q=rakulang+concurrency&ie=utf-8&oe=utf-8) does not return a single result within these official documentation pages (and [using raku concurrency](https://www.google.com/search?safe=off&client=ubuntu&hs=oP&channel=fs&sxsrf=ACYBGNT9JY5ZNpcHKDkQ_xI1TQ5UPt2QfA%3A1575455049606&ei=SYnnXYLWJI-YjLsPttmdiAw&q=raku+concurrency&oq=raku+concurrency&gs_l=psy-ab.3..0i203.2280.2280..2518...0.0..0.140.354.1j2......0....1..gws-wiz.......35i39.b_2Kdodu16o&ved=0ahUKEwjCnt2045vmAhUPDGMBHbZsB8EQ4dUDCAo&uact=5) still returns the old pages, but that's another question)

**Comment by JJ** [comment]
> ah, ok. do we do something wrt to TIOBE on the doc site, like mentioning "Raku Programming Language" on every page ?

We should probably do that too, because search results for Raku are not too high either, as shown above.

**Comment by coke** [comment]
https://github.com/Raku/doc-website/discussions/76
