### ISSUE TITLE
Make reference show actual implementation of methods... or not

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3125]
## The problem

This has been discussed over and over again: should the reference section show actual implementations of methods and multi-methods, or just the general idea of them? 

For instance, check out this last issue #3124 , which needs to keep up with the new definitions of Cool.contains. [Prior definition](https://docs.raku.org/routine/contains#(Cool)_method_contains) gives the gist of it: it looks for stuff, which needs to be stringified maybe, and returns  a truish of false-ish value. Is it really necessary to show that `$pos` can be a `Cool` or an `Int`?

## Suggestions

Current consensus (or at least kinda-enforced policy) is that yes, it should be. By putting the exact same definition, you can't possibly go wrong. Except you might, if it changes for performance reasons. However, deriving a consensus single definition from there is tricky, and it would need actual tests to see if it behaves in the same way.

The alternative is to get definitions from the roast repo, which reflect actual usage. That might be even more tricky, though, since some cases might not be totally reflected. It might be a way to go, though, that would not change so much with implementation. Any more suggestions?

**Comment by coke** [comment]
Roast doesn't define what the actual method signatures should be, only what calls are expected of them. Unless roast changes how it specs the methods, I think the only reasonable thing we can do is to use the xt/check-signatures.t test (which postdates this ticket) to verify we are matching, at least, rakudo.

I would rather match rakudo than try to guess what the ideal version based on the roast usages are.
