### ISSUE TITLE
Broken link in docs.raku.org/routine/printf

### ISSUE THREAD

**Issue by arnesom** [Raku/doc#3127]
## The problem
The document  "https://docs.raku.org/routine/printf" has a link "Str.sprintf"
pointing to "https://docs.raku.org/type/Str#routine_sprintf". That page exist,
but the anchor (and a description of "sprintf") isn't there.

The same applies to "https://docs.raku.org/routine/sprintf", which I think
should be the target for the link. 

## Suggestions

See above.

**Comment by JJ** [comment]
Good catch. We'll try to fix it as soon as we can.
