### ISSUE TITLE
Hash antipairs/invert cross links broken.

### ISSUE THREAD

**Issue by bbkr** [Raku/doc#3130]
https://docs.perl6.org/type/Hash#(Map)_method_antipairs in "Unlike the invert method" links to https://docs.perl6.org/type/Map#method_invert but this method should be linked to https://docs.perl6.org/type/Hash#(Map)_method_invert because Hash itself does not have such method.

And the same mistake was done the other way

https://docs.perl6.org/type/Hash#(Map)_method_invert in "between invert and antipairs is that" should link antipairs to https://docs.perl6.org/type/Hash#(Map)_method_antipairs instead of nonexistent https://docs.perl6.org/type/Hash#method_antipairs .

**Comment by JJ** [comment]
Thanks! We'll check it out.
