### ISSUE TITLE
Clarify that AT-POS is not really intended for final users

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3146]
## The problem

In [the examples here](https://docs.raku.org/language/nativecall#index-entry-CArray_methods), AT-POS is used directly instead of substituting it by [], which is what it does.

## Suggestions

Revise the example and clarify a bit the whole section if needed.

**Comment by lizmat** [comment]
FWIW, just as we're documenting the MOP, the existence and use of these interface routines need to be documented as well.  Are they?

**Comment by JJ** [comment]
I'm afraid they're, in general, not. That means that there's no single
place where to find them all, and there's not an individual reference for
them. AT-POS is here, for instance https://docs.raku.org/routine/AT-POS, in
the classes where it's defined, but there's no place that says what it
does, in general, and where to use it, I think.
