### ISSUE TITLE
silence of IterationEnd failures

### ISSUE THREAD

**Issue by p6rt** [Raku/doc#3147]
Migrated from [rt.perl.org#126163](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126163) (status was 'open')

Searchable as RT126163$

**Comment by JJ** [comment]
I'll try to summarize it here. Since `IterationEnd` marks the end of a loop, anything that contains it will silently end the loop when it bumps into it.

    .say for ["foo",IterationEnd, "baz"] # foo

It does not happen in `map`, however.
