### ISSUE TITLE
The words language_documentation_Independent_routines are meaningless

### ISSUE THREAD

**Issue by p6steve** [Raku/doc#3159]
## The problem
The words language_documentation_Independent_routines are meaningless.
viz.
https://docs.raku.org/routine/say#language_documentation_Independent_routines

Maybe some substitution has run amok?

**Comment by JJ** [comment]
It's simply that the independent routines documentations is kind of jury-rigged to look like the documentation of a class.

**Comment by coke** [comment]
This rendering is fixed in the new site generated by raku/doc-website, going live by the end of February
