### ISSUE TITLE
"auths" unclear.

### ISSUE THREAD

**Issue by coke** [Raku/doc#3164]
doc/Language/compilation.pod6 has the text

```
It doesn't support versions or auths and simply maps the short-name to a filesystem path.
```

which I noticed because it fails the spellcheck.

However it also isn't clear - authorizations? Please replace with a more specific word choice (and make sure the spelling test passes)

**Comment by b2gills** [comment]
`auth` is intentionally non-specific.

It can be for **author**, **authority**, **authentication**.

```
# author
module Foo:auth<person> {}

# authority
module Foo:auth<BuyNLow> {}

# authentication
module Foo:auth<person@CPAN> {}
# (This assumes that the installer made sure that it was downloaded from CPAN.)
```

*`auth`s* is just the plural of `auth`.
Which makes sense as *versions* in that sentence refers to `ver`, and could arguably be *`ver`s*.

**Comment by coke** [comment]
Since this section is using auth to refer specifically to the module declaration, then I would recommend updating it to be C<auth>s to make that reference clear, and then adding "auths" to the word list.
