### ISSUE TITLE
`p6doc -l` erroneously defaults to $(pwd)/doc

### ISSUE THREAD

**Issue by stuart-little** [Raku/doc#3166]
## The problem

I have Raku [installed from source](https://rakudo.org/files/star/source) on a Linux machine, with `install/bin` and `install/share/perl6/site/bin` symlinked into my `$PATH`. 

By happenstance, I have a folder called `doc` in my `$HOME`. If I run `p6doc -l` from there, the result is 

```
Failed to get the directory contents of '<home>/doc/Type': Failed to open dir: No such file or directory
``` 
On the other hand, running that same command from *any* directory that does not contain a `doc` subdirectory works as expected. So for instance all is well if I temporarily move `$HOME/doc` out of the way.  

Also, note that only running with the `-l` flag fails in this manner. `p6doc variables`, for instance, or `p6doc -f <whatever>` works regardless of whether or not a stray `doc` subdirectory is present. 

## Suggestions

This strikes me as somewhat pathological: `doc` is a generic enough name to generate many such clashes. I would suggest `p6doc -l` default to its standard location (which in this case seems to be `install/share/perl6/site/doc`, or some such thing).

**Comment by JJ** [comment]
Thanks a lot for the report. We'll get to it as soon as we possibly can.

**Comment by stuart-little** [comment]
Thanks!

I'm am entirely new to Raku (I just downloaded it to get started) but my guess is the issue is in this sub from `rakudo/modules/doc/bin/p6doc`:

```
sub search-paths() returns Seq {                         
(('.', |$*REPO.repo-chain())>>.Str X~ </doc/>).grep: *.IO.d
}
```
That `'.'` at the beginning of the search-path list looks like the root cause.

**Comment by stuart-little** [comment]
I can confirm the above: in `rakudo/modules/doc/bin/p6doc`, changing the definition

```
sub search-paths() returns Seq {                         
(('.', |$*REPO.repo-chain())>>.Str X~ </doc/>).grep: *.IO.d
}
```
to
```
sub search-paths() returns Seq {                         
(($*REPO.repo-chain())>>.Str X~ </doc/>).grep: *.IO.d
}
```
seems to resolve the matter (tested seconds ago).

**Comment by coke** [comment]
p6doc is no longer a part of this repository; it is now called rakudoc and is part of http://github.com/raku/rakudoc
