### ISSUE TITLE
NativeCall and manually creating C strings

### ISSUE THREAD

**Issue by taboege** [Raku/doc#3169]
## The problem
The [NativeCall](https://docs.raku.org/language/nativecall#Passing_and_returning_values) documentation contains an example of how to manually turn a Raku string into a C string to pass it to a native function in case the lifetime of that C string must be prolonged until after the native call returns (so `Str is encoded` is not an option):

``` perl6
my $string = "FOO";
# The lifetime of this variable must be equal to the required lifetime of 
# the data passed to the C function. 
my $array = CArray[uint8].new($string.encode.list);
 
set_foo($array);
# ... 
use_foo();
# It's fine if $array goes out of scope starting from here.
```

Now, C libraries *customarily but not always* assume that a pointer ("to a string"[¹](https://www.nntp.perl.org/group/perl.perl6.users/2020/01/msg7824.html)) is terminated by a NUL character, which is not added by the above Raku code. (Even if it usually just appears after the CArray[uint8] by chance.[²](https://www.nntp.perl.org/group/perl.perl6.users/2020/01/msg7844.html))

## Suggestions

The example should be amended so that either:

- it is made clear that the function being called accepts a string that is not NUL-terminated, which is usually done by passing a pointer and a size, or
- the construction of the CArray[uint8] must include the NUL terminator, for example by using `CArray[uint8].new($string.encode.list, 0)`.

Best may be to show both and leave a small comment about the meaning of each variant, in informal terms, trusting the C experience of the reader.

## History

- <https://www.nntp.perl.org/group/perl.perl6.users/2019/12/msg7586.html>
- <https://www.nntp.perl.org/group/perl.perl6.users/2020/01/msg7822.html>

**Comment by ab5tract** [comment]
Thanks for this!! It helped me get past some issues that were seriously draining my will to continue coding.
