### ISSUE TITLE
RFE: add some links to Operators

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/doc#3175]
Dear Raku,

On your doc page, it is stated:

`https://docs.raku.org/language/functions#Defining_operators`
     Operators are just subroutines with funny names.  The funny names are composed of the category name (infix,  prefix, postfix, circumfix, postcircumfix), followed by a colon, and a list of the operator name or names (two components in the case of circumfix and postcircumfix).

Problem, although the above is very clear, what is not is assuming everyone knows what those terms mean.  And those that do know, DO NOT need to read this page.  In other words, start small, define terms, go on to the complicated stuff.   You missed the middle step.

Marcel helped me with this on the Raku mailing list.  Would you please consider adding the following right after the above paragraph (quoting Marcel here):

       prefix:  +foo
       'pre' means something like 'before'. What is before then. 
       It is about operators. So an operator goes before an
       argument. '+foo' here could then be +$a.  Other prefix 

       examples are ?$a, !$a, -$a, .

    postfix:  foo++
       'post' means something like 'after'. The operator goes after 
       the argument. 

       Examples are $a++, $b--.
 
    infix:  foo + bar
       This means that the operator is in between arguments. 

       Like [example] $a + $b, $a ** 2.

    circumfix: [foo]
       Means the operator goes around the argument. 

       Like a list ( $a, $b, 3, 4 )

    postcircumfix: foo[bar]
       The operator here is placed around an argument which is placed
       after another.

       Like @a[$b], (^10)[3], %h{$k} 

Then go on to the complicated stuff.

Thank you for your considerations.

**Comment by JJ** [comment]
You could also try and open a pull request, so that we can comment on specific lines, request changes, and so on. In this case, I don't really think we should go down to that level of detail. Also, this is already specified [here](https://docs.raku.org/language/operators#index-entry-postcircumfix_operator) in  table at the beginning of the page.  I'm sorry, but I'm closing here.

**Comment by ToddAndMargo** [comment]
On 2020-01-19 22:22, Juan Julián Merelo Guervós wrote:
> You could also try and open a pull request, so that we can comment on 
> specific lines, request changes, and so on. In this case, I don't really 
> think we should go down to that level of detail. Also, this is already 
> specified here 
> <https://docs.raku.org/language/operators#index-entry-postcircumfix_operator> 
> in table at the beginning of the page. I'm sorry, but I'm closing here.
> 

Hi Juan,

Would you please reconsider.  Let me make my case.

I am a beginner.  I program with the docs open in several
tabs as I write.  These terms mean nothing to me.

What I would like to see is an explanation that start out,
defines the terms, and then goes on to the complicated.
So the "level of detail" you refer to is for the beginner
and should be there as we are goging to be the primary users
of the docs.  Advanced users would only occasionally need
to view them.

https://docs.raku.org/language/operators#index-entry-postcircumfix_operator

Also makes this mistake and jump ahead of itself.  The
table is okay for advanced users but blasts clear over
my head.

If do not want to constantly repeating yourself, please
consider placing a link to the definitions wherever you
call out operators.  The section I asked for the enhancement
does not link to the section with the table.

Thank you for your consideration,
-T
