### ISSUE TITLE
xt/examples-compilation.t - can't see error

### ISSUE THREAD

**Issue by coke** [Raku/doc#3188]
Previous versions of xt/examples-compilation.t allowed a way to capture the error output from an attempted EVAL/parse. The current version using nqp discards all the error output.

This makes it difficult when trying to figure out why a particular set of sample code isn't passing.

If someone can provide the sample code for how to capture it the output, we can put something together that, only in the case of error, gets the output and does something with it.

**Comment by coke** [comment]
In this particular case, it was failing because nqp::getcomp was failing to find a compiler after the change from perl6 -> Raku

**Comment by JJ** [comment]
Previous version was almost 2x as slow. We'll try to see what we can do with current version. Maybe it's not as slow now.
