### ISSUE TITLE
Change from p6doc to rakudoc

### ISSUE THREAD

**Issue by coke** [Raku/doc#3203]
Our installed doc tool should probably be called rakudoc and no longer p6doc.

**Comment by coke** [comment]
I believe this can be closed, as I understand the current plan it's to use the tool in raku/rakudoc.

**Comment by JJ** [comment]
Got it. Will close it when it's totally eliminated from here (and created a
new release)

**Comment by coke** [comment]
It's been removed, and is now called rakudoc at http://github.com/raku/rakudoc
