### ISSUE TITLE
Explanation for %?RESOURCES needs to be improved.

### ISSUE THREAD

**Issue by coke** [Raku/doc#3205]
languages/modules says
```
through the %?RESOURCES Hash
```
per @niner , it's a Distribution::Resources object

Besides, it does not mention how (as indicated in @ugexe article below) `libraries` is handled in its own way, and what kind of objects are returned, and in which circumstances it's supposed to work (prior to installing a Distribution, for instance).

**Comment by coke** [comment]
We also need docs for Distribution::Resources object.

**Comment by coke** [comment]
%?RESOURCES has to be invoked from a module to work.

**Comment by JJ** [comment]
> We also need docs for Distribution::Resources object.

Please create a new issue for this.

**Comment by CurtTilmes** [comment]
Found this issue trying to figure things out.  I'll put here what I've found out so far.

This blog entry: [2016 Day 16: The Meta spec, Distribution, and CompUnit::Repository explained-ish](https://perl6advent.wordpress.com/2016/12/16/day-16-the-meta-spec-distribution-and-compunitrepository-explained-ish/) gives a little bit of into

`%?RESOURCES` is the `Distribution::Resources` for the current `Distribution`.  It returns a `Distribution::Resource` when you look up a key.

I'm especially interested in this magic which needs to be documented:

>If the first path part of the content-id is “libraries/” then any path under it will have its name mangled to whatever naming convention rakudo thinks is right for the OS it is running on. This can be useful for distributions that compile/generate libs at build time and expect to be named a certain way; libraries/mylib.dll on windows, libraries/libmylib.so on linux, and libraries/libmylib.1.so on OSX. This allows you to reference this library in a (probably NativeCall) module as %?RESOURCES<mylib> instead of guessing if its %?RESOURCES<mylib.dll> or %?RESOURCES<libmylib.so>

It seems that unlike the examples you actually must preface the library name with 'libraries' even in the call to `%?RESOURCES` 
```
my $lib = %?RESOURCES<libraries/mylib>`
```

When you do that, it mangles the 'mylib' part to 'libmylib.so' and so forth, looking for it in `resources/libraries`.

From [Distribution.pm6](https://github.com/rakudo/rakudo/blob/master/src/core.c/Distribution.pm6), I can see a bit of the library name mangling logic (falling back to `$*VM.platform-library-name` which is also not documented, but perhaps should not be as a VM internal matter?)

In any event, `Distribution::Resource` finds the resource somehow (in a way you shouldn't depend on), then can turn it into a `IO::Path` with `.IO`.  It delegates a bunch of methods (`Str gist raku absolute is-absolute relative is-relative parts volume dirname basename extension open resolve slurp lines comb split words copy` to that ).  So you can call any of those on a `Distribution::Resource`.

**Comment by niner** [comment]
The only part of this that's not a supported API is `.IO` on the 
`Distribution::Resource`. I would have liked to omit the path handling methods 
as well but it was too late at a time. People were already expecting resources 
to give file system paths.

`$*VM.platform-library-name` is a public API.

**Comment by 2colours** [comment]
Re: (non-)accessibility of %?RESOURCES:

I think we are trying to describe the same phenomenon using different words - I for one don't even know what the exact term would be.

Yesterday I noticed that a script bundled in a module's bin directory still won't access `%?RESOURCES`. Probably only "actual modules", i.e rakumod files under lib, will be able to access it. @ugexe please confirm or correct me.

At the moment, we have the following remark:

> %?RESOURCES is a compile-time variable available to the code of a Distribution.

(confer https://github.com/Raku/doc/blob/master/doc/Language/variables.pod6 for more details)

The `Distribution` role has a pretty shallow description: https://github.com/Raku/doc/blob/master/doc/Type/Distribution.pod6

I'm not sure which should be extended with the correct and precise description of what files can access it; possibly both.

**Comment by coke** [comment]
Niner had opened a related ticket, which I addressed, closing this one I opened.
