### ISSUE TITLE
Invalid example in doc/Type/Cool.pod6

### ISSUE THREAD

**Issue by coke** [Raku/doc#3213]
6cbd36f3c40c566726124e285bbf6e7ca248f9b4 added this example:

```
+    say log2(5);            # OUTPUT: «2.321928094887362␤»
+    say "4"log2;            # OUTPUT: «4␤»
```

Looks like it was meant to be "4".log2, but given the output presented, It's not entirely clear. Can the original author please fix the example?

**Comment by coke** [comment]
You can verify the test passes with:

```
xt/examples-compilation.t doc/Type/Cool.pod6
```

**Comment by lizmat** [comment]
Fixed with https://github.com/Raku/doc/commit/3b8f9fe964
