### ISSUE TITLE
Mentions of Perl 6 in the docs were edited out a little TOO thoroughly

### ISSUE THREAD

**Issue by tobyink** [Raku/doc#3216]
https://github.com/Raku/doc/blob/master/doc/Language/faq.pod6#L10

> **What's the difference between Raku, Rakudo and Perl 6?**
>
> Properly speaking, Rakudo is an implementation of Raku. It's currently the one that's being developed, but there have been other implementations in the past and there will likely be others in the future. Raku is the definition of the language. When talking about the current interpreter, Rakudo and Raku can be used interchangeably.

That answers what the difference is between "Raku" and "Rakudo", but the answer doesn't mention "Perl 6" at all.

**Comment by JJ** [comment]
Right, we should mention it. Thanks!
