### ISSUE TITLE
Small section about the handles trait

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#3255]
I've written [this small section](https://gist.github.com/uzluisf/7f575c702373565a18b6d74565b2db40) somewhat explaining delegation and how it's achieved in Raku. The [`handle` trait](https://docs.raku.org/language/typesystem#index-entry-handles_trait-handles) is already documented, however the examples given there only show the syntax/semantics without providing any [motivation for its use](https://colabti.org/irclogger/irclogger_log/raku?date=2019-11-08#l345). If deemed worthy of the documentation, this could be added to the [Objects](https://docs.raku.org/language/objects) page given the long examples with substantial narrative on there already.

**Comment by JJ** [comment]
Of course it is. Please do that.
