### ISSUE TITLE
Buf.list() and Blob.list() return type

### ISSUE THREAD

**Issue by stoned** [Raku/doc#3266]
The documentation for Buf.list() and Blob.list() says that these methods return a List (previously a Seq) of codepoints. But it seems to me that a List of integers would be more correct. What do you think of this ?

**Comment by lizmat** [comment]
Indeed.  They could be codepoints semantically, but they're just integers realistically.

**Comment by JJ** [comment]
Just mention the type; maybe you can additionally say "that can be treated as codepoints"
