### ISSUE TITLE
p6y to rakuy 

### ISSUE THREAD

**Issue by coke** [Raku/doc#3287]
https://github.com/Raku/doc/commit/04055410c6ce60f6aedc54bc22da80337dfaa8c5  breaks the aspell test.

(Change of "p6y" to "rakuy")

* there's probably a way to write this that avoids using a neologism: maybe "idiomatic", "native", "Raku-like", "natural" - no need to match the original neologism's formatting.
* Whatever we pick needs to pass the spelling test (either by picking existing words or updating the words files)
* This leaves "p6y" dangling in the glossary. We should remove it if we're not referencing it anywhere else in the docs.

**Comment by tbrowder** [comment]
Fair enough!

**Comment by tbrowder** [comment]
How do you like in the instance above "it is considered better practice to try and...?"

**Comment by coke** [comment]
c86f4dd1c9aa40eafb0748a9c3404a1ccbdca025

**Comment by JJ** [comment]
The thing is, maybe we should give the whole thing a bit of thought. With the motto "There is more than one way to do it" written in block letters all over Raku, there's no better or worse thing, just different ways of doing it. It's true that some constructions help the optimizer a bit more, but in that case, we should be precise in how it's better. There're no "code smells" or PEPs we should respect, so in that sens a whole re-writing of these sentences is, IMHO, the best option.

**Comment by coke** [comment]
There are idiomatic practices, however, and it's fine to call those out.

**Comment by coke** [comment]
@tbrowder if you're looking for feedback, I have a slight preference to "idiomatic".

**Comment by AlexDaniel** [comment]
I've heard “Rakuish” multiple times, but I agree that rewording the sentence is almost always a better choice.

**Comment by coke** [comment]
No more references to p6y in the docs.
