### ISSUE TITLE
broken link on https://en.wikipedia.org/wiki/Raku_rules#Implicit_changes

### ISSUE THREAD

**Issue by kanliot** [Raku/doc#3303]
apologies if this is the wrong place to report the wiki, if you give me the correct link I'll try and fix the wiki myself. 

from https://en.wikipedia.org/wiki/Raku_rules#Implicit_changes
>[Raku rules - Wikipedia](https://en.wikipedia.org/wiki/Raku_rules#Implicit_changes)
References
Wall, Larry (June 24, 2002). ["Synopsis 5: Regexes and Rules"](http://dev.perl.org/perl6/doc/design/syn/S05.html).

http://dev.perl.org/perl6/doc/design/syn/S05.html redirects to http://feather.perl6.nl/syn/S05.html which no longer resolves thru dns.

**Comment by JJ** [comment]
Thanks for the report. It's as good as any, I guess.

**Comment by JJ** [comment]
Fixed, thanks!
