### ISSUE TITLE
Array indices can only have 63 bits

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3307]
## The problem

As pointed out by [@lizmat here](https://stackoverflow.com/questions/61031107/do-array-indices-need-to-be-native-ints/61031617#61031617)

## Suggestions

Please mention it in the [subscripts](https://docs.raku.org/language/subscripts#Basics)

**Comment by lizmat** [comment]
Perhaps mention [Array::Sparse](https://modules.raku.org/dist/Array::Sparse) and/or that one can use hashes with integer keys?
