### ISSUE TITLE
Change .perl to .raku in examples

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3309]
## The problem

As part of the #3046 , .raku has superseded .perl. The latter still works perfectly (although it will be deprecated in the next vesion), but it would probably be better to stop using it in examples.

## Suggestions

List below examples that use it and start changing it.
* [x] [Shell environment variables used by Raku](https://docs.raku.org/programs/03-environment-variables)
* [x] [class Set](https://docs.raku.org/type/Set)
* [x] [class List](https://docs.raku.org/type/List)
* [x] [class Code](https://docs.raku.org/type/Code)
* [x] [role Iterable](https://docs.raku.org/type/Iterable)
* [x] [class Metamodel::ClassHOW](https://docs.raku.org/type/Metamodel/ClassHOW)
* [x] [role Metamodel::MethodContainer](https://docs.raku.org/type/Metamodel/MethodContainer)
* [x] [role Metamodel::MultipleInheritance](https://docs.raku.org/type/Metamodel/MultipleInheritance)
* [x] [class Method](https://docs.raku.org/type/Method)
* [x] [class Routine](https://docs.raku.org/type/Routine)
* [x] [class Range](https://docs.raku.org/type/Range)
* [x] [class Signature](https://docs.raku.org/type/Signature)
* [x] [class Any](https://docs.raku.org/type/Any)
* [x] [class Scalar](https://docs.raku.org/type/Scalar)
* [x] [class Attribute](https://docs.raku.org/type/Attribute)
* [x] [class Complex](https://docs.raku.org/type/Complex)
* [x] [class Junction](https://docs.raku.org/type/Junction)
* [x] [class Date](https://docs.raku.org/type/Date)
* [x] [class Int](https://docs.raku.org/type/Int)
* [x] [class Mu](https://docs.raku.org/type/Mu)
* [x] [class Rat](https://docs.raku.org/type/Rat)
* [x] [class Slip](https://docs.raku.org/type/Slip)
* [x] [class Str](https://docs.raku.org/type/Str)
* [x] [role Buf](https://docs.raku.org/type/Buf)
* [x] [class Proc](https://docs.raku.org/type/Proc)
* [x] [class Backtrace](https://docs.raku.org/type/Backtrace)
* [x] [class Array](https://docs.raku.org/type/Array)
* [ ] [role Numeric](https://docs.raku.org/type/Numeric)
* [x] [class IO::Spec::Unix](https://docs.raku.org/type/IO/Spec/Unix)
* [x] [class IO::Spec::Win32](https://docs.raku.org/type/IO/Spec/Win32)
* [x] [class IO::CatHandle](https://docs.raku.org/type/IO/CatHandle)
* [x] [class IO::Path](https://docs.raku.org/type/IO/Path)
* [x] [class IO::Path::Cygwin](https://docs.raku.org/type/IO/Path/Cygwin)
* [x] [class IO::Path::Unix](https://docs.raku.org/type/IO/Path/Unix)
* [x] [class IO::Path::Win32](https://docs.raku.org/type/IO/Path/Win32)
* [x] [class IO::Path::QNX](https://docs.raku.org/type/IO/Path/QNX)
* [x] [class IO::Handle](https://docs.raku.org/type/IO/Handle)
* [x] [class Pair](https://docs.raku.org/type/Pair)
* [x] [class FatRat](https://docs.raku.org/type/FatRat)
* [x] [class Seq](https://docs.raku.org/type/Seq)
* [x] [class BagHash](https://docs.raku.org/type/BagHash)
* [x] [class Nil](https://docs.raku.org/type/Nil)
* [x] [class Bag](https://docs.raku.org/type/Bag)
* [x] [role Rational](https://docs.raku.org/type/Rational)
* [x] [class CallFrame](https://docs.raku.org/type/CallFrame)
* [x] [class SetHash](https://docs.raku.org/type/SetHash)
* [x] [class Cool](https://docs.raku.org/type/Cool)
* [x] [module Test](https://docs.raku.org/type/Test)
* [x] [role Iterator](https://docs.raku.org/type/Iterator)
* [x] [Lists, sequences, and arrays](https://docs.raku.org/language/list)
* [x] [Functions](https://docs.raku.org/language/functions)
* [x] [Community](https://docs.raku.org/language/community)
* [x] [Modules](https://docs.raku.org/language/modules)
* [x] [Type system](https://docs.raku.org/language/typesystem)
* [x] [Pod6](https://docs.raku.org/language/pod)
* [x] [Experimental features](https://docs.raku.org/language/experimental)
* [x] [Control flow](https://docs.raku.org/language/control)
* [x] [Syntax](https://docs.raku.org/language/syntax)
* [x] [Glossary](https://docs.raku.org/language/glossary)
* [x] [Raku native types](https://docs.raku.org/language/nativetypes)
* [x] [Perl to Raku guide - functions](https://docs.raku.org/language/5to6-perlfunc)
* [x] [Subscripts](https://docs.raku.org/language/subscripts)
* [x] [FAQ](https://docs.raku.org/language/faq)
* [x] [Iterating](https://docs.raku.org/language/iterating)
* [x] [Ruby to Raku - nutshell](https://docs.raku.org/language/rb-nutshell)
* [x] [Hashes and maps](https://docs.raku.org/language/hashmap)
* [x] [Perl to Raku guide - in a nutshell](https://docs.raku.org/language/5to6-nutshell)
* [x] [Containers](https://docs.raku.org/language/containers)
* [x] [Classes and objects](https://docs.raku.org/language/classtut)
* [x] [Input/Output the definitive guide](https://docs.raku.org/language/io-guide)
* [x] [Numerics](https://docs.raku.org/language/numerics)
* [x] [Grammar tutorial](https://docs.raku.org/language/grammar_tutorial)
* [x] [Regexes](https://docs.raku.org/language/regexes)

**Comment by stoned** [comment]
FYI there is no occurrence of `perl` method in [Shell environment variables used by Raku](https://docs.raku.org/programs/03-environment-variables)

**Comment by Prince213** [comment]
Marking 'Experimental features' as complete since there's nothing to do.

**Comment by coke** [comment]
If you have a unix-y shell, this should work to find any remaining failing pod6 files:

```
TEST_FILES=$(grep -lr '\.perl' doc) prove -e raku xt/examples-compilation.t
```

**Comment by coke** [comment]
What we don't have a test for is that we have a 'method raku' section of a document (at least for those that have a perl method)

**Comment by coke** [comment]
> I think there is no occurrence of `perl` method in [Shell environment variables used by Raku](https://docs.raku.org/programs/03-environment-variables)

Probably hit the ".perl6", safe to ignore.

**Comment by stoned** [comment]
False positive for [class Int](https://docs.raku.org/type/Int).

**Comment by stoned** [comment]
In [class Mu](https://docs.raku.org/type/Mu) the description of the `raku` method applied to type objects mentions the `perl` method. I was considering changing `perl` to `raku` in this description but it accuretly corresponds to rakudo's current implementation of the `raku` method. So I kept these occurences of the method name `perl` while submitting #3385. Should it be otherwise?

**Comment by JJ** [comment]
@stoned I'm seeing this after commenting the same in the PR...
