### ISSUE TITLE
Change name of 5to6-* files

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3310]
## The problem

Shouldn't it be changed now to "perl2raku"? 

## Suggestions

We will probably need to find incoming links to them too, even external ones, but we can always solve that with a redirect.

**Comment by coke** [comment]
Duplicate of #3090

**Comment by JJ** [comment]
Er, not really. That one is for discussing, this one for actually doing

**Comment by coke** [comment]
In my opinion, we don't need two tickets for the same item; if the discussion is over, we can close that ticket or use it to house the actual todo item. If we haven't decided yet, we don't need a ticket for an undecided item.

**Comment by Altai-man** [comment]
Agree on the two tickets redundancy.

About those migration pages: they are very old, maybe among the oldest documents written, and need a from scratch rewrite. Indexing there is bad and has to be changed as well.
