### ISSUE TITLE
Native arrays are indexed three times

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3319]
## The problem

There are two `array`s, one of them pointing [here](https://docs.raku.org/language/101-basics#index-entry-array), and one `native array`. The first and last point to the same place, or close.

## Suggestions

One problem here is the confusion of the name, `array` with the generic name for them. All of them should be changed to `native arrays` probably. But there are outstanding issues like #2257. In the meantime, probably a single indexing term would be the best.

**Comment by coke** [comment]
indexing & searching has been overhauled, I can't see this issue when searching on @finanalyst 's site (whose latest updates will be in prod shortly).
