### ISSUE TITLE
"." and ".." are indexed, but leads to wrong pages

### ISSUE THREAD

**Issue by matiaslina** [Raku/doc#3336]
## The problem

Searching for `.` in the "infix" section leads to the `index` routine: https://docs.raku.org/routine/
Searching for `..` in the "infix" section leads to https://docs.raku.org/

## Suggestions

* For `.` go to [https://docs.raku.org/language/operators#methodop_.](https://docs.raku.org/language/operators#methodop_.)
* For `..` go to [https://docs.raku.org/language/operators#infix_..](https://docs.raku.org/language/operators#infix_..)

**Comment by JJ** [comment]
There's a problem with indexing that kind of things, I'm afraid...

**Comment by coke** [comment]
This performs much better in the site generated for raku/doc-website, which should be live by end of February; Thanks for the report.
