### ISSUE TITLE
When should an iterable be an Iterable?

### ISSUE THREAD

**Issue by Kaiepi** [Raku/doc#3338]
## The problem
The docs for `Iterable` state this:

> `Iterable` serves as an API for objects that can be iterated with `for` and related iteration constructs, like assignment to a `Positional` variable.

> `Iterable` objects nested in other `Iterable` objects (but not within scalar containers) flatten in certain contexts, for example when passed to a slurpy parameter (*@a), or on explicit calls to flat.

I don't think this is very clear. `Any` declares a proto for the `iterable` method, which allows any class to become iterable if desired. `Iterable` defines an API of some sort for iterable values, but it isn't the API that specifically makes them iterable.

## Suggestions
The behaviour of `Iterable` WRT scalars and slurpies indicates to me that this should be described as an API for iterables that should behave more like lists in general. Maybe de-emphasize the first half of and emphasize the second half of that first paragraph somehow.

**Comment by JJ** [comment]
Sorry, you lost me here. Why does the statement about Any.iterable contradict the two quoted paragraphs? What does the affirmation about nested Iterablas has to do with it? What first half and second half are you referring to?

**Comment by Kaiepi** [comment]
Ah... my bad, I was thinking the `iterator` method of an object always determined the behaviour of `for` loops, but it's a little more involved than that, so none of this makes any sense. It was `list` that I was thinking of that can affect how loops behave with non-`Iterable` objects in certain cases, but that seems to be an implementation detail of Rakudo.
