### ISSUE TITLE
xt/aspell.t explosion.

### ISSUE THREAD

**Issue by coke** [Raku/doc#3339]
Recent changes to doc/Type/Str.pod6 are causing xt/aspell.t to fail:

```
$ xt/aspell.t doc/Type/Str.pod6
1..1
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
Unhandled exception in code scheduled on thread 4
Malformed UTF-8 near bytes 74 ea 74

# You planned 1 test, but ran 0
```

The file itself seems fine to raku:

```
$ raku -e '"doc/Type/Str.pod6".IO.slurp.chars.say'
49813
```
Need some research to find the root cause.

**Comment by JJ** [comment]
My money is on tête à tête

**Comment by coke** [comment]
bisect shows this commit is when the failure begins:

1fbe42f257caf1855982e73143f1bb08c43b0843

**Comment by JJ** [comment]
There's [this bug somewhere](https://github.com/hunspell/hunspell/issues/362)

**Comment by JJ** [comment]
Could it be on the words.pws file?

**Comment by coke** [comment]
Removing the entry from xt/code.pws avoids the explosion.

**Comment by coke** [comment]
Fixed by cheating to avoid the ispell issue.

**Comment by stoned** [comment]
Sorry for the trouble. FYI I did not encounter the problem, even if I was using the same aspell version.
```
$ xt/aspell.t doc/Type/Str.pod6 
1..1
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
ok 1 - doc/Type/Str.pod6 has no spelling errors
$ grep t.te- xt/*.pws
xt/aspell.pws:tête-à-tête
xt/code.pws:tête-à-tête
$
```
