### ISSUE TITLE
Header/definition discrepancy

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3350]
## The problem

Every method and routine get a header, and then a definition. In some cases, these differ: one is defined as method, the other as routine.  For instance, [`mkdir`](https://docs.raku.org/type/IO::Path#sub_mkdir)

## Suggestions

Try to find automatically these cases, and fix them. In cases where there are methods & subs, use `routine` instead.

**Comment by coke** [comment]
There is a test now to enforce this.
