### ISSUE TITLE
xt/examples-compilation.t doc/Type/IO/Handle.pod6 failure

### ISSUE THREAD

**Issue by coke** [Raku/doc#3351]
## The problem

```
xt/examples-compilation.t doc/Type/IO/Handle.pod6
```

Fails with

```
    # method open(IO::Handle:D:
    #       :$r, :$w, :$x, :$a, :$update,
    #       :$rw, :$rx, :$ra,
    #       :$mode is copy,
    #       :$create is copy,
    #       :$append is copy,
    #       :$truncate is copy,
    #       :$exclusive is copy,
    #       :$bin,
    #       :$enc is copy,
    #       :$chomp = $!chomp,
    #       :$nl-in is copy = $!nl-in,
    #       Str:D :$nl-out is copy = $!nl-out,
    #       :$out-buffer is copy,
    #     )
    #
    # Attribute $!chomp not declared in class <anon|67>
```

## Suggestions

This looks like we need to add a new ```:preamble``` style parameter into the testing script that allows us to add attributes to the anonymous class we use to test the method declaration.  The method is correctly marked with ```:method```.

Test is currently skipped with a tag referring to this issue.

**Comment by coke** [comment]
If someone can make it work with just a preamble, go for it. My thought is that we need an attribute in the class itself since we're referring to, e.g. $!chomp. Pre/Post probably won't work because, after adding post support, we're already doing special handling because it's a :method, so faking it with wrapping another class seems problematic. My suggested syntax:

```
=for code :method :attributes<chomp nl-in nl-out>
```

Which would add lines to the generated code inside the class defined here:

https://github.com/Raku/doc/blob/master/xt/examples-compilation.t#L66

**Comment by coke** [comment]
... Which means we can probably do it as a special preamble. Was thinking preamble was outside the class, not inside. give me a moment.

**Comment by coke** [comment]
Yup, that worked. no need for a new attribute.

**Comment by JJ** [comment]
Great job. Thanks!
