### ISSUE TITLE
Juice up documentation for the "perl 6" and "perl6" search terms

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3377]
## Problem or new feature

The docs.perl6.org and doc.perl6.org are about to be permanently redirected to docs.raku.org. This means that some pages that do not include perl6 in the domain name or in the content are going to be returned as people click on them, or that they will no longer be indexed under that term and not returned when Google notices that they're a simple redirect.

## Suggestions

Try to find out what are the best practices in this case, and change the template and/or the content so that it's not so bad.

**Comment by coke** [comment]
Moving issue to https://github.com/Raku/doc-website/discussions/76
