### ISSUE TITLE
some use of .pm6 suffix

### ISSUE THREAD

**Issue by p6steve** [Raku/doc#3379]
## Problem or new feature

this page https://docs.raku.org/language/modules has some use of .pm6

## Suggestions

s/pm6/rakumod/g

**Comment by JJ** [comment]
For the time being, I don't think we're changing extensions. We might in the future, though; for the time being it's not a priority.

**Comment by JJ** [comment]
Please don't close it. It's just lower priority, and we still need to address it in that page.

**Comment by p6steve** [comment]
sure

**Comment by JJ** [comment]
Thanks!

**Comment by coke** [comment]
@JJ mentioned in a commit comment:

> But .pm6 still works, and is not deprecated. Changing a few is OK, but making it disappear from the site, I'm not sure...

It's not disappeared from the site - for specific examples, this updates them to use the preferred, new file extension type. The list of allowable extensions includes both, and I didn't remove it from there.

This is similar to the discussion around .perl vs. .raku - if there are multiple ways to do something and one of them is recommended, then for consistent documentation, we should pick one and use it in examples. (related, we still document .perl & .raku methods, but in examples, we should be using only .raku)

```.pm6``` still listed in doc/Language/intro.pod6 and there is a ```N<>``` tag in doc/Language/modules.pod6 which could probably be moved to visible text.

**Comment by Altai-man** [comment]
:+1: for using Raku "native" extensions. About a year passed since renaming discussion.
