### ISSUE TITLE
xt/examples-compilation.t

### ISSUE THREAD

**Issue by coke** [Raku/doc#3391]
Looks like this test file starts failing tests when run against the entire repo. Error message on every test (once it starts failing) is something like

```
    # Cannot find method 'new_type' on object of type <anon|4186>::Metamodel::DefiniteHOW
```

**Comment by JJ** [comment]
Could it be a bug?

**Comment by JJ** [comment]
Again, could it be a bug?

**Comment by coke** [comment]
Yes. I opened this ticket because I thought it was.

**Comment by coke** [comment]
The issue was in ```doc/Type/Metamodel/DefiniteHOW.pod6``` which had a class definition for ```Metamodel::DefiniteHOW``` - after this test, tests in other files began failing. skipping this test, and we're back to a single failure when running against the entire suite.
