### ISSUE TITLE
method printf is misplaced

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3392]
## Problem or new feature

[`method printf`](https://docs.raku.org/language/independent-routines#routine_printf) ended up in the independent routines page, from wherever it was in the first place, probably Cool.

Still to go:
* [ ] `method note`
* [ ] `method unpolar`

## Suggestions

Add it to where it belongs: [Cool](https://github.com/rakudo/rakudo/search?q=%22method+printf%22&unscoped_q=%22method+printf%22)

**Comment by softmoth** [comment]
See also PR #3420 to help find it with `p6doc -f printf`; due to that bug it wasn't showing up!

**Comment by JJ** [comment]
Ditto for sprintf

**Comment by coke** [comment]
misplaced methods like this should also be caught by the xt/ test.

**Comment by coke** [comment]
The original is long gone, the other two are in a list that includes the sub variant as well. Closing ticket.
