### ISSUE TITLE
False positives in routine-definitions.t

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3395]
## Problem or new feature

Running routine-definitions over the code, it seems to give some false positives.

For instance:

```
# Failed test 'doc/Type/independent-routines.pod6 section «routine squish» but code block starting with «sub          squish(» lacks both sub and method definition'
```

I would say that it's because of the many spaces involved, but this is only this case.

## Suggestions

Check all positives and eliminate false ones.

**Comment by JJ** [comment]
The thing is that this is a false positive, but just because "routine" can be both. It need not _include_ both.

**Comment by stoned** [comment]
Sorry I did not quite understood you in #3350.

When you said
> In cases where there are methods & subs, use routine instead

I  understood that if a section is both about a sub and a method it must have "routine" in its heading and reciprocally if a section has "routine" in its heading it must be about both a sub and a method.

With 1bd6b05 you relaxed the conditions for a section to have "routine" in its heading: it could be about a sub, about a method, or about both.

But, as an example, https://github.com/Raku/doc/blob/master/doc/Type/Array.pod6#L347-L351 does not seem quite right to me, `=head2 method dynamic` seems more appropriate to me.

Am I wrong ? :-)

**Comment by JJ** [comment]
@stoned well, it's technically correct, since it's a routine. In that case I would rather try and find out why it ended up with a routine instead of a method. It's possible that originally there were some subs around; there might still be. So you can still change it for method if that's how it's defined in the source, but routine is not really incorrect.

**Comment by stoned** [comment]
@JJ OK, understood. Thanks!
