### ISSUE TITLE
Directory name changes

### ISSUE THREAD

**Issue by Prince213** [Raku/doc#3396]
## Problem or new feature

In the current directory structure, we have `share/perl6`.

## Suggestions

Since we are adapting to Raku, I propose changing its name to `raku`.

**Comment by Prince213** [comment]
Related issue: https://github.com/rakudo/star/issues/155

**Comment by Altai-man** [comment]
Are you sure this is a doc issue and not rakudo issue?

**Comment by Prince213** [comment]
You're right, it's a Rakudo issue.
