### ISSUE TITLE
Proc.Bool is not documented

### ISSUE THREAD

**Issue by gfldex** [Raku/doc#3397]
Proc overloads method Bool to return False on `exitcode != 0 && signal != 0` but is omitted in https://docs.raku.org/type/Proc .

```
run <ls /does-not-exist>
and shell <ls /does-not-exist>
and qx{ls /does-not-exist>}
or die 'cant list what is not there';
```

I did not check if the same applies to Async::Proc.

This is was specced in https://github.com/Raku/roast/blame/aa4994a7f6b3f6b450a9d231bebd5fba172439b0/S29-os/system.t#L29 .

**Comment by JJ** [comment]
Thanks for the report. We'll try to check it out ASAP.
