### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ayoubhm** [Raku/doc#3400]
## Problem

On page 
https://docs.perl6.org/routine/shell 
there is the following broken link 
https://docs.perl6.org/type/independent-routines#sub_shell 
that leads to the following page 
404: Page Not Found
that requests I report the broken link over here.

**Comment by JJ** [comment]
Those pages are deprecated... [The equivalent page in raku.org ](https://docs.raku.org/routine/shell) does have a correct link. Can you please check?

**Comment by ayoubhm** [comment]
The equivalent [page](https://docs.raku.org/routine/shell) in raku.org works. Thanks and sorry to trouble you.

**Comment by JJ** [comment]
No problem, my pleasure. I'll close this issue if you don't mind them. Please keep them coming!
