### ISSUE TITLE
CHM version of docs

### ISSUE THREAD

**Issue by Prince213** [Raku/doc#3413]
## New feature
PHP and Python provide CHM for browsing on Windows. This is more convenient than browsing HTMLs and can also avoid the name issues on Windows(`*`, `<`, `>` etc. can't be used as filenames).

## Suggestions
Build CHMs. However this probably requires a Windows host.

**Comment by Prince213** [comment]
Since EPUBs don't have the name issues, this only a suggestion and is *not* urgent or necessary.

**Comment by antoniogamiz** [comment]
What's CHM?

**Comment by JJ** [comment]
An old hypertext format used in Windows applications.

**Comment by coke** [comment]
rejecting this in favor of epub: https://github.com/Raku/doc/discussions/4142
