### ISSUE TITLE
Take advantage of new Raku --doc=auth-fmt capability

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3414]
Rakudo PR #3708 has added an option argument capability to '--doc=' that causes the parsed Pod from leading declarator blocks to retain author formatting rather than combining all such text into a normalized single-line string.

That capability may be very useful for this program.

**UPDATE**

There is an active discussion on IRC channel #raku about the best choice of identifier for the action. Users are encouraged to look at comments on the PR and vote for their choice of names.

**Comment by JJ** [comment]
An example?

**Comment by tbrowder** [comment]
#| Purpose:
    #|   + collect info
    #|   + average results
    #|
    #| Example:
    #|    2, 3, 4 
    #|         average: 3
    sub foo() {}

Text as extracted now (one normalized line):

Text as extracted with the new argument:

**Comment by JJ** [comment]
OK, I see. Thanks!

**Comment by coke** [comment]
What's the specific use case for this feature? Generating the HTML site isn't going to use this, and examples-compilation doesn't care about the formatting.

**Comment by coke** [comment]
Closing ticket - feel free to re-open if there's an actionable item.
