### ISSUE TITLE
Create section for each of the types in the "Raku Types" page.

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#3442]
## Problem or new feature

The [Raku Types](https://docs.raku.org/type.html) page lists all the types in a single long table and as of now, you've to search the whole thing to look for a type of a given "type" (`class`, `role`, or`enum`).

## Suggestions

Create a section within the same page for each of the types (`class`, `role`, and `enum`). The aim is to make it easier to jump straight to any section and then look on there for the given type. Something like this might do the job:

### Classes

| Name | Type | Description|
|:--|:--|:--|
|Any | class | Thing/object|
|Array | class | Sequence of itemized values|
|AST | class | Abstract representation of a piece of source code|

### Enums

| Name | Type | Description|
|:--|:--|:--|
|Bool | enum | Logical boolean|
|Endian | enum | Indicate endianness (6.d, 2018.12 and later)|
|Order | enum | Human readable form for comparison operators.|

### Roles

| Name | Type | Description|
|:--|:--|:--|
|Associative | role | Object that supports looking up values by key|
|Blob | role | Immutable buffer for binary data ('Binary Large OBject')|
|Buf | role | Mutable buffer for binary data|

**Comment by JJ** [comment]
We would still have to search for a given type. Plus the type column would be redundant. Are we really earning something with this?

**Comment by uzluisf** [comment]
My aim wasn't to do away with the search but that if I'm looking for a "type" of type `class`, I can jump straight to that section and do the search there. I copied the information directly from the page and didn't bother removing the columns 😅. As for earning anything, I don't think we're necessarily are aside from making it more visually pleasing.

**Comment by JJ** [comment]
The problem is that this is generated by Documentable, using the same pattern as others. So it's not as easy to do. We can raise it there as a wishlist, however...

**Comment by coke** [comment]
@finanalyst has something like this in the new https://docs.raku.org/types page - not quite the same table format, but it is grouped by type. Thanks.
