### ISSUE TITLE
Perform more checks automatically and do automatic deployment if possible too.

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3451]
## Problem or new feature

Automatic deployment has been already requested #3428 , but additionally, there are some lengthy checks, mainly test-compile examples and spell checks, which are not automated right now.

## Suggestions

Use GitHub actions or Azure DevOps pipelines to do both.

**Comment by coke** [comment]
There are two items in this ticket; one is already listed as a duplicate, the second is a duplicate of #3036.

Closing ticket.
