### ISSUE TITLE
"Page Not Found" with newly added sections

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#3464]
## Problem or new feature

Several newly added sections gets you a "Page Not Found" or they haven't been rendered at all. For instance, the search term `last-date-in-month` gets you a "Page Not Found" ([Pod](https://github.com/Raku/doc/blob/master/doc/Type/Date.pod6#L70-L87)) while `:api<>` doesn't take you to the relevant because it isn't there ([Pod](https://github.com/Raku/doc/blob/master/doc/Language/typesystem.pod6#L935-L958)).

## Suggestions

Check why these sections aren't being rendered.

**Comment by JJ** [comment]
Pages are not automatically generated, as indicated in #3428. I'll upload the new version in a while.
