### ISSUE TITLE
Pod::Cache isn't safe for concurrent access

### ISSUE THREAD

**Issue by coke** [Raku/doc#3466]
when using ```util/update-and-test``` (which generates a script called ```retest```), we are running all the test files against a small subset of the tests. If that test uses lib/Pod/Cache and it's determined that the file needs to be updated in the cache, multiple instances of the test can possibly run at the same time. This can cause the file to be mangled, causing tests like xt/aspell to fail because they are not looking at the full source.

(Try to clean the pod cache before a run of ```make xtest``` with a small number of TEST_FILES but a TEST_JOBS of 3 or so helps to highlight the issue)

Noticed because a recent run of the tools was complaining about a typo in doc/Language/typesystem.pod6 that just did not exist in the original file, nor in ```raku --doc``` output. Clearing the cache and rerunning? same error. Clearing the cache and using TEST_JOBS=1 when rerunning? avoids the error.

**Comment by coke** [comment]
@JJ   - does https://github.com/JJ/raku-cache-pod/blob/master/lib/Pod::To::Cache.pm6 avoid the concurrency problems? If so, let's kill our use of lib/Pod/Cache and switch over.

**Comment by JJ** [comment]
No, it does not, I'm afraid. It's a good idea to try and switch it anyway.
I started Cache::Pod to overcome both problems
https://github.com/JJ/raku-cache-pod but it's not there yet. Adding
concurrency to the spec.
Baseline is, concurrency is not something you can latch on later, you need
to bake it in.

**Comment by coke** [comment]
This doesn't help:

```
$ git diff
diff --git a/lib/Pod/Cache.pm6 b/lib/Pod/Cache.pm6
index 732cb6bd4..0bc79ba5f 100644
--- a/lib/Pod/Cache.pm6
+++ b/lib/Pod/Cache.pm6
@@ -13,6 +13,8 @@ method cache-file(Str $file --> Str) {
     if $in-time > $out-time {
        mkdir $output-io.dirname;
        my $outfile = $output-io.open(:w);
+       $outfile.lock;
+
        LEAVE $outfile.close;
        $outfile.lock;
        my $job = Proc::Async.new($*EXECUTABLE-NAME, '--doc', $file);
```

**Comment by coke** [comment]
OH HEY there's already a .lock in there there wasn't doing anything.

**Comment by coke** [comment]
Tried to fix this a bit with:

ea98b81ac

**Comment by coke** [comment]
flock seems to be working, closing ticket.

**Comment by coke** [comment]
@niner points out that .lock *does* work in his example, so something else may be going on here. The fix here is probably also broken on Windows. So see if we can remove the flock fix and keep the working code.

**Comment by coke** [comment]
While I did seem to have a bad run of pod-cache in the last refactor of xt/aspell.t, it's been behaving for me for a bit now.

Closing ticket.
