### ISSUE TITLE
Mobile usability problems

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3470]
## Problem or new feature

For some reason, I've started to receive reports from Google. This one is in Spanish:

```
 Los elementos en los que se puede hacer clic están demasiado cerca unos de otros

El texto es demasiado pequeño para leerlo

El contenido es más ancho que la pantalla

La ventana gráfica no se ha definido
```

Clickable elements too close ot each other, text too small to read, content wider than screen, the graphic screen has not been defined. 

## Suggestions

It would be really helpful if someone revised the general usability of the site. It's not necessarily intended for a mobile phone, but people might need to use it in a pinch.

**Comment by Altai-man** [comment]
1)Can you please specify how do you get reports?
2)What do you think about https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-06-08#l87 ?

**Comment by JJ** [comment]
1) Really no idea. I suddenly started to receive them.
2) I'm on board, of course. A redesign is overdue. I have no problem of
using the same one all across the sites.

**Comment by Altai-man** [comment]
Sorry, by "how do you get reports" I meant where do they even came from.
For example, https://search.google.com/test/mobile-friendly?id=fjLv9UDsqzFsniT3uzFSbw I just tested says it is mobile friendly, no?

**Comment by JJ** [comment]
It's an email I just got.

**Comment by coke** [comment]
The reports on this site are no longer valid. If someone can sign us up for these alerts on the new version of the site, that'd be great (Maybe JJ will get them for free when we do the cutover later this month), but going forward, please report any usability issues on raku/doc-website
