### ISSUE TITLE
Boolean should be capitalized

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3517]
## Problem or new feature

Since its origin is a proper name, Boole, [it should be capitalized](https://english.stackexchange.com/questions/4481/should-the-word-boolean-be-capitalized).

## Suggestions

There are more `boolean` than `Boolean` in the documentation.

If applicable, suggest something towards the solution. For starters, eliminate it from the dictionary, and looking forward add it to a test.

**Comment by coke** [comment]
Additionally, when referring to the Raku type, it should probably be changed to a link to Bool, the enum.

**Comment by paultcochrane** [comment]
See #3542.  There were some instances in the docs where a "Boolean value" was mentioned; I don't think that this was the Boolean type, hence I made no linkes to the Bool enum.  The PR is submitted in the hope that it is useful, so please let me know if there is anything I could improve.

**Comment by uzluisf** [comment]
Should this issue be closed since it looks like it was addressed already?

**Comment by JJ** [comment]
@uzluisf maybe add a test also.

**Comment by coke** [comment]
Should be possible to add this requirement to xt/word-variants.t

**Comment by coke** [comment]
Merged @stoned's PR, ran the test, fixed the one item remaining.
