### ISSUE TITLE
Pod::Block::Code lacks the .allowed method descibed in its docs.

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3525]
The [documentation for `Pod::Block::Code` states](https://docs.raku.org/type/Pod::Block::Code#___top) that it has the `allowed` method.  However, it does not.  Indeed, the [source code for `Pod::Block::Code`](https://github.com/rakudo/rakudo/blob/master/src/core.c/Pod.pm6#L48-L49) does nothing more than inherit from `Pod::Block`.

Does anyone know if `Pod::Block::Code` is *supposed* to have an allowed method that hasn't yet been implemented?  If so, I can open a Rakudo bug to that effect.  Either way, however, it seems that the documentation should not indicate the presence of a non-existent method.  Depending on responses to this issue, I'm happy to submit a PR that either describes the `allowed` method as "not-yet-implemented" or removes reference to it entirely.

**Comment by JJ** [comment]
> The [documentation for `Pod::Block::Code` states](https://docs.raku.org/type/Pod::Block::Code#___top) that it has the `allowed` method. However, it does not. Indeed, the [source code for `Pod::Block::Code`](https://github.com/rakudo/rakudo/blob/master/src/core.c/Pod.pm6#L48-L49) does nothing more than inherit from `Pod::Block`.
> 

Right.

```
Pod::Block::Code.^methods
(BUILDALL contents gist config BUILD BUILDALL)
```

> Does anyone know if `Pod::Block::Code` is _supposed_ to have an allowed method that hasn't yet been implemented? If so, I can open a Rakudo bug to that effect. Either way, however, it seems that the documentation should not indicate the presence of a non-existent method. Depending on responses to this issue, I'm happy to submit a PR that either describes the `allowed` method as "not-yet-implemented" or removes reference to it entirely.

A NYI would have the method implemented, but would throw `X::NYI`. Anything you do would be fine.

**Comment by JJ** [comment]
Unsurprisingly, that part of the file is 8 years old:

https://github.com/Raku/doc/blame/master/doc/Type/Pod/Block/Code.pod6#L13-L19

If we had the time, we should routinely revise everything that's older than the Christmas release...
