### ISSUE TITLE
independent-routines not included in the `Language` section

### ISSUE THREAD

**Issue by ohmycloud** [Raku/doc#3526]
## new document named `independent-routines` can't navigate through the `Language` section

[https://docs.raku.org/language/independent-routines](https://docs.raku.org/language/independent-routines) seems not included in [https://docs.raku.org/language.html](https://docs.raku.org/language.html)

And, the following url in the bottom page of [https://docs.raku.org/language/independent-routines](https://docs.raku.org/language/independent-routines) seems broken:

Generated from [/language/independent-routines](https://github.com/Raku/doc/blob/master/doc/Language/independent-routines.pod6)

**Comment by JJ** [comment]
Thanks for the report; we'll try and see what can be done here.

**Comment by coke** [comment]
https://docs.raku.org/reference has the link to independent-routines, which now lives at

https://docs.raku.org/type/independent-routines
