### ISSUE TITLE
Improvements to util/list-missing-methods.p6 [tracking issue]

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3529]
I very much like the idea behind the `list-missing-methods.p6` program – Raku provides extremely rich introspection abilities, and we should be able to automatically detect any undocumented areas.  Additionally, the same program should be able to list methods we document that do *not* currently exist (something that occurred to me after working on #3528)

However, while attempting to add that functionality to `list-missing-methods.p6`, I realized that it currently has a few other issues (e.g., it was confusing `Pod::Block` with `Block`).  I'm currently working on a revision that both adds that functionality and addresses several minor issues; I'm opening this as a tracking issue for that work.

**Comment by JJ** [comment]
Thanks!

**Comment by coke** [comment]
missing methods relies on bin/p6doc which is going away (See #3483) - if still needed, will need to rely on https://github.com/raku/rakudoc

**Comment by codesections** [comment]
Unless I'm missing something, that's true of [`missing-methods.p6`](https://github.com/Raku/doc/blob/master/util/missing-methods.p6) but not [`list-missing-methods.p6`](https://github.com/Raku/doc/blob/master/util/list-missing-methods.p6), which is the script I'm working on revising.

(I'm not at all clear on why there are two so similarly named utilities or if one of them should be deleted in favor of the other.  I started with `list-missing-methods` because it's the one mentioned in [CONTRIBUTING](https://github.com/Raku/doc/blob/9ba24606b02ed7662450c5c60958f9fa17af3bc7/CONTRIBUTING.md#testing-method-completeness))

**Comment by coke** [comment]
My bad - if we can remove the other one, that's great.

**Comment by codesections** [comment]
Closed by #3571
