### ISSUE TITLE
 Recursive/self-referential regex match <~~> not documented 

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3533]
According to the spectest, "a leading ~~ indicates a recursive call back into some or all of the current rule."  [S05–metasyntax](https://github.com/Raku/roast/blob/master/S05-metasyntax/angle-brackets.t#L285).  This behavior is not currently described in the docs.

I'm happy to submit a PR – I assume it belongs in the [language/regexes](https://docs.raku.org/language/regexes) page?  However, I'd appreciate a careful review when I submit the PR; I didn't even know about the feature until a few minutes ago, so I might not be the best person to document it!

**Comment by JJ** [comment]
It probably does. But please check that it's really implemented.
