### ISSUE TITLE
Nativecall page should explain the usual practice for sub bodies

### ISSUE THREAD

**Issue by MasterDuke17** [Raku/doc#3540]
## Problem or new feature

Sometimes the examples use `sub some_argless_function() is native('something') { * }` and sometimes `sub some_argless_function() is native('something') {*}` (note the missing whitespace around the `*` in the second example). That could lead to confusion with the `{*}` token used to mark the dispatch point for protos. See https://github.com/salortiz/NativeLibs/issues/9 for an example.

## Suggestions

The examples should be made consistent and some explanation of what is correct for the sub body given.

**Comment by JJ** [comment]
Thanks a lot for the report. We'll revise docs and fix what's wrong.
