### ISSUE TITLE
Need example and words on constraint of an arg in a sub parameter to one of multiple types

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3548]
## Problem

I want to constrain a subroutine parameter to one of several types and could not find a clear example of how to do it in the docs. Thanks to @Altai-man on IRC \#raku who showed the solution as in this example:

    sub a($foo where Str|List) {...}

**Comment by coke** [comment]
Should be added in https://docs.raku.org/type/Signature#Type_constraints near the subset examples.

**Comment by tbrowder** [comment]
Ok.

**Comment by tbrowder** [comment]
Closed by commit e7ce74e.

**Comment by JJ** [comment]
Thanks!

**Comment by tbrowder** [comment]
On Wed, Aug 5, 2020 at 07:20 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Thanks!


My pleasure, it's always a pleasure to scratch a Raku itch!
