### ISSUE TITLE
substr doc

### ISSUE THREAD

**Issue by rakool** [Raku/doc#3550]
v6.c doesn't `substr $c, 0, 0, 'foo'`; as indicated in [https://docs.raku.org/language/5to6-perlfunc#index-entry-substr_-_perlfunc](url) while [https://docs.raku.org/routine/substr](url) indicates the former link is wrong.

And I seem to be entering the links wrongly.

**Comment by coke** [comment]
I was confused for a second because that form doesn't appear exactly in the docs - but I see it's referring to the form with replacement - updating the docs to refer to substr-rw for that case.
