### ISSUE TITLE
Adverbial :h to quoting constructs has no docs.

### ISSUE THREAD

**Issue by ziuq** [Raku/doc#3553]
Problem: 
See title.
See https://docs.raku.org/syntax/Q
I have searched the site without success.   I am unknowing how to escape `:h` for gugu's engine, but I did check 7 of the likeliest pages.

## Suggestions

Document the adverbials on the referenced page.

Addressing the problem from a different angle:  have a page for difficult to search punctuation contaminated constructs.  The  '*',  bare '::' (subset) , and ':' (method call) come to mind.

**Comment by JJ** [comment]
It's included in the table in the page you link. You can also type it in
the search slot, and it will take you here
https://docs.raku.org/language/quoting#index-entry-:h_(quoting_adverb)
Is that what you mean?

**Comment by ziuq** [comment]
@JJ:  Thanks for the correction.  Yes `:h` is documented as existing, but I presume it does something and want to find out what.

**Comment by JJ** [comment]
I'm sorry, but I don't quite follow what you mean. In the documentation, it says `Interpolate % vars`. 
What that exactly means, well, not really clear, either in that case or in the others. Maybe an example would help?

**Comment by jnthn** [comment]
Perhaps "Interpolate variables with the % sigil (only if followed by an indexer)" would be clearer.

**Comment by JJ** [comment]
jnthn you mean the `<>` thingie. You call that indexer?

**Comment by JJ** [comment]
@jnthn are you sure it's an indexer and not a decont? `@a<>` works too.

**Comment by jnthn** [comment]
Well, if we want to be accurate, we should say "a postcircumfix", but I suspect that might not tell the typical docs reader very much. :-)

**Comment by jnthn** [comment]
(I mean, `%h.elems()` is fine, because it ends in the `()` postcircumfix.)

**Comment by JJ** [comment]
OK, reopening to clarify that.

**Comment by ziuq** [comment]
Yes, hints are there in the docs.  Examples might be better.

I started with a reasonable thought of a grammar-based solution, but while searching the docs for
a wheel my weak mind slid downhill when finding `:h`.

Something like this off the cuff example:

`my %h = hashify qq(  
    :key(nothing to escape here, no parens , just a trailing ws ), 
    boltcutter => Here auto-trimming seems good and do escape arrows and commas ,
 );`

is even briefer with the quote-like builtin or the `hashify` built in to a quote-like.
So I was definitely muddling a couple of concepts under  interpolation at that point.
