### ISSUE TITLE
sub form of `round` is not documented fully

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#3555]
This works (note that it is used as a sub, not as a method):
```raku
say round 42.42, 0.1 # 42.4
```

However, it is never mentioned in the docs.
The signature for `sub` form is provided:
```
multi sub round(Numeric(Cool))
```
But it doesn't mention `$unit`.

**Comment by JJ** [comment]
Noted, thanks.

**Comment by jjatria** [comment]
I might be misreading something here, but this seems to also work when `round` is used as a method?

```
$ raku -e 'say π.round: 0.001'
3.142
```

**Comment by coke** [comment]
Docs should also give more info about units (and rename units to $scale, as it is in the source). the current behavior is to scale to the entire scale, not just the least sigfig, so:

```
19:59 < [Coke]> m: say round(1000, .01); say round(1000, 23.01)
19:59 < camelia> rakudo-moar 85847d2f1: OUTPUT: «1000␤989.43␤»
```
Waiting for a reply on #raku-dev to verify this is the intended behavior.
