### ISSUE TITLE
General comments found in the Raku survey

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3585]
They are here mainly for informative purposes, but in some cases they are actionable, so this issue can be referred when you refactor the documentation addressing them specifically.

Some comments on the docs:
- Many of them seem to be written for people coming from Perl and are light on the details for Perl-y concepts.
- There are explanations of _how_ language features work, but not _why_ they are designed that way and how they might be used. This is even more important for things that you find only in Perl and Raku. (E.g. sigils and containers. It took me at least a month to go from "What is this Rube Goldberg contraption doing in my language?" to "This is actually really useful if you use it intelligently.".)
- An article on how to work in the ecosystem, project structure, use of the tools, how to write documentation, ... would be very useful. (Reference: https://wiki.haskell.org/How_to_write_a_Haskell_program)

**Comment by coke** [comment]
Created a separate ticket for the last item, closing this ticket.
