### ISSUE TITLE
Document Hash key-type parameterization

### ISSUE THREAD

**Issue by fecundf** [Raku/doc#3592]
## Problem or new feature

Hash doesn't explicitly mention its key & value types.

The Hash docs point to the Map docs at the very beginning - "A Hash is a mutable Map; ..."

The Map class docs (eg https://docs.raku.org/type/Map ) states "A Map is an immutable mapping from string keys to values of arbitrary types" which is good and accurate, for Map.

A Hash never mentions that its key types & value types are parameterized.

Map doesn't mention that its key & value types are NOT parameterized.

## Suggestions

Add a note to Hash- "Hash associates from string keys to values of arbitrary types as a default. The key and value types can be declared." -or similar. And show an example of how

```
my %search-message := Hash[Str, Regex].new (
  rx:i:m/ <[aeiou]> ** 2 / => 'Found vowels together!',
  rx:i:m/ 'y' | 'w' / => 'Eww, maybe...'
);
# is same as
my Str %search-message{ Regex };
%search-message{ rx:i:m/ <[aeiou]> ** 2 / } = 'Found vowels together!';
%search-message{ rx:i:m/ 'y' | 'w' / } = 'Eww, maybe...';

```

As for Map not being parameterized, perhaps discuss that before documenting the limitation! see https://github.com/Raku/problem-solving/issues/223

**Comment by JJ** [comment]
Thanks a lot for the report. We'll get to it as soon as we possible can.
