### ISSUE TITLE
aspell shouldn't handle affixes, should it?

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3593]
## Problem

When commenting on #3587, @JJ  raised an interesting question: should "apostrophes be excluded from spell check"?  I looked into aspell's functionality a bit, and the docs indicate that aspell supports a feature called [affix compression](http://aspell.net/man-html/Affix-Compression.html), which _seems_ related to automatically handling apostrophes and other word-endings.  After reading a bit more about the feature, though, I think it's not a good fit for us – it looks like it's mostly about reducing the size-on-disk for the dictionary files and would at least slightly slow processing time.

However, I'm not at all familiar with aspell.  I've relied on it for years, but today may be the first time I've opened its man page.  @coke, I know you just spent some time with the aspell tests – do you (or anyone else) know whether my understanding of affix compression is correct?  And/or do you know if aspell has any other feature that would automatically exclude possessives or other variants of a word when we add the base word to our word list?

**Comment by JJ** [comment]
We can preprocess the word and eliminate apostrophes; after all, we don't
use aspell directly but through a script.

Also, this is an example of a functionality that should be spun off to a
general module for Pod spell checking.

**Comment by coke** [comment]
I don't see anything obvious in the aspell options for handling possessives.

As JJ suggests, we could get rid of any ```'s``` that appears as the end of a word. That'd leave 2 entries in ```code.pws``` (after first making sure that the possessive is actually warranted and it shouldn't be a plural).

**Comment by coke** [comment]
Gave a little more thought - I'd rather leave the ```'s``` explicitly in the lexicon because then we can verify the grammar when they are added. If we strip them, we then allow possessives on things that shouldn't be.

**Comment by codesections** [comment]
That makes sense to me.  Plus, stripping them out would mean adding them back via the script – which would slow things down at least a little.  It seems like it has too many costs for not enough gain.
