### ISSUE TITLE
Inconsistent xt/aspell results 

### ISSUE THREAD

**Issue by codesections** [Raku/doc#3597]
45b66a1 causes 62 new test failures when I run `make xtest` on Pop_OS (basically Ubuntu 20.04). The following words cause failures for me: runtime, enque, enqueues, deque, unary, incrementing, decrementing, falses.

After talking with @coke, it seems like this has to do with different words in system dictionaries, or some other aspell oddity.

**Comment by codesections** [comment]
I looked into this a bit more: after updating to the [most recent availibe aspell dictionary](https://ftp.gnu.org/gnu/aspell/dict/0index.html#official), aspell6-en-2019.10.06-0, I get only 1 test failure (rather than 62).  The failure I still get is caused by "Falses" in Junction.pod6.

However, to do that I had to update the aspell dictionary outside of my package manager.  Using the latest dictionary from the Ubuntu archives did not solve the problem.

Given all that, maybe we should add a note contributors about all this?

**Comment by coke** [comment]
Yes, please add your setup instructions somewhere and I’ll add my Mac instructions.

**Comment by JJ** [comment]
Yes, please.

**Comment by coke** [comment]
```
To run this test, you'll need to install aspell and the english dictionary package.

On Mac OS X, you can install aspell using macports (https://macports.org/).

$ sudo port install aspell
$ sudo port install aspell-dict-en
```
