### ISSUE TITLE
Document introspection in Routine class

### ISSUE THREAD

**Issue by fecundf** [Raku/doc#3600]
## Doc for class Routine, link to `&?ROUTINE`

I was trying to remember how to get the currently-running routine pointer. A site search on Introspection highlighted this from language/functions
> Introspection on subroutines is provided via [Routine](https://docs.raku.org/type/Routine).

with a link to type/Routine - but that page does not mention Introspection anywhere.

## Suggestions

Mention, in the Routine class documentation, that a routine can get to itself via &?ROUTINE variable. That can be a simple one-line link, no need to repeat the details.

**Comment by JJ** [comment]
Yes, it makes sense. Thanks for the suggestion.
