### ISSUE TITLE
xt/check-signatures.t doesn't respect TEST_FILES 

### ISSUE THREAD

**Issue by coke** [Raku/doc#3611]
Instead of manually checking for doc/Type files, should use the results of Test-Files.documents and grep through those, similar to xt/aspell.t

**Comment by coke** [comment]
(doing this would allow the test to work with util/update-and-test which relies on using the TEST_FILES environment variable.)

**Comment by codesections** [comment]
Good point.  I didn't realize util/update-and-test used TEST_FILES.

I initially didn't use TEST_FILES because it will frequently include doc/Language/* files that xt/check-signatures can't do anything with.  But you're 100% correct that a simple grep would solve that.

**Comment by coke** [comment]
Had to move the code to get the files to the top of the test (in place, it was getting a list of the files in the rakudo source dir.)
