### ISSUE TITLE
1-file HTML does not yet exist

### ISSUE THREAD

**Issue by Prince213** [Raku/doc#3632]
## Problem

Though https://github.com/Raku/doc/pull/3599 is merged, https://docs.raku.org/raku.html does not yet exist.

## Suggestions

Regenerate documentation.

**Comment by JJ** [comment]
We do have the means to generate it now again... We'll try to comply. Thanks for the report.

**Comment by coke** [comment]
note that https://docs.raku.org/perl6.html currently exists. This will eventually be replaced with an ebook build target. (which should include PDF)

**Comment by coke** [comment]
Tracking the creation of the epub version here:

https://github.com/Raku/doc-website/issues/75
