### ISSUE TITLE
OO code example in rb-nutshell doesn't work

### ISSUE THREAD

**Issue by raiph** [Raku/doc#3706]
## Problem or new feature

```
class Person {
    has $.name = 'Jill';
    has $.age  = 42;
    has $!birth_year;
    method BUILD {
        $!birth_year = now.Date.year - $.age;
    }
}
my $p = Person.new( name => 'Jack', age => 23 )
```

is bogus code in several ways, generating warnings, failing to initialize the object, etc.

## Suggestions

Maybe replace with:
```
class Person {
    has $.name = 'Jill';
    has $.age  = 42;
    has $!birth_year = now.Date.year - $!age;
}
my $p = Person.new( name => 'Jack', age => 23 );
```
This compiles and runs without warnings and correctly initializes the object.

I can't vouch for whether it's exactly the same as the Ruby but it's definitely much better than the code that is currently in the doc.

**Comment by JJ** [comment]
Good catch. Thanks!

**Comment by MorayJ** [comment]
"In Raku you get a default constructor that accepts key/value pairs of accessor attributes, and can do further setup in the BUILD method." - For this example, I think we may just need to change BUILD to TWEAK in the code and this line.

**Comment by lizmat** [comment]
Yeah.  A lot of examples in this area predate the existence of the `TWEAK` method.

**Comment by MorayJ** [comment]
Example now changed to TWEAK
