### ISSUE TITLE
Slip documentation give example result that doesn't mesh with current rakudo result

### ISSUE THREAD

**Issue by michael-776** [Raku/doc#3709]
## Problem

https://docs.raku.org/type/Slip near the top says:

my $l = (1, 2, 3);
...
say (0, slip $l).raku;    # says (0, $(1, 2, 3)), $l does not break apart 

But the current rakudo (Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.11.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.11)
gives this result:
(0, 1, 2, 3)

**Comment by JJ** [comment]
That's correct. We'll need to fix that. Thanks!
