### ISSUE TITLE
docs.raku.org "everything in one file" link returns 404

### ISSUE THREAD

**Issue by sorpigal** [Raku/doc#3720]
1. open https://docs.raku.org/
2. click "everything in one file"

Result: 404 https://docs.raku.org/raku.html

Expected result: 200 and the docs in one file.

I tried https://docs.raku.org/perl6.html just in case the old name was being used and it exists but is not up to date.

**Comment by sorpigal** [comment]
Nevermind, I now see that https://github.com/Raku/doc/issues/3632 essentially reports this.

**Comment by JJ** [comment]
We need to fix it anyway. Thanks for reporting it.
