### ISSUE TITLE
Looks like documented trap "Using regexes within grammar's actions" has been fixed

### ISSUE THREAD

**Issue by raiph** [Raku/doc#3721]
## Problem

[Using regexes within grammar's actions](https://docs.raku.org/language/traps#Using_regexes_within_grammar's_actions) doesn't fail in the Rakudo's I tried (2018.12 and 2020.07).

## Suggestions

Remove it.

**Comment by JJ** [comment]
We'll have a look. Thanks!

**Comment by Altai-man** [comment]
I may be mistaken now, but it seems the error is still here. It is just that the example demonstrated is not enough to trigger the error?

```
grammar will-fail { token TOP {^ <word> $}; token word { \w+ } }; class will-fail-actions { method TOP ($/) { my $foo = ~$/; say $foo ~~ /foo/;  } }
```
surely does not give an error, BUT if you add:
```
will-fail.parse('word', :actions(will-fail-actions))
```
it throws `Cannot assign to a readonly`, just as the trap description promises.

I will now extend the example to include full code...
