### ISSUE TITLE
Searching for '*' does not show 'Whatever' in the results

### ISSUE THREAD

**Issue by patrickbkr** [Raku/doc#3728]
When searching for '*' the [Whatever](https://docs.raku.org/type/Whatever) page is not shown in the results. Also the [syntax *](https://docs.raku.org/syntax/*) page does not show the [Whatever](https://docs.raku.org/type/Whatever) documentation. This makes it hard to find out what the star means when one sees it the first time as a Whatever *.

**Comment by JJ** [comment]
It's very likely that there are some troubles with indexing that kind of thing. I'll check anyway, thanks for the report.
