### ISSUE TITLE
cannot install through zef due to missing GTK::Simple dependency

### ISSUE THREAD

**Issue by stuart-little** [Raku/doc#3750]
## Problem or new feature

As of today, 2020-12-23, `zef` cannot find `GTK::Simple`, which is a required dependency for `p6doc`:

```
$ zef install p6doc
===> Searching for: p6doc
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
u0_a141@localhost:~$ zef install p6doc               ===> Searching for: p6doc
===> Searching for missing dependencies: Pod::To::BigPage:ver<0.5.1+>, Pod::To::HTML:ver<0.6.1+>, Test::META, Perl6::TypeGraph
===> Searching for missing dependencies: META6, URI, License::SPDX, Template::Mustache, LibCurl, Pod::Load, GTK::Simple, Test::Output, Test::Deeply::Relaxed, HTTP::UserAgent, Test::When
===> Failed to find dependencies: GTK::Simple
Failed to resolve some missing dependencies
```

And trying to install `GTK::Simple` directly:

```
$ zef install GTK::Simple
===> Searching for: GTK::Simple
No candidates found matching identity: GTK::Simple
```

Additionally, the `GTK::Simple` [page](https://github.com/finanalyst/GTK-Simple) linked from the [central module hub](https://modules.raku.org/search/?q=gtk%3A%3Asimple) 404-errors out.

## Suggestions

I do not have the expertise to offer any, but perhaps investigate the status of `GTK::Simple` and consider alternatives?

**Comment by lizmat** [comment]
The GTK::Simple repo is in process of being transferred to a new maintainer.  Sadly, this appears to take longer than expected due to some administrative shenanigans.  It should be available again with a new maintainer shortly.

**Comment by JJ** [comment]
It shouldn't be a dependency, anyhow. Thanks for the report, let me check
this out.

**Comment by stuart-little** [comment]
Thanks! It now installs on all of my `x86_64` machines, but not on `Android`. That's a [different matter](https://github.com/ugexe/zef/issues/380) though (stemming from the `LibCurl` dependency).

**Comment by JJ** [comment]
I think this is possibly due to Documentable picking up an incorrect version of Pod::To::HTML. However, you don't need Documentable at all to install this, it's rather the other way round. I think for the time being I'm going to eliminate that dependency and see if that fixes this.
