### ISSUE TITLE
<<<>>> on Syntax page isn't rendered

### ISSUE THREAD

**Issue by pxeger** [Raku/doc#3763]
## Problem or new feature

https://github.com/Raku/doc/blob/7f8b1f6fc595c4e89f2d2a9f0a38f09011de4e99/doc/Language/syntax.pod6#L1011

`C<<< >>>` is [not rendered in the page](https://docs.raku.org/language/syntax), probably because of the `<>` characters. I don't know how to fix it myself I'm afraid

## Suggestions

Fix this.

**Comment by JJ** [comment]
Sure will. Thanks for noticing it and pointing it out to us.
