### ISSUE TITLE
Bugs in NativeCall example

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/doc#3764]
https://docs.raku.org/language/nativecall#Structs

on the bottom example of Structs, there are all kinds of syntax errors:

#!/usr/bin/env raku

use NativeCall;

class MyStruct is repr('CStruct') {
    has CArray[num64] $!arr;
    has Str $!str;
    has Point $!point; # Point is a user-defined class 

    submethod TWEAK {
        my $arr := CArray[num64].new;
        $arr[0] = 0.9e0;
        $arr[1] = 0.2e0;
        $!arr := $arr;
        $!str := 'Raku is fun';
        $!point := Point.new;
    }
}

$ raku -c NativeCallExampleTest.pl6
===SORRY!===
Type 'Point' is not declared
at /home/linuxutil/NativeCallExampleTest.pl6:8
------>     has Point⏏ $!point; # Point is a user-defined clas
Malformed has
at /home/linuxutil/NativeCallExampleTest.pl6:8
------>     has⏏ Point $!point; # Point is a user-define

I do believe you will find `has Str $!str;` is a booboo too.

**Comment by JJ** [comment]
It's not really intended to be used all by itself. You need to compile it in a file or in a way that makes the previous example, which declares `Point`, available; and it says clearly so in the comment. In general, not all example can be compiled unless they show an `OUTPUT`, which it does not in this case.
A clarification might be a good thing, however.

**Comment by Altai-man** [comment]
Just extending the `# Point is a user-defined class ` into `# Point is a user-defined class shown above` is enough to clarify.
