### ISSUE TITLE
lastcall is most probably in the wrong place

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3767]
## Problem or new feature

[`lastcall`](https://docs.raku.org/type/Method#sub_lastcall) is documented in Method. It's not clear why it's there, since it's neither exclusive to methods nor uses it as invocant or argument.

## Suggestions

Move it to independent routines, which is where it belongs.

**Comment by stoned** [comment]
I guess this can be closed now. right ?

**Comment by JJ** [comment]
Right. You can close it either from the commit or the PR. We quite prefer that, indeed.
