### ISSUE TITLE
02-reading-docs mentions rakudoc, which isn't published

### ISSUE THREAD

**Issue by dakkar** [Raku/doc#3769]
## Problem or new feature

https://docs.raku.org/programs/02-reading-docs tells people to use `rakudoc`, but that distribution is not published (yet).

## Suggestions

One of:
* publish https://github.com/Raku/rakudoc to the ecosystem
* add a prominent NYI note on 02-reading-docs
* suggest a different (but working today) way to read docs of installed modules

**Comment by coke** [comment]
rakudoc is currently installable.
