### ISSUE TITLE
Graph for X::Syntax::InfixInTermPosition and others are missing

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3773]
## Problem or new feature

Although it is in the type-graph.txt file, [that graph is missing](https://docs.raku.org/type/X::Syntax::InfixInTermPosition)
Also https://rakudocs.github.io/type/X::Proc::Async::BindOrUse

## Suggestions

Find out if it has not been generated because it's recent, or is a genuine problem.

**Comment by raydiak** [comment]
All `IO::` classes/roles are also affected by this, except for the `IO` role itself

**Comment by JJ** [comment]
Thanks! We'll try and find out what happens...

**Comment by raydiak** [comment]
FWIW, I did try to build it myself to further investigate, but ran into several issues with the dependencies. Among other things, npm threw warnings about 3 deprecated/unsupported/renamed packages, the very specific and old mojolicious version required didn't build for me (though the current version does), and highlights/node_modules/oniguruma threw a python syntax error on its configure step (perhaps meant for an older python?). I didn't have time to get deeper into it today, but will post a separate issue for these things if I can't get them working after taking a closer look.

**Comment by JJ** [comment]
You need to use version 12 of node, I think. It does not work with the
current version.
