### ISSUE TITLE
We need to speed up tests or otherwise reduce dependence on Travis

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3777]
## Problem

Our tests in travis are taking up more than 30% of all Travis credits for the Raku organization

![Captura de pantalla de 2021-01-10 10-38-29](https://user-images.githubusercontent.com/500/104119955-926d3480-5333-11eb-877b-c7bc0f2fa602.png)

And this has led to exhaustion of credits in less than two months.

## Suggestions

Every build takes 7 minutes, and sometimes it's only testing a new or a bunch of new files, something that should take less than a few seconds. There are many things that could be done

* Try and make only changed files undergo testing. This is kinda difficult, since I'm not so sure if Travis keeps the last commit that was tested. In the case it did, it wouldn't be too difficult to modify tests so that they did.
* Split tests in different platforms. We already use different platforms, albeit for different things. We are not using GitHub actions, though.
* Move everything or a part to GitLab, which also hosts CI workflows.

**Comment by stoned** [comment]
I'll try to setup GitHub actions equivalent to at least the default Travis build

**Comment by coke** [comment]
If we can track previous checkout information, util/update-and-test already has the code to test only those items that have changed since the last commit.

**Comment by stoned** [comment]
A first github workflow was run with sucess, see https://github.com/Raku/doc/actions/runs/476131939

**Comment by JJ** [comment]
Thinking twice, I think I'm going to reopen this. We would still need to speed up tests. Github is not, or will not be, unlimited either.

**Comment by coke** [comment]
Is the issue speeding up the tests or speeding up the build?

**Comment by coke** [comment]
raku/rakudoc travis tests have been disabled by travis due to negative credit balance.

**Comment by coke** [comment]
Setting up new CI covered in #4195
