### ISSUE TITLE
Failing signature test for Seq

### ISSUE THREAD

**Issue by coke** [Raku/doc#3779]
## Seq.pod6

```
$ RAKUDO_SRC=../rakudo xt/check-signatures.t doc/Type/Seq.pod6
1..1
    1..7
    not ok 1 - Seq.new invocant matches source
    # Failed test 'Seq.new invocant matches source'
    # at xt/check-signatures.t line 118
    # documented method: (Iterator:D $iter --> Seq:D)
    #     source method: (Seq: |)
    ok 2 - Seq.iterator invocant matches source
    ok 3 - Seq.is-lazy invocant matches source
    ok 4 - Seq.elems invocant matches source
    ok 5 - # SKIP cannot determine source for multi method Seq.from-loop
    ok 6 - Seq.sink invocant matches source
    ok 7 - # SKIP cannot determine source for multi method Seq.skip
    # You failed 1 test of 7
not ok 1 - check Seq methods
# Failed test 'check Seq methods'
# at xt/check-signatures.t line 80
# You failed 1 test of 1
```

**Comment by JJ** [comment]
Well, it's a multi:

https://github.com/rakudo/rakudo/blob/9e13ace808b422c465eaf902c5436f6e1d2b26fc/src/core.c/Seq.pm6#L10-L20

**Comment by JJ** [comment]
I get this error when running the same:

```
MVMArray: shift expected string register
  in block <unit> at xt/check-signatures.t line 61
```

Maybe some instructions would be needed for check-signature.

**Comment by coke** [comment]
What version of rakudo are you using (and what version is your checkout)?

**Comment by JJ** [comment]
Latest release, I was it was already fixed after you reported a similar error.

**Comment by coke** [comment]
After your change, I no longer see .new reported on in the test output (it doesn't error, but it doesn't list as a pass, either)

**Comment by coke** [comment]
I removed the skip on this - latest version of rakudo has this type, so all the tests pass using that.

**Comment by coke** [comment]
The 'method new' lines aren't matching the grammar, needs to be expanded to match.

**Comment by coke** [comment]
This failure mode no longer happens
