### ISSUE TITLE
Error with check-signature.t

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3781]
## Problem or new feature

After downloading the latest version of the source, I get this error:

```
MVMArray: shift expected string register
  in block <unit> at xt/check-signatures.t line 61
```

## Suggestions

It's not entirely clear why we need the source. We can check signatures of the functions in the compiler itself, right?

**Comment by JJ** [comment]
Found the error. Opening a bug in Rakudo.

**Comment by coke** [comment]
@codesections can you respond to @JJ's question about examining Rakudo source vs. runtime?

**Comment by coke** [comment]
Digging through check-signatures.t, it's already doing type introspection in addition to looking at the source. I'm seeing if we can rip out the source inspection entirely.

**Comment by coke** [comment]
@JJ  - is this original issue resolved? We can create a separate ticket for "don't use source for test" if desired.

**Comment by JJ** [comment]
I don't think so. It still needs to check out the external source, right?

**Comment by coke** [comment]
Can anyone aside from JJ reproduce this error?

**Comment by JJ** [comment]
> Can anyone aside from JJ reproduce this error?

You mean it's working OK for you?

**Comment by JJ** [comment]
Well, again we need to specify the source. But then I get this error:

```
The spawned command 'git' exited unsuccessfully (exit code: 1, signal: 0)
  in block <unit> at xt/check-signatures.t line 70
```

**Comment by JJ** [comment]
I've added some error printing, and it appears that my downloaded version does not have the tags it's checking out. Not clear why it's got to check out the tag either? Wouldn't it be easier to just download it and be done with?

**Comment by coke** [comment]
I think the original intent was "work with the rakudo checkout that a docs developer probably already has". If we do a download, we'll have to do the download each time and remove it when done; we'll also need a network connection while running the test (not sure if this is required now, don't think so). If it's desired to switch how that test works, let's open a ticket to track that; I think the diagnostics you added let us close out this ticket (error when running the test)

**Comment by JJ** [comment]
> I think the original intent was "work with the rakudo checkout that a docs developer probably already has". If we do a download, we'll have to do the download each time and remove it when done; we'll also need a network connection while running the test (not sure if this is required now, don't think so). If it's desired to switch how that test works, let's open a ticket to track that; I think the diagnostics you added let us close out this ticket (error when running the test)

But the problem is it's not finding the tags. Either they've changed (most probably) or they're not downloaded for some reason?
Anyway, another alternative would be to just use introspection instead of using at the source, as I suggested originally.

**Comment by coke** [comment]
Your copy is the only one that seems to have this issue. Can you try a fresh clone of rakudo and let us know if the problem persists?

**Comment by JJ** [comment]
Correct. Thanks. Can't imagine why it didn't download the previous ones. It had tags up to 2017 or so.
