### ISSUE TITLE
List of types inheriting from Cool out of date in Cool documentation ?

### ISSUE THREAD

**Issue by stoned** [Raku/doc#3783]
## Problem or new feature

the list of types inheriting from Cool, a listed at in https://github.com/Raku/doc/blob/90efdf1f9e9a2037d244f2335c4ea2405c44a5b9/doc/Type/Cool.pod6#L25 seems slightly out of date.

## Suggestions

Drop this list in favor of the type graph generated from type-graph.txt and let the reader follow the inheritance tree via the type graphs in types' documentation?

**Comment by coke** [comment]
Great idea, finally got to it. Thanks!
