### ISSUE TITLE
Change document extension from .pod6 to .rakudoc

### ISSUE THREAD

**Issue by coke** [Raku/doc#3785]
As referenced in https://docs.raku.org/language/modules, it's the new standard for pod6 only files.

Acceptance criteria:
* install should become no more broken (it's already broken)
*  build should continue to work
* all t/, xt/ tests  should still pass
* must not impact github's Linguist criteria for identifying files

**Comment by JJ** [comment]
But does the standard explicitly exclude .pod6? Problem is, this needs some more stuff like changing github's Linguist criteria, and probably some others. You know I'm very prudent with this kind of things, so I would not do it unless totally and absolutely necessary.

**Comment by coke** [comment]
Sure. Added the linguist item to the acceptance criteria. I definitely don't want anything to break as part of the change, but as a Raku repository, we should (IMO) be trying to follow the updated guidance we're recommending for our users (to help identify issues, set a good example, and find any issues before our users have to deal with them.)

**Comment by coke** [comment]
Probably a good idea to test it out on a fork so we can make sure all the github interactions work as expected (and if not, can be used as a reference to report the issue to github)

**Comment by coke** [comment]
Aside from our own tooling, should make sure that both raku/rakudoc and raku/doc-website are happy with this change.

**Comment by finanalyst** [comment]
This works for doc-website.

**Comment by coke** [comment]
initial attempt in branches/rakudoc, but I may drop that and retry to avoid merge issues.

**Comment by duncand** [comment]
> initial attempt in branches/rakudoc, but I may drop that and retry to avoid merge issues.

Given the nature of the change and how old the branch is, it would totally make sense to just redo it.  The core rough cut is just a multi-file search and replace of a static string plus some file renames likewise.  This may be less effort than trying to reconcile with git.  But if you did decide to keep the current branch, rebasing the branch on trunk is best rather than trying to merge to trunk.

**Comment by coke** [comment]
The branch is very recent (created today) and our primary branch is main, not trunk.
