### ISSUE TITLE
"proclaim" seems to be missing from Test

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3789]
## Problem or new feature

After seeing it in a Rakudo issue, [`proclaim`](https://github.com/rakudo/rakudo/blob/927fa332cca131485aee32d0cf51c1c0f7f9988d/lib/Test.rakumod) is missing from the [documentation of Test](https://docs.raku.org/type/Test) or anywhere else.

## Suggestions

Issues go back to [2016, like this one](https://github.com/rakudo/rakudo/commit/4a954d8858d514998ff6066663e5f1cd193fb1f1) So I wonder why it's not there. Maybe it's not spec. Check it out, anyway, and meanwhile, check out also other possible missing functions.

**Comment by coke** [comment]
```proclaim``` does not appear in the spec tests, so can be consided rakudo-specific

**Comment by lizmat** [comment]
Anything without an `is export` trait in `Test`, should be considered an implementation-detail.  `proclaim` is *not* exported, and is even in a "private subs" section of the code.

**Comment by lizmat** [comment]
So I think this issue can be closed?
