### ISSUE TITLE
Use better examples for "long names"

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3795]
## Problem or new feature

["long names"](https://docs.raku.org/type/Signature#Long_names) or ;; are used as part of the signature to 

> To exclude certain parameters from being considered in multiple dispatch

However, the example does not really use multiple dispatch. There are other examples [here](https://docs.raku.org/language/functions#Multi-dispatch) which do not really clarify why they are used. 

## Suggestions

Use better example, and real use cases (see #1748 ). They are used throughout the whole Rakudo code, so that shouldn't be difficult to find.

**Comment by 2colours** [comment]
Same as: https://github.com/Raku/doc/issues/4268
