### ISSUE TITLE
Curry is not defined

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3796]
The verb "curry" is not defined in the context of programming.

**Comment by JJ** [comment]
Right. We have [whatever-currying](https://docs.raku.org/type/Whatever#index-entry-Whatever-currying), but not what's understood, in functional programming, as currying. Maybe add to the glossary?

**Comment by tbrowder** [comment]
Yes, that would help. I notice Zoffix also created an issue on the whatever-currying discussion.

**Comment by raiph** [comment]
There's no built in in Raku that does currying, there's no obvious affinity of the notion with anything in Raku, mentioning it is like mentioning COBOL picture clauses outside a COBOL to Raku guide. Why?
