### ISSUE TITLE
l[2] is 3 NOT 2

### ISSUE THREAD

**Issue by danieladickey** [Raku/doc#3797]
https://docs.raku.org/language/py-nutshell
Under "Variables" your python example : 
s = 10
l = [1, 2, 3]
d = { a : 12, b : 99 }
 
print s 
print l[2]
print d['a']
\# 10, 2, 12 

However, print l[2] should print 3 not a 2 the last line should be # 10, 3, 12

**Comment by JJ** [comment]
Thanks! We'll fix it momentarily.

**Comment by coke** [comment]
I am not a python person, but I found I had to use this code:

```
s = 10
l = [1, 2, 3]
d = { 'a' : 12, 'b' : 99 }

print(s)
print(l[2])
print(d['a'])
# 10, 3, 12
```

quoting the characters and ()ing the prints.

**Comment by Altai-man** [comment]
@coke print parens are necessary for Python 3, the tutorial was likely written to reflect Python 2 (oh, the irony), so yes, your code is correct, just need to patch the example.
