### ISSUE TITLE
https://docs.raku.org/language/traps: Section title and discussion "assigning to Nil" is wrong

### ISSUE THREAD

**Issue by vonbrand** [Raku/doc#3798]
The section type "Assigning to Nil" is wrong, the body really covers what happens when you assign `Nil`. Trying to assign to `Nil (e.g., `Nil = 42`) gets you an error message that you can't modify an immutable.

**Comment by JJ** [comment]
That's bad. Thanks for the report.

**Comment by coke** [comment]
Also, it's not showing assignment, which is :=
