### ISSUE TITLE
"zef install rakudoc" fails

### ISSUE THREAD

**Issue by j-mckim** [Raku/doc#3802]
## Problem or new feature

I'm trying to get the 'rakudoc' cli command to work on my freshly installed raku. This raku is via the rakudo-moar-2020.12-01-linux-x86_64-gcc.tar.gz binary package made available on the rakudo site.

The page https://docs.raku.org/programs/02-reading-docs describes installing rakudoc via zef. That does not work for me.

The diagnostic from zef:

$ zef install rakudoc
===> Searching for: rakudoc
No candidates found matching identity: rakudoc

A search of raku.modules.org didn't find anything either.

I see the rakudoc development project at https://github.com/Raku/rakudoc. Using its installation procedure requires cloning the rakudoc repository. Is that the recommended procedure?

## Suggestions

Is there a preferred way to do gain the rakudoc command? It would be helpful to fix the page to indicate how to do this.

**Comment by JJ** [comment]
Thanks for the report. We'll try to fix this as soon as possible. Yes, it's more or less our thing to care about rakudoc, too.

**Comment by Altai-man** [comment]
Is it https://github.com/Raku/rakudoc/blob/master/META6.json just not being published?

**Comment by JJ** [comment]
We need to do it soon-ish...

**Comment by coke** [comment]
This is a duplicate of #3769 - please follow that ticket for resolution.
