### ISSUE TITLE
Glossary is missing some terms/phrases seen in error messages

### ISSUE THREAD

**Issue by MasterDuke17** [Raku/doc#3809]
## Problem or new feature

`raku -e '.say if /asdf \s+ \/'` gives the error message
```
===SORRY!===
Regex not terminated.
at -e:1
------> .say if /asdf \s+ \/⏏<EOL>
Unable to parse regex; couldn't find final '/'
at -e:1
------> .say if /asdf \s+ \/⏏<EOL>
    expecting any of:
        infix stopper
```
but the phrase 'infix stopper' is not in the docs anywhere ('infix' is, but not even 'stopper' by itself).

## Suggestions

Try to find a list of all the `expecting any of:` things and add them to the glossary.

**Comment by JJ** [comment]
Good one. Thanks!

**Comment by Altai-man** [comment]
@MasterDuke17 isn't that just leaking the internal structure of the parser instead of a better error message?

**Comment by MasterDuke17** [comment]
Well, there's been discussion about removing that, but it was decided against a while ago. Some relevant issues/PRs/etc https://github.com/Raku/old-issue-tracker/issues/5585, https://github.com/rakudo/rakudo/pull/871, https://github.com/rakudo/rakudo/issues/2115, https://github.com/rakudo/rakudo/issues/2110

**Comment by Altai-man** [comment]
I remember (have no links) a recent report about Rust error messages being superior to `expecting any of: infix stopper` and can support this idea.

Glancing your relevant tickets: it seems the problem still exists, even if some ideas about addressing it were rejected before. E.g. Zoffix who rejected some of the work also wrote this (https://github.com/rakudo/rakudo/pull/871#issuecomment-245237217):

>So I think rather than adding command line switches and logic to hide information generated by -e code, we should *just improve the usefulness of the expected any message*.

https://github.com/rakudo/rakudo/issues/2115 is still opened, so it is open for analyzing what we have, what we can have, some comparisons to be done, then proposal and implementation of something awesome. Not a doc ticket demanding "This weird thing you see in the error message is a special thing for parsing so you had to google it and go here, ignore that".

**Comment by JJ** [comment]
TBH, I think it's a straighforward thing to try and check out error messages googling them, and having some way of finding them in the documentation is a good idea. @MasterDuke17 is suggesting the glossary, which is not really affected by the "no implementation" thumb rule. You can put something in the glossary that says: look, this is about this thing. Check out here and there. It can only help...

**Comment by Altai-man** [comment]
The discussion about Rust is at https://colabti.org/irclogger/irclogger_log/raku?date=2021-02-10#l290 (above and below).
We can add it to the glossary, but it sounds like a temporary band-aid rather than a proper treatment.

**Comment by coke** [comment]
Infix stopper added in 9c04bb7be7
