### ISSUE TITLE
Zef can't find rakudoc

### ISSUE THREAD

**Issue by nige123** [Raku/doc#3819]
I'd like to use `rakudoc` to view module documentation locally. However, when I try and install with `zef` the following happens:

```
nige@kaizen /home/s3/321.ventures> zef install rakudoc
===> Searching for: rakudoc
No candidates found matching identity: rakudoc
```

Here is what is currently installed:

```
nige@kaizen /home/s3/321.ventures> zef -version
v0.10.0
nige@kaizen /home/s3/321.ventures> raku -version
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
```
I'm following the advice found here:

[rakudoc INTRODUCTION](https://docs.raku.org/syntax/INTRODUCTION)

**Comment by JJ** [comment]
It's not been published... yet. Also, duplicate of #3802

**Comment by coke** [comment]
Until the installer is fixed, we should consider removing this repository from the ecosystem.

**Comment by coke** [comment]
Closing ticket; please refer to #3802 for updates.
