### ISSUE TITLE
There are two "method STORE" in the same page

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3825]
## Problem or new feature

This [page for `STORE`](https://docs.raku.org/routine/STORE) shows the two methods that are there

They're sub-headers of different headers, but that's not taken into account when indexing, so it's not so much an actual error as a indexing rules (whatever these are) error.

## Suggestions

The text in `subscript` actually repeats what's in the `Associative` page. It might make sense to delete the content and point to the other page.

**Comment by coke** [comment]
The generated secondary page is now showing where the methods are coming from.

**Comment by coke** [comment]
Regarding the duplicative content, see #1924.
