### ISSUE TITLE
Pod::To::Text is underdocumented

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3829]
## Problem or new feature

This is clearly a Rakudo feature, and not part of the language. Still, this is a feature that's not indexed as a part of the documentation, just mentioned as part of [Pod6](https://docs.raku.org/language/pod) documentation or [core modules](https://docs.raku.org/language/modules-core)

## Suggestions

This need was arisen by #3828, which mentions improvements to Pod::To::Text, basically. Still, it's the same case as Test, which is thoroughly documented. It should maybe be documented at the same level as Test.

**Comment by JJ** [comment]
Also mentioned in #3229

**Comment by coke** [comment]
Test is required by roast, but Pod::To::Text is not (ok, it's in there once but should not be), and PTT is going away with RakuAST. Rejecting this ticket.
