### ISSUE TITLE
What is SSA?

### ISSUE THREAD

**Issue by van-de-bugger** [Raku/doc#3830]
[Scalar](https://docs.raku.org/type/Scalar):

> SSA-style constants bind directly to their value with no intervening Scalar, even when assignment (=) is used. They may be forced to use a Scalar by assigning a $-sigiled variable to them, at which point, they behave entirely like $-sigiled variables.

The term "SSA-style constants" appears in Raku documentation only once with no explanation what does it mean. "SSA" looks like TLA (tree-letter acronym), but it is not clear which words stay behind it. (Software Security Assurance? Serial Storage Architecture? Super Systolic Array?) Since it is the only appearance of SSA, it would be better to eliminate it completely.

**Comment by JJ** [comment]
If it does not include Super, I'm going to be super-disappointed. Good catch!

**Comment by MasterDuke17** [comment]
https://en.wikipedia.org/wiki/Static_single_assignment_form

**Comment by JJ** [comment]
Hum, this was addressed.

**Comment by JJ** [comment]
Closed by 90bdf94942567a30a573bc1b059e949b5ed20c6d
(which incorrectly said 3880 instead of 3830)
