### ISSUE TITLE
Add 'div' versus '/' for integral operations to traps

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3839]
Newcomers to Raku coming from C++ may not be aware of at least two infix operators that have both integral and real number versions: (1) 'mod' versus '%' and (2) 'div' versus '/'.

Such details should be added to the doc section 'Traps to avoid'.

**Comment by JJ** [comment]
Do you think that should go to "traps" or maybe a possible (so far inexistent) C++ to Raku?

**Comment by moon-chilled** [comment]
Behaviour of integer/noninteger division is highly inconsistent across programming languages.  It's common (outside of c++) that int / int is not int, but the exactly semantics vary wildly.  So I think it is worth putting in the 'traps' section.

**Comment by moon-chilled** [comment]
Behaviour of integer/noninteger division is highly inconsistent across programming languages.  It's common (outside of c and c++) that int / int is not int, but the exactly semantics vary wildly.  So I think it is worth putting in the 'traps' section.

**Comment by tbrowder** [comment]
I definitely agree!

**Comment by 2colours** [comment]
I think it's overboard to label this as a trap, _exactly because_ it varies from language to language. Mentioning one at the description of the other may be sufficient.

Perhaps we could think about how we define 'trap'.

**Comment by tbrowder** [comment]
I agree: I think each def should mention, and link to, the other's definition. I'm still having to look up the proper use.
