### ISSUE TITLE
Non-existent links in existing files

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#3841]
## Links in Primary content files without targets
A primary content file is a pod6 document under the `doc/` directory in this repository.
A link is specified like `L<text|path/to/file#target>`

So the bug is when there is no `target` in `path/to/file` when `path/to/file.html` exists.

For a complete list of these bugs, see [Error Report](https://raku.finanalyst.org/error-report.html).

Some of these bugs seem to have existed from when the Content files were first written, and they are simple typos. The reason they are not picked up is that browsers fail gracefully if the file exists. 

The expected behaviour is for the browser to open the file and move the page so that the target url is at the top (or the middle) of the visible page. Graceful failure leaves the file at the top of the page.

Types of errors: 
- Look at the document `language/io-guide`. You will see that the link texts `.getc` and `slurp` are listed and the underlying urls are shown as `method_getc` and `routine_slurp`. In fact, the references should be `routine_getc` and `method_slurp`.
- In document `language/system` the link text `<code>@*ARGS</code>` (which is browser rendered as `@*ARGS` has an underlying reference to `%24%2AARGS`, which is converted by
a browser as `$*ARGS`. The documentation writer used `%24` instead of `%40`.

There are some *false negatives* as my test regexes are incomplete (the relevant code is in the [link-error-test plugin in the Collection-Raku-Documentation](https://github.com/finanalyst/collection-raku-documentation/tree/master/Website/plugins/link-error-test) distribution). 

For example, there is a reference to `empty set` in `language/math` with underlying url `term_%E2%88%85`. This refers to the target `term_∅`, which exists.  `%E2%88%85` is a combined unicode reference that isn't correctly handled by `link-error-test`. 

However, I think false negatives are now rare.

## Suggestions

These errors can be gradually identified and removed. Since such corrections have no knock-on or side effects, I suggest that they could be assigned to newcomers in Squashathons. 

I shall work on a few and (unless anyone objects) I shall commit corrections without review.

**Comment by JJ** [comment]
This should probably be a test; probably even a normal test, not an xt.

**Comment by Altai-man** [comment]
This is an absolutely awesome suggestion!

I think to effectively approach the "find 404 and fix them" we have to first take a look at how actual anchors are created. Anchor ID generation is tied closely to "metadata" of the `X<>` as well as generated by headers, and so any even sensible changed in this direction will lead to fallout.
See https://github.com/Raku/problem-solving/pull/271/files for further reading.

I think working out a spec (if not changing it, than merely stating it) for how anchor IDs are generated is a prerequisite to working with users of this spec.

**Comment by finanalyst** [comment]
@Altai-man  Perhaps we need to be clearer about some nuances with regard to errors. 

The errors in _this_ issue do **not** generate 404 errors because the resource (the documentation file) **exists**. So browsers fail gracefully pointing at the start of the file. This is why the error mentioned in this issue are so hard to notice. 

I did discover 404 errors, but they were in places that were rarely visited, so no one noticed them and reported them. A week or so ago, I created an issue about 404 errors, and made four PRs to eliminate them. Currently, there are no 404 or 'bad hosts' in the documentation.

I think trying to prevent such problems - as @Altai-man has suggested here - is going to be more difficult. My intuition is that it is better to allow for mistakes to be made, then test them.  I think philosophically the issue here with documentation and `L<>` errors is the same sort of software dilemma about using declarative mechanisms for reducing errors, eg. declaring variables, and run-time tests against which software is run. Raku encourages the use of both techniques.

Also, I should point out in response to @JJ 's comment that there is a BIG difference between mistakes made in a single file, which is what `xt/` or `t/` tests can look for, and mistakes across a **collection** of files, which is what I am drawing attention to here. 

Actually, the 404 errors I uncovered with `Collection` could be discovered using a `t/` test because the `L<>` http/s schema is independent of any of the other files in the collection.

The only way to make the tests covered in this issue is to collect all the information about links and anchors for the whole collection first, then to run through all the links, and compare them with all the anchors. This is what the 'Collection' toolchain does.

I developed Collection because the "evolved" design of Documentable does not easily allow for new code to be easily added to the loop for manipulating a collection. 

Collection is a tool chain for manipulating a collection of files. Basically there is a lifecycle for rendering the whole collection, including a loop that renders all the files. During the lifecycle there is a set of milestones at which plugins can be added. This set of tests is a plugin which runs after all the files have been rendered, and all the information on links and anchors has been collected.

**Comment by Altai-man** [comment]
>The errors in this issue do not generate 404 errors because the resource (the documentation file) exists. So browsers fail gracefully pointing at the start of the file.

Sorry, I was not clear enough. With "404" I did not mean the actual pages missing, but HTML anchors we link to missing. It had nothing to do with the actual response code, just a general way to refer to something non-existent.

I still want to see how do you approach the whole thing with creating anchors to link to.

**Comment by finanalyst** [comment]
Re 404. I did understand your intent in the first place - sorry if that was not properly expressed, but for clarity of conversation, I thought it best to be a bit picky. 

> I still want to see how do you approach the whole thing with creating anchors to link to.

Not quite sure what you mean by this. There is a POD6 specification for `L<>`. It requires care when linking within a collection. If the target is not 'in memory', or there is no 'live' database of targets, I don't see how to eliminate typos. My view is that the whole collection is tested when it is rendered.

**Comment by finanalyst** [comment]
FYI. I have improved the target regexe to include a test for %E2 %xx %yy which are 3-byte UTF8 codepoints. Only 4 are used, so I only check for them.

Also the [error report] (https://raku.finanalyst.org/error-report.html] now has links to target and destination files to help locate the error, and the visible text of the link.

**Comment by Altai-man** [comment]
>Not quite sure what you mean by this

Let me elaborate. Say we refer to something like `L<other page|/link/part#anchor_foo>`. We can easily (in most cases, I guess) judge about `/link/part` piece, because it is a real or generated HTML page. But `#anchor_foo` bit is more complex than that. Right now it is based upon `X<>` code and heading via some really complicated rules in Documentable. In the document I linked to I describe a way to remove all the complex logic and replacing it with some less complex logic.

This issue talks about detection of `#anchor_foo` mis-linking from the user (`L<>`) point of view, but I am saying that looking at the generation bit and making it streamlined is important as well.

**Comment by finanalyst** [comment]
> > Not quite sure what you mean by this
> 
> Let me elaborate. Say we refer to something like `L<other page|/link/part#anchor_foo>`. We can easily (in most cases, I guess) judge about `/link/part` piece, because it is a real or generated HTML page. But `#anchor_foo` bit is more complex than that. Right now it is based upon `X<>` code and heading via some really complicated rules in Documentable. In the document I linked to I describe a way to remove all the complex logic and replacing it with some less complex logic.
> 
> This issue talks about detection of `#anchor_foo` mis-linking from the user (`L<>`) point of view, but I am saying that looking at the generation bit and making it streamlined is important as well.

@Altai-man Thanks for the explanation. I just went back to the document you linked to and I will continue the discussion there. I have a lot to say. Especially after fixing all these mistakes.

**Comment by finanalyst** [comment]
I have fixed all the errors I found using Collection, and learnt a lot about the sorts of problems in links.

One error remains outstanding, and is in another PR related to .Str.

Otherwise, I am closing this issue
