### ISSUE TITLE
CachedIterator mentioned in docs

### ISSUE THREAD

**Issue by coke** [Raku/doc#3852]
A recent commit added a reference to CachedIterator in doc/Type/Seq.pod6 - which I don't see in the rakudo source, only in #2905

There is an attempt to skip the check on those methods, but it's not skipping. Also, if we're going to skip, we should minimize the skip to the minimum section required (one method).

But since I don't see that in rakudo (only a changelog entry from 2019), I think it should be removed (perhaps by reverting 682cda4454e82bb1539ee82ad71074142820a40d, or by removing the skip & the CachedIterator variant)

**Comment by lizmat** [comment]
I removed the CachedIterator code just before a release because of Blin breakage, and then forgot about it.  I'll look putting it back, as it is a very useful optimization.

**Comment by JJ** [comment]
Meanwhile, we'll have to remove those definitions.
