### ISSUE TITLE
Remove old version info

### ISSUE THREAD

**Issue by p6steve** [Raku/doc#3853]
https://docs.raku.org/language/operators#infix_...

Note: the variants ^..., ^...^, ^… and ^…^ have been available in Rakudo compiler starting from 2020.05 release.

I reckon this line is now superfluous - propose it is deleted

**Comment by JJ** [comment]
Not totally sure about this. There are notes like this all over. If there's
something that was not available in the initial version, but on a later
release, it's always indicated that way. Even more, I would put "Note" in
boldface so that it's clearer.

**Comment by p6steve** [comment]
ok - that’s cool

**Comment by JJ** [comment]
Thanks!
