### ISSUE TITLE
Docs need a reference or bibliography section

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3862]
Given the nature of much of Raku, particularly in dealing with time and the associated clases (Duration, Instant, Date, DateTime, role Dateish), it would be useful to have a section in the docs to keep references for use in descriptions throughout the document website.

**Comment by Altai-man** [comment]
Can you please elaborate?
Why https://docs.raku.org/type.html is not good as a reference/index?

**Comment by tbrowder** [comment]
I mean a location for bibligraphic references to authoritative sources outside the Raku domain. For example, scholarly articles and books as well as online references. Unicode sources are a perfect example of a Raku topic referring to an external reference.

**Comment by JJ** [comment]
Common practice now is simply linking them from where they are used. Do you think an additional section would be necessary?

**Comment by tbrowder** [comment]
I'm thinking specifcally about my words on the new methods on DateTime. It would be easier to do somthing like "see References L<23|ref>, p. 63; L<32|ref>, p. 92; and L<40|ref>, pp. 102-105...", especially when the refs need repeating in other chunks of text.

But it's probably not worth the effort.
