### ISSUE TITLE
Should get() be added to Independent routines ?

### ISSUE THREAD

**Issue by hakonhagland** [Raku/doc#3872]
```
$ raku -e "dd &get'
Sub get = proto sub get ($?, *%) {*}
```
but `get()` seems to be missing from [Independent routines](https://docs.raku.org/language/independent-routines)

**Comment by JJ** [comment]
Yep, it should. Well seen

**Comment by raiph** [comment]
`get` is unusually hard to discover.

cf https://stackoverflow.com/questions/70993976/perls-inp-in-raku
