### ISSUE TITLE
NativeCall cannot return unsigned int

### ISSUE THREAD

**Issue by codechurch** [Raku/doc#3877]
## Problem or new feature

Hi guys,
I want to call a native function from 'xxx.so'.   
The code is:

my sub c_hash64(CArray[uint8], uint64 , uint64) returns int64 is native('xxx') {*}

my sub hash(Str $str) returns UInt {
	my $buf = $str.encode.list;
	my $r = c_hash64(CArray[uint8].new($buf), $buf.elems, 0);
	if $r < 0 {
		return 2**64 + $r
	} else {
		return $r
	}
}

If I use 'returns uint64'  for c_hash64,  the sub 'c_hash64' remains returning a int64, not a uint64. 
So I must plus 2**64 to the integer.
I think it's a bug.

**Comment by JJ** [comment]
Thanks for the report, but I'm not totally clear about what you are reporting here. Does it refer to an specific example in the documentation?

**Comment by codechurch** [comment]
Hi JJ,

    Please look at the following code. 
    
`
#!/usr/bin/env perl6
use v6;
use NativeCall;

my sub c_hash64(CArray[uint8], uint64 , uint64) returns uint64 is native('cua') {*}

my sub hash(Str $str) {
	my $buf = $str.encode.list;
	return c_hash64(CArray[uint8].new($buf), $buf.elems, 0);
}

say hash('1').fmt('%u');   ### error here,  line:12
`
>>Output:   
negative value '-5209518570039057196' for %u in sprintf
Cannot stringify this object of type VMArray (BOOTArray)
  in block <unit> at ./native.p6 line 12


So, the 'sub c_hash64' is specified the 'uint64' as return-type, but it returns a int64 actually. 
And, the return value cannot format in '%u'. 
I think that is a bug at the native-call's returning.

**Comment by JJ** [comment]
Again, is this an example in the docs? Or does it exemplify something found there?

**Comment by codechurch** [comment]
Sorry. The issue is not about bug in the docs. It's just a bug in Raku runtime, I think.
I closed it.
Very sorry for wasting your time, JJ. Bye

**Comment by JJ** [comment]
No problem at all, @codechurch. If you want, I can reopen it and move it to the rakudo/rakudo repo, where they will probably be able to help you. You might want to try StackOverflow, too.

**Comment by codechurch** [comment]
Hi， @JJ，
I am willing to submit it myself and see if it has been repeated, thank you for your help.
