### ISSUE TITLE
101 example page, exercise 1, throws an error

### ISSUE THREAD

**Issue by merryandsilver** [Raku/doc#3887]
Hi,

At the bottom of the page, the answer to exercise 1 throws an error with scores.txt unchanged.

With the first line of scores.txt removed, it works.

The example says the first line of scores.txt is "not necessary," but that could mean "not necessary to process."

The answer suggests changes to the program, not scores.txt.

**Comment by JJ** [comment]
Do you mean the first example in [this page](https://docs.raku.org/language/101-basics)

**Comment by JJ** [comment]
OK, I see what you mean. Not only you have to remove the first line, but also the line where @names are read. I'll try to change the text to reflect this
