### ISSUE TITLE
Checklist for release 2021.05

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3888]
#  Additions:
 * [x] Add support for `∊` and `∍` as aliases for `∈` and `∋` -[d00c7e35](https://github.com/rakudo/rakudo/commit/d00c7e35) 
#  Changes:
 * [x] Make `lc`, `uc`, `tc`, `tclc`, `fc`, `flip` methods on `Allomorph` return `Str` instance
      to make it consistent on subclassing -[bb069a99](https://github.com/rakudo/rakudo/commit/bb069a99)

**Comment by coke** [comment]
All checklist items checked - closing ticket.
