### ISSUE TITLE
"Proc::Async" links lead to 404: Page Not Found

### ISSUE THREAD

**Issue by wphtech** [Raku/doc#3895]
## Problem or new feature

On the page, 
https://docs.raku.org/type/Proc 
under the session "Potential Deadlocks", there are two links for "Proc::Async" points to the following dead link.

https://docs.raku.org/Proc::Async

## Suggestions

Please fix it.

**Comment by JJ** [comment]
Thanks for the report. I'll try and see what's the deal.
