### ISSUE TITLE
rename util/*.p6 to util/*raku

### ISSUE THREAD

**Issue by coke** [Raku/doc#3905]
Need to rename the files.

- [x] Remove the "use v6" (Raku doesn't really need this anymore)

Change any references to the file names elsewhere in the repo.

- [x] util/issue-with-all-pod6.p6
- [x] util/list-missing-methods.p6
- [x] util/missing-types.p6
- [x] util/new-type.p6
- [x] util/perl-nbsp.p6
- [x] util/to-raku.p6
- [x] util/unskip.p6

**Comment by coke** [comment]
Remaining:

- [ ] util/issue-with-all-pod6.p6
- [ ] util/list-missing-methods.p6
- [ ] util/missing-types.p6
- [ ] util/new-type.p6
- [ ] util/perl-nbsp.p6
- [ ] util/to-raku.p6
- [ ] util/unskip.p6

**Comment by JJ** [comment]
Many thanks, Will. :100:
