### ISSUE TITLE
Add overview comment to util/*

### ISSUE THREAD

**Issue by coke** [Raku/doc#3906]
The files in util/ are not commonly used, having the comments will help with maintenance of the repo.

- [x] util/clean-spell
- [x] util/create-brackets-table.raku
- [x] util/github-action-test.sh
- [x] util/ignored-methods.txt
- [x] util/list-missing-methods.raku
- [x] util/missing-types.raku
- [x] util/new-type.raku
- [x] util/perl-nbsp.raku
- [x] util/sort-words.raku
- [x] util/test-modified.sh
- [x] util/unskip.raku
- [x] util/update-and-test

**Comment by coke** [comment]
Related: we have both Dockerfile and util/Dockerfile - They appear to be basically duplicative, with some formatting differences, and direct invocation of commands vs. invoking a script. If we can eliminate one as part of this effort great, otherwise let's include documents on the top level Dockerfile as well so we know why they're different.

**Comment by JJ** [comment]
You mean inline comments here?
Also, re: Dockerfile. I need to find out why these were done. I think that one is used in Circle, and the other elsewhere. I'm going to check it out.

**Comment by JJ** [comment]
Right, one is a `no-docs` Dockerfile used to create the docs (and thus probably useless now, since building is no longer done here). Refers to #2525
