### ISSUE TITLE
Need a tutorial for Linux users wanting to use Raku on Windows

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#3913]
# Problem

I am a long-time *nix user (since 1987) and only use Windows when absolutely necessary. I do not keep up with the minutiae of Windows administration, thus I cannot easily show someone how to use Raku "natively" on Windows or take advantage of the latest built-in Linux subsystem to use it at the Command Line Interface (CLI).

I do realize most non-geek adults and most young people in school are not routinely exposed to Raku and are not interested in using Linux just to use Raku, so I want to know how to most easily get Raku working on Windows (my primary use cases being my grandchildren and their school-mates, and perhaps their teachers).

In that regard, I would like to see added to the docs a short tutorial or checklist for installing and using Raku aimed at novice Windows users. Such a tutorial would include:

+ obtaining the Windows MSI file
+ installing the MSI file
+ how to show "Hello, Word!" at the CLI
+ selecting and using a suitable free or inexpensive begnning editor to use for simple programming in Raku

Then the Raku afficianado can be armed with a practical setup to compete with the Python peddlers that have confused young, beginning programmers!

**Comment by JJ** [comment]
The problem seems to be that use of Windows among Raku users is testimonial, if any. Issues such as #2534 stay open for ever. I seem to remember there was also another one on how to write Unicode characters in Windows, that's been open for a long time. So, while agreeing with you, it's a catch-22 problem: no one uses Windows around here, so there's no tutorial, so people using Windows are discouraged. We'll really have to wait for someone willing to spend time with Windows for this kind of thing, which I agree with you would help.

**Comment by tbrowder** [comment]
I have thought about asking Todd (our favorite Windows user) to give it a try. I will do that now!

**Comment by patrickbkr** [comment]
Did you notice https://github.com/rakudo/rakudo/pull/4448 ? I.e. I hope to be able to provide an MSI installer from the 2021.07 release onward.

I think I managed to make things a bit more intuitive to use. E.g. there are now Start menu shortcuts installed that open respective command line interfaces, which in turn will always display a short introduction of how to use Rakudo. This is not and can not be a substitute for a Windows getting-started tutorial though.

**Comment by coke** [comment]
My take on this is that this doesn't belong on the language doc site; there are already related tickets here about improving the docs.

https://github.com/rakudo/rakudo.org/issues

Please see if one of these addresses the need; if not, please create one and feel free to assign it to me.
