### ISSUE TITLE
js-nutshell: mention `//` equivalent of Nullish coalescing operator `??`

### ISSUE THREAD

**Issue by mykhal** [Raku/doc#3928]
[JavaScript (Node.js) to Raku - nutshell](https://docs.raku.org/language/js-nutshell) could mention JS *[Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)* (also called *First-Defined* operator).

This JS operator is similar to `||`, but noes not progress on falsy, but nullish, i.e. not e.g. on `0`, or `""` – only on `null` or `undefined`.
```js
undefined || null || 0 || 1 ;   // => 1
undefined ?? null ?? 0 ?? 1 ;   // => 0
```

It seems to be equivalent to Raku [`//` operator](https://docs.raku.org/language/operators#infix_//)
```raku
(Any) || Nil || 0 || 1 ;   # => 1
(Any) // Nil // 0 // 1 ;   # => 0
```
.. but I'm not sure if there aren't more gotchas.

**Comment by Kaiepi** [comment]
A section on `//` would be a good place to describe Raku's notions of definedness and definiteness in general. `with`/`without` could use one too.
