### ISSUE TITLE
log2 & log10 description incorrect in Class cool.

### ISSUE THREAD

**Issue by mabiggar** [Raku/doc#3929]
## Problem or new feature

says raised to 2 (10) should be other way around

## Suggestions

Fix it.

**Comment by tbrowder** [comment]
Please submit a PR. Then we know exactly what the problem is.

**Comment by JJ** [comment]
I'm checking [this page](https://docs.raku.org/routine/log2) and it does seem to be correct, at least in the page you mention. Maybe you found that somewhere else?

**Comment by mabiggar** [comment]
For example, log10 says "a number that approximately produces the original number when raised to the power of 10".  Should it not say "when 10 is raised to the number" or something like that.  Likewise for.log2.


Mark Biggar
--
***@***.***
***@***.***

**Comment by JJ** [comment]
Ah, right. Sorry.
