### ISSUE TITLE
Haskell-to-p6 `takeWhile`

### ISSUE THREAD

**Issue by mykhal** [Raku/doc#3932]
[Haskell to Raku - nutshell](https://docs.raku.org/language/haskell-to-p6) doc does not mention `takeWhile` function, e.g.

```haskell
> fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
> takeWhile (<20) fibs
[0,1,1,2,3,5,8,13]
```

I'm not sure what's best Raku idiom. `.grep`, `.head` probably cannot be used (in general), so.. `.toggle` ? (I hope there's something better):
```raku
> my @fibs = 0, 1, { $^a + $^b } ... Inf
> @fibs.toggle(* < 20)
(0 1 1 2 3 5 8 13)
```

**Comment by mykhal** [comment]
Simpler example:
```haskell
> takeWhile (<10) [1, 2, 3, 40, 50, 60, 7, 8, 9]
[1,2,3]
```

**Comment by Util** [comment]
Exiting the codeblock of a `grep` via `last` will terminate the iteration!
( Discovered while writing https://conf.raku.org/talk/158 )
```
say grep { $_ < 10 or last }, [1, 2, 3, 40, 50, 60, 7, 8, 9];
(1 2 3)
```
I would expect this to become the equivalent to (Haskell|Python+itertools)'s takeWhile, in idiomatic Raku.
If you did want a wrapper to minimize culture shock, this version may be helpful:
```
sub takeWhile ( Code $c, @s ) { @s.grep: { $c.($_) or last } };

say eager takeWhile * < 20,  (1, 1, { $^a + $^b } ... Inf);
(1 1 2 3 5 8 13)
```

**Comment by lizmat** [comment]
````raku
sub takeWhile(&code, @s ) { @s.grep: { code($_) or last } }
````
Taking a `Callable` is generally done using the `&` sigil.  And when done that way, you don't need to specify the `&` when using it to invoke it.

**Comment by Util** [comment]
@lizmat , Thanks!

I had a buggy initial version that used &code, and convinced myself (in error) that using the `&` was part of the bug.
Now we can use `.&` (call sub with $_ as argument) using a method-like syntax) to write it as:
```
sub takeWhile ( &code, @s ) { @s.grep: { .&code or last } }
```

**Comment by mykhal** [comment]
The nice `or last` trick for some reason works differently in some 2016 releases…

https://gist.github.com/Whateverable/5a3e6fab8d2f802ccaac6ddf7c837de6

**Comment by lizmat** [comment]
Those should be considered a bug.

**Comment by mykhal** [comment]
Another potentially idiomatic approach, inspired by today's Raku conference 1, lecture 1:

```raku
[1, 2, 3, 40, 50, 60, 7, 8, 9] ...^ !(* < 10)   # => (1, 2, 3)
```
(And it has same result in all releases)
