### ISSUE TITLE
"Depreciated" error gets wrong line

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/doc#3937]
Hi All,

Fedora 34
Xfce 4.14

$ raku -v
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.07.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.07.

The following code throws a "depreciated error" (code is sliced up to show the error, the code is not meant to work)

```
#!/usr/bin/env raku

 
sub RunNoShellAll( Str $RunString, Bool $StdOut, Bool $StdErr, Int $Code ) {
   my Buf $BufStdOut; 
   my Buf $BufStdErr; 
   my Str $ReturnStr = ""; 
   my Str $ReturnErr = "";
   my Int $RtnCode = 0;
   my $proc;
   
   my @RunArray  = $RunString ~~ m:global/ [ '"' <-[ " ]> * '"' | \S+ ] /;
   for @RunArray.kv -> $index, $value { @RunArray[$index] ~~ s:g/\"//; };
   $proc      = run( @RunArray, :err, :out, :bin );
   
   if  $Code    { $RtnCode   = $proc.status; } 
   
   return( $ReturnStr, $ReturnErr, $RtnCode );
}


sub RunNoShell( $RunString ) is export( :RunNoShell ) {
   my Str $ReturnStr = ""; 
   my Str $ReturnErr = "";
   my Int $RtnCode   = 0;
   
   ( $ReturnStr, $ReturnErr, $RtnCode ) = RunNoShellAll( $RunString, True, False, True ); 
   return ( $ReturnStr, $RtnCode );
}


(my $x, my $y)= RunNoShell "pwd";
say "$x\n$y";

```

Here is the error as presented:

```
$ Deprecated.pl6
 Deprecated.pl6

0
Saw 1 occurrence of deprecated code.
================================================================================
Sub RunNoShellAll (from GLOBAL) seen at:
  ./Deprecated.pl6, line 27
Please use exitcode and/or signal methods (status is to be removed in 2022.06) instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!

```

Problem.  The offending line is NOT line 27, 
       27:    ( $ReturnStr, $ReturnErr, $RtnCode ) = RunNoShellAll( $RunString, True, False, True ); 
it is line 16
      16:  if  $Code    { $RtnCode   = $proc.status; } 

You can reproduce the by comment out and un-commentating out line 16.

Please fix,

Many thanks,
-T

**Comment by lizmat** [comment]
This was a problem in 2021.07, it got fixed in 2021.08.

**Comment by JJ** [comment]
Not a documentation problem, anyway. Do you want me to transfer it to Rakudo or close it altogether?

**Comment by lizmat** [comment]
Transfer to Rakudo and then close?

**Comment by JJ** [comment]
I apparently can't transfer between different organizations. So closing directly.

**Comment by ToddAndMargo** [comment]
Hi Liiznat,

Thank you!  :-)

Was it the wrong line number on the error you fixed?  Or was it tagging 
     16: if $Code { $RtnCode = $proc.status; }
as deprecated that you fixed?  Or both?

-T

**Comment by lizmat** [comment]
The problem was in the way the `is DEPRECATED` trait was being handled on `proto`s.  I didn't fix that, I just put the `is DEPRECATED` trait on all candidates as a quick fix.

**Comment by ToddAndMargo** [comment]
Is

        16: if $Code { $RtnCode = $proc.status; }

actually depreciated?  If so, can you point me to the documentations as to its replacement?

**Comment by jonathanstowe** [comment]
The replacement is stated in the deprecation message: `Please use exitcode and/or signal methods (status is to be removed in 2022.06) instead.`  Both are documented in https://docs.raku.org/type/Proc

**Comment by ToddAndMargo** [comment]
A keyword search for "status" on https://docs.raku.org/type/Proc draws a blank.

I did find

my $exit-code       = $p.exitcode;

Perhaps you have a newer copy of the documentation?

**Comment by jonathanstowe** [comment]
No, no `status` isn't documented because it is deprecated.  You should be using `exitcode` instead.

**Comment by ToddAndMargo** [comment]
Your previous statement 

"The replacement is stated in the deprecation message: Please use exitcode and/or signal methods (status is to be removed in 2022.06) instead. Both are documented in https://docs.raku.org/type/Proc" 

led me to believe that "both" were documented: depreciated code and replacement code.    If this is not what you meant, I would like to suggest that you create a section in Proc that discusses what is deprecated and replaced by what. If it is what you meant (both), it should be added.

**Comment by jonathanstowe** [comment]
I meant both "exitcode" and "signal" are documented.

**Comment by ToddAndMargo** [comment]
Makes sense now.

How about a paragraph in the doc as to what is depreciated?
