### ISSUE TITLE
Problem with url generation when the fragment contains some symbols

### ISSUE THREAD

**Issue by k3ut0i** [Raku/doc#3946]
In `Language/iterating.pod6`, this link  `L<C<^> twigil|/syntax/$CIRCUMFLEX_ACCENT#(Traps_to_avoid)_twigil_^>`
 was translated (in `language/iterating`) to this link 
`https://docs.raku.org/syntax/$CIRCUMFLEX_ACCENT#(Traps_to_avoid)_twigil_$CIRCUMFLEX_ACCENT`
 where as the appropriate section is at  `https://docs.raku.org/syntax/$CIRCUMFLEX_ACCENT#(Traps_to_avoid)_twigil_^`

So either the index entries in each document must be translated, or the fragments in the url generation must be left untranslated.

I have found a few links that involve `^` that do not redirect to the appropriate section.

`L<this page|/language/variables#The_^_twigil>` in Language/5to6-perlvar.pod6
`L<placeholder|/language/variables#The_^_twigil>` in Language/control.pod6
`L<.^|/language/operators#methodop_.^>` in Language/typesystem.pod6
`L<More information|/language/operators#infix_(^),_infix_⊖>` in Language/setbagmix.pod6

I am not sure which symbols (other than ^) are being translated. So there might be more.

**Comment by JJ** [comment]
That's done in [Documentable](https://github.com/Raku/Documentable). It's probably better if the issue is raised there. Thanks for providing these examples.

**Comment by k3ut0i** [comment]
The issue seems to have been raised here https://github.com/Raku/Documentable/issues/149 .

Should I close this ?

**Comment by JJ** [comment]
> The issue seems to have been raised here [Raku/Documentable#149](https://github.com/Raku/Documentable/issues/149) .
> 
> Should I close this ?

If you're so kind to add the examples included here as additional info, I would appreciate it.

The fact that it's not been solved is actually more convoluted than that. We don't have a principled way of generating URLs. [This PR was created with that intention](https://github.com/Raku/problem-solving/pull/216), but then stalled.

So having more information that can be turned into tests will certainly help. But the solution is not easy, and will not come fast, I'm afraid.

**Comment by k3ut0i** [comment]
Closing this, as the issue is begin tracked here: https://github.com/Raku/Documentable/issues/149
