### ISSUE TITLE
callable placeholder vars are not documented nor indexed

### ISSUE THREAD

**Issue by gfldex** [Raku/doc#3953]
Callable placeholder vars are well specced in S02-types/anon_block.t, S06-signature/mixed-placeholders.t, S06-signature/positional-placeholders.t, S14-traits/routines.t but not mentioned in /language/variables . As a result `&^` is missing from the search index.

Placeholder vars do create a `Signature`, which is not touched in /type/Signature nor does /language/variables link there.

Named callable placeholders are not documented at all and as such not indexed by `&:`. Those are specced ... a lot.

**Comment by JJ** [comment]
Thanks for the report.
