### ISSUE TITLE
broken link to Testing in Modules documentation

### ISSUE THREAD

**Issue by zjmarlow** [Raku/doc#3959]
## Problem

In the [Modules](https://docs.raku.org/language/modules) documentation, in the [Testing modules and a distribution](https://docs.raku.org/language/modules#Testing_modules_and_a_distribution) section, in the text "(see Testing)", there is a broken link to the Testing documentation.  The link is to /language/Testing but should be /language/testing

**Comment by JJ** [comment]
Got it. Thanks for the report!
