### ISSUE TITLE
Promise.then: code argument is not documented

### ISSUE THREAD

**Issue by van-de-bugger** [Raku/doc#3974]
## Problem or new feature

[Promise.then](https://docs.raku.org/type/Promise#method_then) documentation is: 

> **method then**
>
>     method then(Promise:D: &code)
>
> Schedules a piece of code to be run after the invocant has been kept or broken, and returns a new promise for this computation. In other words, creates a chained promise.
>
>     my $timer = Promise.in(2);
>     my $after = $timer.then({ say "2 seconds are over!"; 'result' });
>     say $after.result;
>     # OUTPUT: «2 seconds are over␤result␤»

Method `then` passes its object as the first argument to the `&code`, but this is not documented.

## Suggestions

Describe the `&code` parameter and include it into example, either as named parameter:

    my $timer = Promise.in(2);
    my $after = $timer.then(-> $p { 
        if $p.status ~~ Kept { say "2 seconds are over!"; }; 
        'result' 
    });
    say $after.result;
    # OUTPUT: «2 seconds are over␤result␤»

or implicit positional parameter: 

    ...
    my $after = $timer.then({ 
        if $^a.status ~~ Kept { say "2 seconds are over!"; }; 
        'result' 
    });
    ...

**Comment by coke** [comment]
Thanks!
