### ISSUE TITLE
Allow multi-packet response in the "hello world" HTTP server at https://docs.raku.org/type/IO::Socket::Async

### ISSUE THREAD

**Issue by ramiroencinas** [Raku/doc#3979]
In relation with https://github.com/rakudo/rakudo/issues/4628, the HTTP server simple example from https://docs.raku.org/type/IO::Socket::Async transmits only a packet (65535 chars) to the client. Can be used another more `whenever` to transmit all the packets to the client if the response has more than 65535 chars:

```raku
react {
    whenever IO::Socket::Async.listen('0.0.0.0', 3333) -> $conn {
        whenever $conn.Supply.lines -> $line {
            my $http_message = qq:heredoc/END/;
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Encoding: UTF-8

<html>
<body>
    <h1>Hello World!</h1>
    <p>{ $line }</p>
</body>
</html>
END
            whenever $conn.print: $http_message -> $x { $conn.close; }
        }
    }
    CATCH {
        default {
            say .^name, ': ', .Str;
            say "handled in $?LINE";
        }
    }
```

**Comment by JJ** [comment]
Do you think this would help the reader to understand the concept better?

**Comment by ramiroencinas** [comment]
I think that anyone who tests the example with the idea of using it in production will lose interest in it when finds that the example silently fails to transfer beyond a single packet.

**Comment by ramiroencinas** [comment]
Anyway forget my proposal server code example because fails with a web browser client throwing a `Cannot write to a closed socket`. I will investigate a solution that can run with any http client.

**Comment by coke** [comment]
@ramiroencinas  - any update on this? Would love to get the improved example code.

**Comment by coke** [comment]
Hopefully fixed with @voldenet 's PR.
