### ISSUE TITLE
Modules Introspection: incomplete sentence "As explained"

### ISSUE THREAD

**Issue by flwyd** [Raku/doc#3984]
## Problem or new feature

The last sentence of the [Introspection section of the Modules documentation](https://docs.raku.org/language/modules#Introspection) is incomplete, it just says "As explained".

## Suggestions

I don't know if this is an accidental copy/paste (the sentence before the previous example also starts with "As explained") or if the author didn't complete their thought.

**Comment by JJ** [comment]
Very likely. Thanks for the report.

**Comment by coke** [comment]
This was fixed by @JJ in b98e4f248adf3d7ac5cdb9cacba024e16c1b7e9d
