### ISSUE TITLE
Explain where binary (scripts) resources go in a module

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3999]
## Problem

[This document](https://docs.raku.org/language/modules#Upload_your_module_to_CPAN) does not tell where scripts that are going to be copied to some executable path should go

## Suggestions

Include the `bin` directory in the document, and maybe issue a few more instructions on what to put there.

**Comment by sdondley** [comment]
It's mentioned in this section: https://docs.raku.org/language/modules#Basic_structure

**Comment by JJ** [comment]
Right, but then it's not in the expanded explanation.
