### ISSUE TITLE
failed tests in if and when return Empty

### ISSUE THREAD

**Issue by gfldex** [Raku/doc#4017]
The following constructs return `Empty`.
```
    dd do if 0 {};
    dd (42 if 0);
    dd do with Any {};
    dd (42 with Any);
```
 
This is specced in S04-statement-modifiers/if.t and S04-statement-modifiers/with.t but not docced in /language/control . It seems reasoanble to extend /type/Slip#constant_Empty to show where the compiler will creates Empty for us.

**Comment by JJ** [comment]
Thanks for the suggestion.
