### ISSUE TITLE
Describe "forward declaration" of classes using a "stub"

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#4018]
## Problem

The docs currently describe the use of stubs for abstract classes, but do not mention using them for forward declaration of classes in order to defer definition.

For example:

~~~
class Foo {...}
class Bar {
    has Foo $.foo;
}
class Foo {
    say "This is a Foo object";
}
~~~

## Suggestions

Add some text describing the additional use in file 'glossary.pod6'.

**Comment by lizmat** [comment]
Please note this also is allowed to stub subs!
````raku
sub a() { ... }
sub a() { 42 }  # no compilation error
````
