### ISSUE TITLE
Suggested tweaks of `NativeCall` page (Basic use of pointers section, maybe more)

### ISSUE THREAD

**Issue by raiph** [Raku/doc#4025]
Quoting my question and [AfterShock's response](https://stackoverflow.com/questions/71009136/calling-c-function-from-raku-that-was-compiled-in-c-on-windows-why-is-it-not/71011899?noredirect=1#comment125550302_71011899):

> What doc and/or Raku(do) updates would you suggest we consider in reaction to this SO?

> Reading the documentation.. and testing the solution... There was a similar example. I read this [docs.raku.org/language/nativecall](https://docs.raku.org/language/nativecall)... read between the lines... there was an example with CArray[Str].new.... by the way, "Basic_use_of_pointer" should contain an example of that.. it does not.... it should be mentioned... that new pointer needs to be constructed.. by the way, there is example of that... I just noticed couple of minutes ago... >>>(inet_ntop(AF_INET, Pointer.new(nativecast(Pointer,self)+4), $buf, INET_ADDRSTRLEN)<<< though it looks convoluted

I'll ask AfterShock if they'll do a PR.

**Comment by JJ** [comment]
Maybe it's #4026 you're talking about?

**Comment by jaffa4** [comment]
Yes
