### ISSUE TITLE
Operator precedence table is needlessly confusing

### ISSUE THREAD

**Issue by codesections** [Raku/doc#4029]
The [operator precedence table](https://docs.raku.org/language/operators#Operator_precedence) currently has a column labeled `A` with single-letter abbreviations for various types of associativity.  To interpret these letters, the reader needs to cross-reference another table.  These letters aren't used in the source code; as far as I know, this is the only place they're used.

Unless anyone objects, I'll simplify the table by directly listing the associativity and remove the letter-to-meaning table.

**Comment by JJ** [comment]
By all means. Please go ahead.

**Comment by codesections** [comment]
Fixed by #4031
