### ISSUE TITLE
[].sum is not documented

### ISSUE THREAD

**Issue by gfldex** [Raku/doc#4030]
```
say [].sum;
say ().sum;
say Empty.sum;

# OUTPUT: «0␤0␤0␤»
```

Although not surprising, it is not obvious for a NOP to return a result. This is not specced but consistent with coercing non-numeric values to 0.

This should be documented in /type/List#routine_sum .

**Comment by lizmat** [comment]
It's **not** coerced to `0`, it's coerced to **the number of elements**.  Which happens to be 0 for `[]`, `()` and `Empty`.  So there is *really* nothing special here?

**Comment by coke** [comment]
This was changed in doc/Type/List.pod in 208197fc5b on 2016-05-20. Made a similar change to the Any method sum as well.
