### ISSUE TITLE
Try and avoid a condescending tone in the manual, either the reference or tutorial part

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4044]
## Problem or new feature

This is mainly to discuss the issue raised in this PR  → #3993. In general, try and avoid tone that some people try and find condescending, without incurring in a too dry tone that people might also dislike.

## Suggestions

* In the case of "of course" and "obviously": in a case by case basis, see if this particular link is needed, or it can be eliminated along with the rest of the sentence. Alternatives: link to the reference or tutorial so that people can *really* see why that's so clear that it's preceded by an "of course"
* Other cases, again deal with them in a case by case basis.

Additionally, create an author test that warns someone if they're using that sentence, and potential caveats it carries.

**Comment by coke** [comment]
Putting this in an author test is going to be basically impossible.

We can definitely review all existing uses of it, add a note to the style guide, and review future edits in light of that.

**Comment by Altai-man** [comment]
There is hardly a way we can address this issue in an "open the ticket, resolve, close the ticket" fashion. This one is too broad, too subjective to work on it it as a "meta" ticket.

>Other cases, again deal with them in a case by case basis.

To do this, having this ticket around is not needed nor helpful, so closing.
