### ISSUE TITLE
Add documentation for "trying" method

### ISSUE THREAD

**Issue by sdondley** [Raku/doc#4049]
Looking at the `die X::IO::DoesNotExist.new(:path("foo/bar"), :trying("zombie copy"));` line in the code example at https://docs.raku.org/language/exceptions#Typed_exceptions

It's not obvious what, exactly, the nature of the `trying` argument is. At first glance, it looks like an arbitrary string, but judging by the output of the error message, a `zombie` method is run based based on the string passed to `trying`.

There does not appear to be any documentation for the signature for the `trying` method to understand what might be happening.

## Suggestions

Document the `trying` method more thoroughly at https://docs.raku.org/type/X::IO::DoesNotExist

**Comment by lizmat** [comment]
The emphasis on "trying" is all wrong.  Hope https://github.com/Raku/doc/pull/4050 makes it clearer

**Comment by coke** [comment]
PR merged, closing this ticket.
