### ISSUE TITLE
Clarify categories for new terms

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4056]
## Problem or new feature

In some cases, the categories overlap (operators and certain kind of operators) or simply it's not clear what the difference is (Language and Syntax, Enums are not types but behave like types... )

## Suggestions

As part of the CONTRIBUTING file, a clear way to add new terms or even assess if existing ones are correctly categorized should be added. Bonus track if somehow the indexed term can be introspected to check what's it and check it the assigned category is correct. Super extra premium bonus track if Documentable is able to somehow assign categories for non-categorized items based on its introspected type or metaclass.

**Comment by Altai-man** [comment]
>As part of the CONTRIBUTING file, a clear way to add new terms or even assess if existing ones are correctly categorized should be added

Yes, that'd be just wonderful!

>Bonus track if somehow the indexed term can be introspected to check what's it and check it the assigned category is correct

We cannot write an AI that would recognize semantically bogus things, but there is a test which rejects completely invalid _syntax_: https://github.com/Raku/doc/blob/master/xt/search-categories.t

>Super extra premium bonus track if Documentable is able to somehow assign categories for non-categorized items based on its introspected type or metaclass.

This is already done to some degree, e.g. when Documentable sees `=head routine sin` it indexes the thing as a Subroutine, but when it sees `=head routines we like to show to you` it doesn't index.
