### ISSUE TITLE
Category case inconsistency

### ISSUE THREAD

**Issue by coke** [Raku/doc#4063]
Most categories (with the official list in `xt/search-categories.t`) are single word, initial capital.

Of the multiple word variants, most are only first word initial capital, but `Asynchronous Phasers` breaks the trend.

Need to decide on single scheme for consistency.

**Comment by coke** [comment]
Upvote "Asynchronous Phasers" here.

**Comment by coke** [comment]
Upvote "Asynchronous phasers" here.

**Comment by JJ** [comment]
That should have been done at the PR phase. I am not discussing now every single feature that was not reviewed or argued properly back then, or for that matter working on the main branch any more. Please don't assign any issue raised from that PR to me; I'm not going to raise any other either.

**Comment by Altai-man** [comment]
Casing is a very subjective matter here and I doubt it anyhow matters much (please correct otherwise).

To prevent inner struggle with deciding variants, I did
```
➜  ~ raku -e 'say rand; # > 0.5 means all capital'
0.7547762599316356
```
so I'm pro all capital.

**Comment by coke** [comment]
We should also consider if we want to match the existing Heading rule (which I think is only initial cap)

**Comment by Altai-man** [comment]
UPD: on the second note, I was able to find something being an argument pro non-capital case: in this case we'll have less references to change.
@coke any objections for "Asynchronous phasers"?
