### ISSUE TITLE
"Routines" category is unused

### ISSUE THREAD

**Issue by coke** [Raku/doc#4064]
Updated xt/search-categories.t to complain if a category is not in use.

This added test is currently failing because "Routines" is declared in the docs but is not in use.

My recommendation: remove it from the list in the docs (this will cause the test to start passing).

If we do intend to use it, easiest way to get the test to pass is to add it to (at least) one instance.

**Comment by coke** [comment]
Note: the list of categories used for the test is now pulled from the documentation so we avoid the issue we just had where "Foreign" was changed to "Other languages" in one of two places and then the test started failing.

**Comment by Altai-man** [comment]
That's interesting.
