### ISSUE TITLE
(My rendering of) the central operator table in the Operators page is profoundly wrong

### ISSUE THREAD

**Issue by raiph** [Raku/doc#4071]
Please look at [this URL](https://docs.raku.org/language/operators#:~:text=The%20following%20table%20summarizes,level.).

Scroll / look at the paragraph that starts:

> The following table summarizes the precedence levels offered by Raku, **listing them in order from high to low precedence**.

Now look at the table below it. Does it list Precedence Levels in precedence order or alphabetical ordering of level *names*? Do you see `Term` or `Additive` as the first row? I see the latter.

If you see what I see it's profoundly wrong. I suspect it led to today's SO: [Assignment destructuring and operator precedence](https://stackoverflow.com/questions/72081593/assignment-destructuring-and-operator-precedence).

----

Next:

* Go the bottom of the page and click the page edit link, i.e. https://github.com/Raku/doc/edit/master/doc//Language/operators.pod6

* Scroll to the Pod source corresponding to that table. What do you see? I see `Term`, not `Additive`, unless I'm making some wrong assumptions about Pod.

----

Presuming I'm right that the rendered web page doesn't match the Pod source, the two explanations that immediately suggested themselves to me are:

* The static web page rendering is an out-of-date rendering of an earlier version of the Pod source that (presumably accidentally) had this unfortunate combination of the introductory text saying the table would be in precedence order (which seems reasonable) but the actual table is sorted alphabetically.

* The rendering is itself sorting the table rows alphabetically.

My review of blame suggested to me it's never been alphabetically sorted in the Pod source. So that leaves the renderer, or something else I haven't thought of.

**Comment by coke** [comment]
I see JJ working on this in commits referencing this ticket on the github.io site. If you look at https://rakudocs.github.io/language/operators, you'll see it's rendering correctly there in the original order in the pod.

Once I can build the main site (#3904), I can investigate what is causing the sorting in the that version. It's possible a new build will fix the main site without changes; can't tell when the last time that site was published (#4072).

**Comment by raiph** [comment]
Thank you @JJ and @coke for starting to address this issue. This has put my mind at ease for now.

@coke, you can of course do as you wish, but while I think you commenting as you have above is more than AOK, I encourage you to otherwise now focus on the big stuff and deliberately ignore this relatively little localized bug, if need be for the next few months, but at least some weeks. If this issue is the LHF I hope it will be (once #3904 is sufficiently progressed), I'll be more than happy to further investigate, and/or try to contribute to a fix, and/or add another comment here in this issue if I find it's beyond my $paygrade.

Also, in the meantime, if this confuses anyone else and they speak up, we can just tell them to refer to the ordering of operators in the list on the left hand side of the page instead of the ordering of the rows in the table and/or refer them to this issue.

**Comment by coke** [comment]
This also appears to be fixed in the under-review new version of the site: https://github.com/Raku/doc/issues/1246#issuecomment-1101393152

Assigning to @Altai-man as one of the tickets that should be resolvable once that lands

**Comment by falsifian** [comment]
Isn't this the same issue as #4085?

**Comment by coke** [comment]
This appears to be resolved with the new site.
