### ISSUE TITLE
title html escaped too much?

### ISSUE THREAD

**Issue by coke** [Raku/doc#4075]
## Problem or new feature

https://docs.raku.org/routine/%3C==

Shows the title as:
``
infix &lt;==
``
instead of
``
infix <==
``

**Comment by Altai-man** [comment]
Already fixed as http://164.90.207.89:10010/routine/%3C== <-

**Comment by coke** [comment]
My recommendation is that we keep any issues that will be resolved by the new site open until at least we agree to deploy the new site; There are many tickets that fall into this category. Can you find that ticket and link to it?

We'll come out of the monthly call in May with a plan to address this kind of ticket, and hopefully a roadmap/timeline on the new site. Thanks

**Comment by Altai-man** [comment]
As a side note, tickets that are "fixed" in the new website are in general assigned to me (there are 30+ of those right now, and almost all can be considered resolved given the migration takes place). I can also "mark" this one.

**Comment by coke** [comment]
I cannot duplicate this issue on the new site in progress at doc-website; (However I did find a different issue that I opened a ticket for).

Closing this ticket.
