### ISSUE TITLE
404 error on https://docs.raku.org/language/language/operators.html#Operator_associativity

### ISSUE THREAD

**Issue by grizzlysmit** [Raku/doc#4087]
## Problem

broken link https://docs.raku.org/language/language/operators.html#Operator_associativity   yields 404 error

## Suggestions

If someone knows an alternate page point at it, otherwise if you know about this please write a page for it

**Comment by Altai-man** [comment]
Hi! Where did you find this url? It looks very bogus and shuold be fixed, the correct URL is https://docs.raku.org/language/operators#Operator_associativity

**Comment by coke** [comment]
Looks like the commits addressed this, closing.
