### ISSUE TITLE
deprecated code in lib/

### ISSUE THREAD

**Issue by coke** [Raku/doc#4089]
```
Saw 1 occurrence of deprecated code.
================================================================================
Use of the 'CompUnit::PrecompilationStore::File' class seen at:
  /Volumes/BUKKIT/Users/coke/sandbox/raku-doc/lib/Pod/Convenience.rakumod (Pod::Convenience), line 11
Please use the 'CompUnit::PrecompilationStore::FileSystem' class instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
```

**Comment by coke** [comment]
May have to run with `v2022.06` to see it.

**Comment by coke** [comment]
Fix was literally just renaming the invoked class.

**Comment by coke** [comment]
@finanalyst : FYI

**Comment by coke** [comment]
Your fix may be slightly more complicated, e.g. picking this one if it exists, and falling back to the original name if not.

**Comment by finanalyst** [comment]
@coke I solved this for Pod::From::Cache, which I wrote to replace Pod::Cached.
I asked about this on Stackoverflow. Liz provided a nice answer that checks to see which  class spelling is OK at Compile time.

**Comment by coke** [comment]
We do need the smarter fix, because our CI is using an older raku.

**Comment by lizmat** [comment]
Run with `RAKUDO_NO_DEPRECATIONS=1` ?

**Comment by coke** [comment]
That doesn't fix the problem, it delays it, by trading the deprecation warning now for a hard failure later when the feature is finally removed.
