### ISSUE TITLE
Formatting codes L<> don't render properly inside table's rows

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#4092]
## Problem or new feature

Links created with `L<>` don't render properly inside a table's rows. See image:

![image](https://user-images.githubusercontent.com/22332927/175791272-cf9275f0-9026-4a01-980e-39e4dfb80b76.png)

## Suggestions

If this a limitation of Pod, we could simply leave the link for each character out.

**Comment by finanalyst** [comment]
Tables are implemented separately and it has long been a problem that table
cells do not accept ANY Pod blocks. This includes subtables, headings,
lists etc

**Comment by coke** [comment]
Maybe this should be opened as a problem solving issue (is there a better repo for POD issues?)

For our fix, we can remove the links and perhaps add a link to the site (can someone find a search URL we can link to?)

**Comment by coke** [comment]
https://github.com/Raku/Pod-To-HTML/issues/17 was opened Aug 3, 2016

**Comment by coke** [comment]
Removed the embedded formatting. also simplified the URLS (didn't need the SHOW directive)
