### ISSUE TITLE
Modules reference unused irc channel

### ISSUE THREAD

**Issue by coke** [Raku/doc#4109]
https://docs.raku.org/language/modules#___top

mentions #raku-toolchain which appears to be unused.

**Comment by lizmat** [comment]
Should I create that channel?

**Comment by coke** [comment]
No, we should update the docs to remove the reference. (Creating the channel won't put people there to discuss the topic)

**Comment by coke** [comment]
Left in reference to the bikeshed repo which looks to be stale at this point; we can consider removing that as well.
