### ISSUE TITLE
Documentation error .raku vs. .flat

### ISSUE THREAD

**Issue by p6steve** [Raku/doc#4120]
## Problem or new feature

https://docs.raku.org/routine/flat#(Iterable)_method_flat

```say ($('a', 'b'), 'c').raku;```
should be 
```say ($('a', 'b'), 'c').list;```
 _methinks_

**Comment by coke** [comment]
Should be *flat*, no?

**Comment by p6steve** [comment]
arggh - yes ```.flat```

**Comment by coke** [comment]
Good catch, fixed.
