### ISSUE TITLE
Policy needed for incomplete snippets

### ISSUE THREAD

**Issue by 2colours** [Raku/doc#4138]
## Problem or new feature

The concrete case was the following: habere-et-disper at IRC, visited https://docs.raku.org/routine/splice which has an example for the `splice` method of `Buf` - however, that example is incomplete, despite even suggesting certain output. 

Even [in the file] (https://github.com/Raku/doc/edit/master/doc//Type/Buf.pod6) that backs up the snippet, it's hard to find the context of that code. I found that the :preamble argument is often used to indicate additional information to the snippet, however that's also prone to being too incomplete to be useful and it's not shown to end users anyway...

It seems to me that this is a general problem that needs to be addressed as such.

## Suggestions

I think, since the usefulness of code snippets is strongly based on the supposed output of the example - and we can't nearly get rid of all the outputs in favor of computing them on the fly - we should approach the problem from the presumptions about the snippet.

1. we should make no assumptions about the context of the snippet - other than the very paragraph it illustrates
2. the output should be at least _deducible_ (preferably _computable_) from the snippet. If something isn't defined in the code, it should be at least described in the preceding text
3. correct me if I'm wrong but [it seems to me](https://github.com/Raku/doc/blob/master/writing-docs/EXAMPLES.md#preambles) that :preambles is essentially a hack for compilation, in which case it should be removed whenever it's appropriate to just add the code to the snippet. Saving one line per snippet is not a huge win, especially not for a reader, especially when it can show up "out of context".

**Comment by Altai-man** [comment]
Can you clarify which code example is meant from the page?

This one:

```
@a.push($x, $y)      @a.splice: *  , *, $x, $y
@a.pop               @a.splice: *-1,
@a.shift             @a.splice: 0  , 1,
@a.unshift($x, $y)   @a.splice: 0  , 0, $x, $y
@a[$i] = $y          @a.splice: $i , 1, $y,
```

?

**Comment by 2colours** [comment]
Well, was raising my eyebrows over that (as well) but no.

```
$bú.splice:  0, 3, <3 2 1>;
say $bú.raku; # OUTPUT: «Buf.new(3,2,1,2,3,5,8,13,21,34,55,89)» 
```

**Comment by coke** [comment]
Yes, :preamble is solely used by the example compilation test. If it makes sense to include that code in the user-visible example, then we do so. If it does not, we can hide it and still verify that the code compiles as intended.

This has to be decided for every code snippet, it's not something we can do across the board.

**Comment by coke** [comment]
note that part of issue is when we split a single large example over X chunks - if a variable decl. is in the first chunk, we have to cheat it somehow; so we make each chunk compile this way. (we could go a different way for these and stitch together the chunks somehow in the examples test, but that's a lot of work for no visible user benefit)

**Comment by 2colours** [comment]
I think the other points still stand: we can make decisions about the output "across the board", can't we?

Say the output is always in a comment on the line of code that is supposed to produce it. This is more or less what the documentation already has, I suppose. Then we can declare that the code snippet should actually produce that output when run - or with a slight lift, by allowing informal specification, like "instances of class Foo give subsequent element of the Fibonacci series upon indexing" (just some random lunatic example of something sufficiently complex to include in the snippet).

**Comment by coke** [comment]
we're not going to run the code and match against the output. this only works for the most trivial cases. I had wanted this at one point (#1424) and @Altai-man has done some prototype work in this area.

**Comment by 2colours** [comment]
I'm not saying that we should run the code and match against the output. What I do say, though, is that it's not acceptable for a code snippet to refer to output _we know it doesn't produce_, like the splice example:

```$bú.splice:  0, 3, <3 2 1>;
say $bú.raku; # OUTPUT: «Buf.new(3,2,1,2,3,5,8,13,21,34,55,89)» ```

You don't have to run this code to know it doesn't produce this output, right?

I'm not talking about some huge magic to ensure this rule, just to set the policy that ^ this example is, among probably many others, an invalid way of documenting, and should be changed. Then this could be something one can think back to, when in doubt.

**Comment by coke** [comment]
The policy should be clearly spelled out in writing-docs/EXAMPLES.md

**Comment by coke** [comment]
> I'm not saying that we should run the code and match against the output. What I do say, though, is that it's not acceptable for a code snippet to refer to output _we know it doesn't produce_, like the splice example:
> 
> ```raku
> $bú.splice:  0, 3, <3 2 1>;
> say $bú.raku; # OUTPUT: «Buf.new(3,2,1,2,3,5,8,13,21,34,55,89)» 
> ```
> 
> You don't have to run this code to know it doesn't produce this output, right?
> 
> I'm not talking about some huge magic to ensure this rule, just to set the policy that ^ this example is, among probably many others, an invalid way of documenting, and should be changed. Then this could be something one can think back to, when in doubt.

It does output this, though, as long as one includes the variable definition earlier in the document, and, all the code that modifies it along the way. As I mentioned in the .md, this is specifically allowed so that we don't have to repeat ourselves. So, **in general**, this approach is fine.

On a Type/ page, however, the original definition can be lost when the page is sliced into secondary pages, and only works if you read the page top to bottom. And furthermore, on this page, it's **definitely** confusing, since it's not just the original definition but other intermediate code as well. doc/Type/Buf.rakudoc for sure needs to be cleaned up.
