### ISSUE TITLE
Document chown (IO::Path method and subroutine)

### ISSUE THREAD

**Issue by 2colours** [Raku/doc#4153]
According to https://github.com/rakudo/rakudo/issues/5078, `chown` got added, both as a subroutine and as a method of `IO::Path`. I tried it with Rakudo 2022.12 on MoarVM, and it seems to work indeed.

It should be added to the documentation. Probably `chmod` can be used as reference.

**Comment by coke** [comment]
added in f381a163cc3248fc8a9e1e93bef5700354fd6ea2
