### ISSUE TITLE
Need an unthreaded version of xt/aspell.t

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#4166]
## New feature to help debugging doc PR testing

Doc issue #4162 demonstrates  a problem which prevents complete testing of **doc** PRs, and it **may** have something to do with the multi-thread implementation of **xt/aspell.t**.

## Suggestions

Make the problem easier to diagnose by doing the following:

1. Create a single-thread version that doesn't use **race** or **hyper** and their friends. 

2. Instead of **proc**, consider using module **Proc::Easier**.

**Comment by coke** [comment]
I'd rather fix the bug than mask it. Many tests are using similar code, not sure why aspell in particular is triggering an issue for you.

**Comment by tbrowder** [comment]
Okay, closing this.  BTW, I've asked @JJ if he can add some info on using the Docker Makefile targets.
