### ISSUE TITLE
Will this content-only repo need to be restructured?

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc#4182]
This is a smallish step that will be useful for migration, because it will let contributors get used to the workflow that they will ultimately use.

I am proposing @coke create a branch called, say, `main-next`, and push the relevant code there.

This will mean enforcing a pull request workflow on folks who may be used to pushing to their own main branch. That will be clumsy at first, but there are big benefits to taking this little step.

* Any automation around transition will be simplified by dealing with a single git remote
* Ultimately a pull request workflow is something we should all become comfortable with

If it helps aid the transition, special branch protection rules can be set on this repo to allow folks like @Altai-man or @finanalyst merge code on their own behalf specifically to the `main-next` branch.

**UPDATE**: Note that this repo will be a content-only repo; We in fact need a new repo where new server/presentation code should live.

**UPDATE 2:** A new repo for server code has been created https://github.com/Raku/doc-website/

**Comment by Altai-man** [comment]
Can you elaborate on

>it will let contributors get used to the workflow that they will ultimately use.

please?

Two repositories for actual doc content and actual presentation is something we should strive for, shouldn't we? I think we worked hard to split those two in the past.

**Comment by dontlaugh** [comment]
Forgive me; Yes, I will defer to you on that architectural decision. In that case, I'd like to determine exactly what the new structure of _this particular repo_ should look like, and we can stub that out on a branch manually. Manual to start is fine.

Specifically, regarding this repo:

* What folders will be moved around, if any?
* What folders will be added or removed?

When designing automated builds, a lot of the work ends up being packaging up the right "stuff". I need help knowing what the right stuff is.

**Comment by Altai-man** [comment]
Very high-level view: all related to the old website should go away, a new frontend implementation should live in a separate repo, so this becomes a content-only one.

**Comment by coke** [comment]
I think we should keep the web site repo separate from the documentation (This is inline with old issues from JJ as well).

I think it should eventually end up as something like raku/doc-website, and start life as a clone of @Altai-man's repo (assuming no issues with licensing).

To avoid infra changes, maybe do the form into Raku now, and do the infra work off that fork, incorporating changes from @Altai-man's repo until go live at which point we can switch to the raku site being the main site. (or we can do the cutover immediately)

**Comment by Altai-man** [comment]
>I think it should eventually end up as something like raku/doc-website

Yup.

>and start life as a clone of @Altai-man's repo (assuming no issues with licensing).

That repo should be archived, just as Documentable, we can now work with finanalyst's repo.

**Comment by dontlaugh** [comment]
Cool. Let's keep looking for small things we can do to move the ball forward. A lot of them will require us to bother a Raku github admin. We can lessen their load by staying organized and giving them precise instructions that we've given some thought to.

We're gonna get this done!

**Comment by coke** [comment]
If we are going to move forward with @finanalyst's version of the site, we need to do a round of QA and determine what issues need to get fixed before go live; I had no remaining issues with yours as a first pass, but there are usability issues with the last version he linked.

So let's get the new repo created, import whatever version is heading towards production, and start opening issues (and have a way to tag which ones need to be fixed before go live)

**Comment by coke** [comment]
I'll move this list to Raku/doc-website as individual issues this weekend if no one beats me to it.

**Comment by patrickbkr** [comment]
Let's do a poll on the run feature. Please add an emoji to the respective reply.

**Comment by patrickbkr** [comment]
Option 1: I like run buttons on each code fragment.

**Comment by patrickbkr** [comment]
Option 2: I like a run area where code examples can be run in. (finanalysts approach)

**Comment by coke** [comment]
Please do this poll on an issue on the new repo. And keep in mind we may disable things to go live and then add them back in once they are working as desired (and the poll can tell us what is desired)

**Comment by finanalyst** [comment]
I'd like to get this moving. But I don't have any way to move content onto the doc-website repo

**Comment by dontlaugh** [comment]
@finanalyst There's initial setup required. Add a link to your code over here https://github.com/Raku/doc-website/issues/1

**Comment by coke** [comment]
You should have push privs now.
