### ISSUE TITLE
Create new repo for next-gen docs server

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc#4183]
This is a task spawned from #4182 

My understanding is that the following is true for the new docs site architecture:

1. This repo Raku/doc hosts **content**
2. A separate repo will host the server code

I don't think number 2 exists. We should pick a suitable, unambiguous name ("docs-server"?), and create this repo.

This new repo should then be populated with the code from the prototype docs site.

What's a good name? Repos can be renamed without too much trouble, so we shouldn't sweat it TOO much. Naming is hard and we'll always get it wrong, so :shrug:

**Comment by dontlaugh** [comment]
@coke i want to weigh in on your comment on #4182 

> To avoid infra changes, maybe do the form into Raku now, and do the infra work off that fork, incorporating changes from @Altai-man's repo until go live at which point we can switch to the raku site being the main site. (or we can do the cutover immediately)

I think it's better to create the new repo now, push up @finanalyst code and perhaps give @finanalyst merge capability to keep things moving during this initial phase.

**Comment by coke** [comment]
https://github.com/Raku/doc-website/ now exists; We can add permissions if needed, should default to Raku membership for now.

**Comment by dontlaugh** [comment]
Closing this; if there are particular permissions needs, we can open an issue on our shiny new repo. Thanks!
