### ISSUE TITLE
special method COERCE not documented

### ISSUE THREAD

**Issue by jonathanstowe** [Raku/doc#4184]
It seems that the special method COERCE is neither indexed or documented,  it probably wants to be added to the doc/Language/typesystem.pod6 (similarly to FALLBACK,) and mentioned in the doc/type/Signature.pod6

**Comment by 2colours** [comment]
This is a duplicate/subset of https://github.com/Raku/doc/issues/3807 that contains quite some useful information about coercions in general.

**Comment by raiph** [comment]
(Closed per comment by @2colours; "contains quite some useful information about coercions in general" is 3807, not this issue.)
