### ISSUE TITLE
Replace Build.pm info with preferred declarative method

### ISSUE THREAD

**Issue by p6steve** [Raku/doc#4186]
## Problem or new feature

https://docs.raku.org/language/modules

Build.pm might go away one day (we've been saying forever).

## Suggestions

Lift the guidance from @ugexe zef info

 Ideally one does what Inline::Perl5 does and uses https://github.com/niner/Inline-Perl5/blob/2e7b99fb03d182d15df4f88818d835b151117786/META6.json#L58-L68

https://github.com/ugexe/zef#build-paths

**Comment by coke** [comment]
This repository is not meant to be installed, I've updated Build.pm to error out if anyone tries.

rakudoc & doc-website, our primary consumers, don't expect an installation anymore.
