### ISSUE TITLE
pod6 comments  "=comment" inaccurate?

### ISSUE THREAD

**Issue by sdondley** [Raku/doc#4187]
## Problem or new feature

Looking at https://docs.raku.org/language/pod#Pod6_comments

Says: "Single-line comments use the =comment marker:"

But as far as I can tell, `=comment` also acts the same way as a `=for comment`, behaving like a paragraph block and terminating on the first blank line or next pod directive. 

## Suggestions

I'm not sure what the correct answer is here. Just wanted to bring to someone's attention.

**Comment by finanalyst** [comment]
This is the correct behaviour for all `=block` pod commands

There are three forms for a Pod::Block, as is documented (I'll use `para` as an example, but it applies to `comment` too)
- `=para This string is put into the contents of para`
  -- You can then have multiple `=para` lines without any blank lines between them
  -- The next line can be blank or another pod block
  -- The string is then put into the contents of the pod structure.
- `=for para :metadata<this can be used by para in some renderers like ProcessedPod>`
 -- The next lines to the first non-blank line are inserted into the contents of `para`
 -- This form must have a blank line before the next pod block
 -- It is possible to multiple lines of metadata by having `=` on subsequent lines after a space character
- `=begin para ...\n ... \n .. =end para`
  --  Metadata can be placed after the block name,
  -- All lines up to the `=end` are placed in the contents.
  -- There is no need for a blank line after `end`.

Hope this helps

**Comment by coke** [comment]
@finanalyst  - Are you saying the docs are correct, or do we need to convert your comment here into a doc patch?

**Comment by coke** [comment]
Thanks for the question, added an example showing @finanalyst's point .
