### ISSUE TITLE
Remove new() method showing positional arguments from Mu.new() documentation?

### ISSUE THREAD

**Issue by sdondley** [Raku/doc#4188]
## Problem or new feature

Looking at https://docs.raku.org/type/Mu#method_new

It shows a multi method which accepts a positional argument. However, that method just throws an error: https://github.com/rakudo/rakudo/blob/2022.12/src/core.c/Mu.pm6#L121

Not sure it makes sense to leave this multi method in the docs when its only purpose is to throw an error.  

## Suggestions

Remove the `multi method new($, *@)` line from the documentation or explicitly explain that this version of the method will only throw an error.

**Comment by coke** [comment]
Thanks, removed.
