### ISSUE TITLE
update CONTRIBUTING.md

### ISSUE THREAD

**Issue by coke** [Raku/doc#4189]
Replace link to JJ's blog with a link to a raku/doc wiki page (lots of good info in JJ's blog, but written with a focus on hackathons, which aren't a thing anymore)

**Comment by MonalikaPatnaik** [comment]
Hey coke!
I would like to work on this issue! Kindly assign me.
Thanks!

**Comment by coke** [comment]
_Doesn't have to be a wiki page, can. be inline in the CONTRIBUTING.md doc_

**Comment by MonalikaPatnaik** [comment]
Could you please label some issues as good first so that I can contribute further!

**Comment by coke** [comment]
Old classifications still around, please try:
* https://github.com/Raku/doc/issues?q=is%3Aopen+is%3Aissue+label%3A%22easy+to+resolve%22
* https://github.com/Raku/doc/issues?q=is%3Aopen+is%3Aissue++label%3AHacktoberfest+

I will try to tag more over the next week.

**Comment by MonalikaPatnaik** [comment]
Alright!
Thankss 💯

**Comment by coke** [comment]
https://github.com/Raku/doc/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 also
