### ISSUE TITLE
New brackets page fails brackets test.

### ISSUE THREAD

**Issue by coke** [Raku/doc#4212]
We went through some cleanup years ago to ensure that "brackets" and "braces" were never used as is, but always as:

* curly braces
* square brackets
* angle brackets
* lenticular brackets

And now we have a page, "Brackets", that has just that as a title without the modifier.

Do we fudge the test for this one instance, or do we fix the generated Brackets page to comply?

**Comment by tbrowder** [comment]
I'm up for a rename of the page, but what name would you use? The two-word expressions are great for the usual cases, but how would you describe the large set of sometimes unfamiliar characters that may not easily fit those definitions.

My suggestion for a possible better name for the table is "Bracketing character pairs."

**Comment by coke** [comment]
This case is special enough, updated the test.
