### ISSUE TITLE
Remove rakudobrew example, switch to rakubrew

### ISSUE THREAD

**Issue by coke** [Raku/doc#4241]
doc/Language/faq.pod6 and doc/Type/Distribution/Resource.pod6 refer to rakudobrew. If we still need these examples, please update to rakubrew.

**Comment by cfa** [comment]
I see that the FAQ has already been updated.

As for `Distribution::Resource`, that example (and those paths) seem a little too tied to a specific installation; generalise?

**Comment by 2colours** [comment]
> As for `Distribution::Resource`, that example (and those paths) seem a little too tied to a specific installation; generalise?

What are you thinking of by "generalise"?

By the way, I think even a mere path update - something that looks considerably newer - can do wonders for "look and feel".

**Comment by cfa** [comment]
> > As for `Distribution::Resource`, that example (and those paths) seem a little too tied to a specific installation; generalise?
> 
> What are you thinking of by "generalise"?

Examples reference a specific installation directory; I'm not sure this is necessary for explaining behaviour.
