### ISSUE TITLE
xt/rakudoc-c.rakutest false positives

### ISSUE THREAD

**Issue by coke** [Raku/doc#4251]
xt/rakudoc-c.rakutest was recently added to complain about ``C<>`` blocks, and many instances were found and corrected.

However, there are some instances in `doc/Language/regexes.rakudoc` which are intended to end with whitespace.

Need to make the test smarter so these are not failures.

**Comment by coke** [comment]
the solution in place causes a failure in xt/aspell.t that we need to resolve.

**Comment by cfa** [comment]
@coke please take a look and close if appropriate.
