### ISSUE TITLE
Leaky, nested tags in the $*REPO section

### ISSUE THREAD

**Issue by 2colours** [Raku/doc#4261]
## Problem or new feature
[In the paragraph about the $*REPO variable](https://docs.raku.org/language/compilation#$*REPO), there are some cases (e.g `B<@INC>`, `B<$*REPO>`) where the bold formatting leaked. Checking the sources, this seems a result of nesting C and B tags, like `C<B<@INC>>`.

## Suggestions
It needs to be checked if this is a valid use of Rakupod. If it isn't, the content should be adopted to a valid version (e.g solely C<>).  
If it is valid, the renderer needs to be aware of it and handle it accordingly.

**Comment by cfa** [comment]
`C<>` is supposed to treat its contents as verbatim, so `C<B<@INC>>` should render as `B<@INC>` (as it does here).

This is used, for example, in [documenting `B<>` itself](https://github.com/Raku/doc/blob/main/doc/Language/pod.rakudoc#L510):

```
To format a text in bold enclose it in C<B< >>
```

The error is with the documentation, not the renderer. I'll push a fix now.
