### ISSUE TITLE
Unicode non-characters

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#4291]
## Problem or new feature

In `Language/operators` the following code is given in the section on Chaining Binary Precedence.
```
=head2 infix C«===», infix C«⩶»

    sub infix:<===>(Any, Any)
```
The character is used a couple of times. It seems to be coded as `%E2%A9%B5` which is out of bounds. 
This seems to be a mistake.

## Suggestions

If applicable, suggest something towards the solution.

**Comment by patrickbkr** [comment]
I think it should be https://www.fileformat.info/info/unicode/char/2a76/index.htm (%E2%A9%B*6*, note the 6), the *tripple* equals sign.

Interestingly: https://www.fileformat.info/info/unicode/char/2a75/index.htm (%E2%A9%B*5*, note the 5) is the *double* equals sign.

**Comment by finanalyst** [comment]
In my browser I am getting an error glyph when I type ⩶ (`<shift><ctrl>2a76`). Checking on the links above, I get the same error. 
I have tried installing Cambria, which is given above as a font that handles this Unicode glyph. But I still get the error glyph.

I originally thought this was an error in the Rakudoc source. Now I think it is a visualisation error. I have not solved it for myself yet.

Any feedback would be welcome.

**Comment by finanalyst** [comment]
raku -e 'say "\x2a76  ", "\x2a76".uninames'
⩶  (THREE CONSECUTIVE EQUALS SIGNS)

**Comment by lizmat** [comment]
That renders for me on MacOS Mojave... so I'm not sure why that wouldn't render for you

**Comment by finanalyst** [comment]
This needs more work on my part. Now I am aware my browser is not rendering properly, I'll follow up.
Closing out this issue as not relevant to this Raku/doc source.

**Comment by lizmat** [comment]
FWIW, it is usually connected to the level of Unicode support in the operating system.  You may need to do an OS upgrade (or some OS module)
