### ISSUE TITLE
An example doesn't work on the Whatever page

### ISSUE THREAD

**Issue by deoac** [Raku/doc#4301]
On https://docs.raku.org/type/Whatever there's a table of exceptions to Whatever-currying.  

```
range operators | 1 .. * | Range.new(:from(1), :to(*));
```

`1 .. *` yields `1..Inf`

`Range.new(:from(1), :to(*))` throws this error: `Cannot resolve caller new(Range:U: :to(Whatever), :from(Int)); none of these signatures matches:`

**Comment by coke** [comment]
The issue is that the args to new here are positional, not named.
