### ISSUE TITLE
Bad link on the 'andthen' page

### ISSUE THREAD

**Issue by deoac** [Raku/doc#4308]
Page https://docs.raku.org/routine/andthen contains this statement:

> The `andthen` operator is a close relative of [`with` statement modifier](https://docs.raku.org/syntax/with%20orwith%20without.html), and some compilers compile with to andthen, meaning these two lines have equivalent behavior:

That link should be 

`https://docs.raku.org/language/control#with_orwith_without`

**Comment by uzluisf** [comment]
Should this be closed @coke?

**Comment by deoac** [comment]
Hi Luis!

No, the link (with statement modifier <https://docs.raku.org/syntax/with%20orwith%20without.html>) still leads to the 404 page.

Thanks,

Jim

**Comment by coke** [comment]
@deoac  - it was fixed in the source, not on the website, which requires someone to press a button.

**Comment by uzluisf** [comment]
Right, the docs aren't automatically generated (yet?) once a change hits the `main` branch

**Comment by 2colours** [comment]
@uzluisf @coke the link seems to work now in production so probably now it could be closed

**Comment by coke** [comment]
Thanks
