### ISSUE TITLE
Ambiguous wording on state page

### ISSUE THREAD

**Issue by deoac** [Raku/doc#4316]
On [state](https://docs.raku.org/syntax/state): 
```
({ state $i = 1; $i++.say; } xx 3).map: {$_(), $_()}; # says 1 then 2 thrice 
```
The phrase `says 1 then 2 thrice` could mean `1␤2␤1␤2␤1␤2␤` on `1␤2␤2␤2␤`

I suggest changing it to `says '1␤2␤' thrice.

**Comment by coke** [comment]
Thanks - I just made the output explicit as we do in so many places.
