### ISSUE TITLE
Reference to S05 in Language/Regexes.rakudoc

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#4340]
## Problem

The following text appears in the document
```
A list of predefined subrules is listed in [S05-regex](https://design.raku.org/S05.html#Predefined_Subrules) of design documents
```
I think - but am not sure - that the list in S05 is already in a document

## Suggestions
Either delete this sentence because the information is already available, or copy the list and create a new section.

**Comment by coke** [comment]
Good catch, thanks.
