### ISSUE TITLE
Make docs 'zef install' able

### ISSUE THREAD

**Issue by coke** [Raku/doc#4347]
Use case: make `rakudoc` more functional out of the box.

Only have a single, latest version of the docs installed

Expectation: only primary docs (actual .rakudoc files) and none of the secondary ones generated for the website (even looking up the Type documentation and the tutorials would be very helpful)

This may involve moving things to resources/ so zef can easily install them without shenanigans and some other changes. May involve work with rakudoc so the tool can find the installed docs by default.

**Comment by 2colours** [comment]
I think it was a really nice change to make the doc repo **not** installable, and to not try to be more than a content repository. Finally, it seems realistic for tools to depend on this repository as it is, and do whatever they want with the content.

This is what I would advise for rakudoc as well: to retrieve the data from this repo, probably during the build process of the module, and then use it whatever way fits it. Now that it is a standalone tool, the doc content itself doesn't have to know about its problems regarding lack of content. Perhaps it could even "collaborate" with Collection to obtain similar files. That seems a much more maintainable solution to me than to steer back and make this a tool repo again...

**Comment by coke** [comment]
The ask was not to make this a tool repo but only make the pod installable.

I can work with the idea of making rakudoc do the work instead, I do like that suggestion. (like rakubrew lets you get zef)
