### ISSUE TITLE
Standardize "environment variable"

### ISSUE THREAD

**Issue by coke** [Raku/doc#4363]
The docs are split between "environmental" and "environment" variable.

Add to xt/

google shows the same amount of results for both, but:

Did you mean: ["environment variable" programming](https://www.google.com/search?sca_esv=567639170&biw=1470&bih=834&sxsrf=AM9HkKmyFzW-NIZD_a8woJOAYHAAEvpjKg:1695402648604&q=%22environment+variable%22+programming&spell=1&sa=X&ved=2ahUKEwimy_uE276BAxX9D1kFHYCqAJoQBSgAegQICBAB) hints at an answer.

**Comment by codesections** [comment]
`coreutils`, `git` and `dash` all use "environment variable" too, so I think we're safe in treating "environmental" as a typo.
