### ISSUE TITLE
Incorrect example involving <ws>

### ISSUE THREAD

**Issue by deoac** [Raku/doc#4368]
On the [grammars -> ws page](https://docs.raku.org/language/grammars#ws), the last example says 
```
grammar Foo { token TOP {\d <ws> \d} };
my $parsed = Foo.parse: "3 3";
say $parsed<ws>; # OUTPUT: «｢ ｣␤» 
```
The actual output is `(Any)`.  Which doesn't make sense, since there is a space in there to be matched.

```
[26] > grammar Foo { token TOP {\d <ws> \d} };
my $parsed = Foo.parse: "3 3";
say $parsed<ws>; # OUTPUT: «｢ ｣␤»
(Any)
```

```
[34] > $*DISTRO
macos (13.5.2)
[35] > $*KERNEL
darwin
[36] > $*VM
moar (2023.08)
[37] > $*RAKU
Raku (6.d)
```

**Comment by codesections** [comment]
I cannot reproduce this issue – I'm getting the output indicated in the docs, as shown below.  It doesn't _seem_ like the sort of issue that should be platform-specific, but I'm not sure what else would be causing it.  I get the same result with Rakudo v2023.08 and the current `rakudo/rakudo` main branch.

```
[0] > grammar Foo { token TOP {\d <ws> \d} };
my $parsed = Foo.parse: "3 3";
say $parsed<ws>; # OUTPUT: «｢ ｣␤»
｢ ｣
[0] > $*DISTRO
pop (22.04.LTS)
[1] > $*KERNEL
linux
[2] > $*VM
moar (2023.08)
[3] > $*RAKU
Raku (6.d)
```

**Comment by deoac** [comment]
Hi Daniel!

I restarted my REPL session and now am getting the expected output.  Hmm…

Thanks,

deoac
