### ISSUE TITLE
doc/Language/regexes.rakudoc fails xt/rakuast-compare.rakutest

### ISSUE THREAD

**Issue by coke** [Raku/doc#4373]
With the 2023.09 rakudo:
``
xt/rakuast-compare.rakutest doc/Language/regexes.rakudoc
``
fails. Haven't checked the output diff yet

**Comment by codesections** [comment]
I looked at the diff before submitting the PR and I believe the issue is due to a bug in the non-RakuAST --doc relating to whitespace

Sep 30, 2023 8:21:03 PM Will Coleda ***@***.***>:

**Comment by coke** [comment]
Now also failing doc/Language/syntax.rakudoc
