### ISSUE TITLE
methods are not "subroutines declared within a class"

### ISSUE THREAD

**Issue by 2colours** [Raku/doc#4380]
## Problem or new feature

https://docs.raku.org/language/syntax#Subroutine_calls mentions methods the following way:

> When declared within a class, a subroutine is named "method": methods are subroutines invoked against an object (i.e., a class instance).

This is confusing at least but I think it's much rather outright wrong. Whether something is declared in a class or outside of it has little to do whether it's "declared within a class" or not.

## Suggestions

I don't know if it's a good idea in the first place to show methods under an entry called "subroutine calls" but in any case, being a method is much rather about argument handling and dispatch than the place of declaration. That property should be highlighted. Maybe it's described better at some place already.

**Comment by codesections** [comment]
The "Subroutine calls" section has several problems, actually – including that it starts with a paragraph about subroutine declaration even though there's a separate "Subroutine declaration" section.

I think I see how to fix it; I'll submit a PR shortly.
