### ISSUE TITLE
is default has three Composite pages, should be one

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#4425]
## Problem or new feature
If you type in 'is default' into search, three Composite pages are suggested. The idea of Composite pages is that they should gather the information about the same thing specified in different classes (etc). 

The reason three Composites are generated is that the `X<>` markup in two files are labelled with extra information, eg '(Attribute)'.

## Suggestions

Remove the (Attribute) / (Variable) information from the `X<>`.

Then remove all 'is default' references that contain the extra information too (some are in recent changes to remove missing links)

**Comment by coke** [comment]
Would it make sense to leave that but ignore it when generating composite pages?
