### ISSUE TITLE
multi method map(\SELF: &block;; :$label, :$item) is an implementation detail

### ISSUE THREAD

**Issue by lizmat** [Raku/doc#4460]
The documentation of `map` mentions the `:label` and `:item` flags.

I think these are Rakudo implementation details and have no place in the Raku documentation.

**Comment by lizmat** [comment]
https://docs.raku.org/type/List#routine_map also states:
```
multi method map(Hash:D \hash)
multi method map(Iterable:D \iterable)
multi method map(|c)
```
What is that about???

**Comment by coke** [comment]
Covered the second comment in #4434 based on the SO article we probably both saw.

**Comment by coke** [comment]
This helped me realize the same weird list was also on Any, not just on List. Fixed.
