### ISSUE TITLE
Stubs as operators

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc#4490]
## Problem or new feature
`Language/glossary` contains a reference to using the **"stub" operator** See [Forward declarations](https://docs-dev.raku.org/language/glossary#Forward_declarations)

But no **operator** stub is listed in `Language/operators`. A search for 'stub' yields [an appropriate reference](https://docs-dev.raku.org/language/objects#Stubs) but not as an operator and only for roles.

## Suggestions

More information about stubs is probably warranted and the Glossary item updated.

**Comment by coke** [comment]
The stub operator is "listop ..." - this link was fixed as part of #4476
