### ISSUE TITLE
Rakudo env var RAKUDO_POD_DECL_BLOCK_USER_FORMAT is not shown on the environment variables page

### ISSUE THREAD

**Issue by tbrowder** [Raku/doc#4515]
## Problem or new feature

Although it is mentioned in the docs as having been added with Rakudo v2020.01.

**Comment by lizmat** [comment]
@tbrowder FWIW, I think we can deprecate this environment variable, as in RakuAST all whitespace is preserved

**Comment by tbrowder** [comment]
Of course you're right, so be it!
