### ISSUE TITLE
Add Rakudoc to Main Site Pages

### ISSUE THREAD

**Issue by librasteve** [Raku/doc#4530]
## Problem or new feature

I have looked for Rakudoc information on the main two pages of docs.raku.org , namely Introduction and Reference. 

The information I need is in this page https://docs.raku.org/language/pod - but I had to search for "POD" in order to find it.

## Suggestions

Add a link in the Reference Page to https://docs.raku.org/language/rakudoc and move/rename the page https://docs.raku.org/language/pod to this even though most of the terms may still refer to "POD" a squick note at the top would explain this is wip.

**Comment by finanalyst** [comment]
closing as completed
