### ISSUE TITLE
Demonstrate how succeed can return a value

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc#4545]
[This page](https://github.com/Raku/doc/blob/main/doc/Language/control.rakudoc) has instructions on how `succeed` can return a value, but we don't demonstate that.

I don't know if we could show it succinctly without defining a `sub`

```raku
sub use-succeed() {
  given 42 {
    when Int {
        # say "Int";
        succeed "Found";
        say "never this!";
    }
    when 42 { say 42 }
    default { say "dunno?" }
  }
}

say use-succeed();
```

Or using `do given`, perhaps. Like `my $value = do given { ... }`

**Comment by raiph** [comment]
> Or using `do given`, perhaps.

Yep. Just prepend a `say do ` in front of the existing example in the doc:

```
say do given 42 {
    when Int {
        say "Int";
        succeed "Found";
        say "never this!";
    }
    when 42 { say 42 }
    default { say "dunno?" }
}
# OUTPUT: «Int␤Found␤»
```

**Comment by dontlaugh** [comment]
I've opened a PR with a small modification on your suggestion #4547
