### ISSUE TITLE
IO::Notification::Change is not documented

### ISSUE THREAD

**Issue by zoffixznet** [Raku/doc#475]
Seems to be documented on http://docs.perl6.org/type/IO::Notification

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/8266af94c9705b1b15cfbb3ee624f2aae174c64e

**Comment by JJ** [comment]
It's just a piece of the description of [IO::Notification](https://docs.raku.org/type/IO::Notification.html), which needs to be extended too: #2828
