### ISSUE TITLE
Lots of broken links, invalid HTML and so on (checklink)

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/doc#561]
I've used [checklink](http://search.cpan.org/dist/W3C-LinkChecker/bin/checklink.pod) utility on doc.perl6.org. **[Here is the output](https://gist.github.com/AlexDaniel/fc6cb8d6f66516c837268d43ecc47c33)**. I believe that all of these issues have to be fixed.

Some of the errors are repeated many times, that's why the output is so large.
## Current status

| Number of lines in the output | Date |
| --- | --- |
| 126591 | 2016-05-31 |
| 128555 | 2016-06-03 |
| 132005 | 2016-06-09 |
| 128771 | 2016-06-11 |
| 126707 | 2016-06-12 |
| 130491 | 2016-06-16 |
| 134073 | 2016-06-23 |
| 131489 | 2016-06-25 |
| 134542 | 2016-07-06 |
| 35561 | 2016-07-13 |
| 35005 | 2016-08-01 |
| 33926 | 2016-08-02 |
| 20540 | 2016-08-03 |
| 17432 | 2016-08-04 |
| 17002 | 2016-08-05 |
| 8253 | 2016-08-06 |
| 8615 | 2016-08-10 |
| 7374 | 2016-11-12 |
| 8157 | 2016-12-20 |
| 208521 | 2017-06-30 |
| 207664 | 2017-07-01 |
| 211899 | 2017-11-04 |
| 213547 | 2018-01-05 |
| 184904 | 2018-03-03 |
| 55393 | 2018-05-05 |
| 54232 | 2018-05-06 |
| 57626 | 2018-11-04 |
| 39726 | 2020-07-26 |

![checklink_graph](https://user-images.githubusercontent.com/5507503/88478516-a7a30200-cf51-11ea-8484-f4442860f356.png)

**Comment by zoffixznet** [comment]
Are you sure you ran the program correctly? In the first item, `http://doc.perl6.org/type/X::TypeCheck::Splice`, the output says 

```
x:/js/main.js	
  Line: 703
  Code: 501 Protocol scheme 'x' is not supported
 To do: Could not check this link: method not implemented or scheme not
	supported.
```

Yet, no scheme `x:` is in use on that line: `<script type="text/javascript" src="/js/main.js"></script>`

I checked a couple of other errors, and they similarly are false positives.

**Comment by zoffixznet** [comment]
There's a bazillion markup errors though: https://validator.w3.org/nu/?doc=http%3A%2F%2Fdoc.perl6.org%2Ftype%2FX%3A%3ATypeCheck%3A%3ASplice

**Comment by dogbert17** [comment]
I’ll take a look at the 404’s, that should keep me occupied for a while. I suspect some of them will not be easily fixed, e.g. https://github.com/perl6/doc/issues/155

**Comment by AlexDaniel** [comment]
> I checked a couple of other errors, and they similarly are false positives. 

Saying that these are false positives is very optimistic. Sometimes the error message is LTA, other times the tool got confused because of markup errors. I'm not sure what's the issue in this particular case, but if you think that it is working incorrectly then please file a bug report [here](https://github.com/w3c/link-checker).

**Comment by dogbert17** [comment]
I have fixed quite a few broken links. Unless I have missed some, which I probably have, the ones that remain point to the following, undocumented, entities:
NaN
HOW
mro

**Comment by AlexDaniel** [comment]
I've added a graph so that we can track the progress. However, until someone fixes html problems we are not going to get any meaningful data there.

**Comment by zoffixznet** [comment]
If it helps anyone, I tried to debug the double-links on headers and gotten only as far as the three `%routines-by-type{*}.list` in [this section](https://github.com/perl6/doc/blob/master/htmlify.p6#L292,L317) stuff links into headers and then when pod is generated the headers get wrapped into links by `Pod::To::Html`. Since complete content is included anyway, the `%routines-by-type{*}.list` needn't to have links in the content.

*passes the torch*

**Comment by AlexDaniel** [comment]
Actually, I think that most issues are now either fixed or have a corresponding issue filed. We need https://github.com/perl6/doc/issues/584 to be fixed.

**Comment by coke** [comment]
@AlexDaniel  - looks like #584 might be fixed; can you re-run this scan?

**Comment by AlexDaniel** [comment]
@coke Just did.

**Comment by Altai-man** [comment]
Mostly there are issues caused by "broken" method names.

The whole thing is like this:
1)We attach a type name to the method name to create unique link on a page like this: `#(Metamodel::AttributeContainer)_method_rw`
2)But when we make a link to method/routine/sub, it becomes just `method_rw` - so the link is invalid.

Without a type name there will be duplication of ids with routine/method/sub pages.

The priority task is to find a way to avoid duplication and to avoid breaking fragments. About 3 months ago, there was a talk with gfldex++ about how one can use number suffixes to avoid duplication in Pod::To::Html, but this part is hard.

There also a few easier issues such as links to items removed from Glossary, etc. They can be just removed/fixed and it will be okay, I think.

**Comment by Altai-man** [comment]
Some further investigation notes:
* There are a lot of links to `.Str` method. It should point to Str method page with Mu-related description, but instead it points to https://docs.perl6.org/routine/Str#class_Mu - Str `.val` method. Should be investigated and fixed.

**Comment by AlexDaniel** [comment]
Still looks pretty bad.

**Comment by AlexDaniel** [comment]
Updated the graph again.

**Comment by AlexDaniel** [comment]
FWIW this is the command I'm using:
```bash
checklink -b -D 25 -q doc.perl6.org | tee "$(date '+%F')"
```

**Comment by JJ** [comment]
What about listing broken links by file and go at them, one by one?

**Comment by AlexDaniel** [comment]
@JJ well, you can just search the output for “404 Not Found” error and you'll find all broken links. Everything else is probably broken html. The goal here is to get the output to 0 lines (we were almost there in 2016).

P.S. Updated the graph and the output again.

**Comment by JJ** [comment]
Can you maybe upload the result somewhere? It took quite a while last time
I did. I can do it tomorrow, anyhow.

**Comment by AlexDaniel** [comment]
@JJ it's always in the first post.

**Comment by JJ** [comment]
:+1:

**Comment by JJ** [comment]
HTML errors have not been addressed, AFAIK. "Type/X::Y::Z" do have quite a lot
![screenshot from 2018-03-05 21 00 19](https://user-images.githubusercontent.com/500/36997015-911b1c60-20b8-11e8-9841-f9cb67d228f2.png)
Addressing HTML errors should help with SEO #1824

**Comment by JJ** [comment]
Seems like the "go to top of document" is added on top of an existing link. There are many "protocol errors" (why the x:/ is added at the beginning by the link checker I have no idea)
```
grep "501 Protocol" ~/Documentos/2018-03-05 | wc
  25708  205664 1276827
```

**Comment by JJ** [comment]
```
grep "404 Not" ~/Documentos/2018-03-05  | wc
     94     376    2068
```
Not so many now, and most of them are either not specced or with problems during generation... I'll check them anyway.

**Comment by JJ** [comment]
```
https://docs.perl6.org/type/X::Bind::Slice
```
However, it's still returning weird "501" errors like this one:
```
x:/routine/fail	
  Line: 338
  Code: 501 Protocol scheme 'x' is not supported
 To do: Could not check this link: method not implemented or scheme not
	supported.
Fragments:
	class_Exception               	Line: 338
```

Those were the lines with nested `<a href`. But they are no longer there... Does not make any sense, either. In fact, the size of the file has gone *up*, not down. Any idea?

**Comment by AlexDaniel** [comment]
@JJ I think `checklink` is going crazy for some reason. It could be that in its eyes the HTML is broken beyond repair, but I'm not sure. We can trying getting it to validate cleanly first: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.perl6.org%2Ftype%2FX%3A%3ABind%3A%3ASlice

**Comment by JJ** [comment]
@AlexDaniel That might be the case. I think I'll try to focus on those HTML errors first, which are probably originated in Pod::To::HTML.

**Comment by JJ** [comment]
Another option would be to patch checklink. It's in Perl, so...

**Comment by JJ** [comment]
And the line that yields the errors @AlexDaniel is actually generated by the `highlight` package https://github.com/atom/highlights/blob/master/spec/highlights-spec.coffee
I might have to debug that too. And I love cofeescript...

**Comment by AlexDaniel** [comment]
I think this issue was closed by accident. It's not resolved until checklink outputs 0 errors/warnings.

**Comment by JJ** [comment]
If it was me, that is an accident. Agreed

**Comment by JJ** [comment]
Right, I said fixed before issue number. Sorry

**Comment by JJ** [comment]
There's still an error in the generated HTML in level-3 headings. 
![screenshot from 2018-04-08 09 46 45](https://user-images.githubusercontent.com/500/38464678-203852aa-3b12-11e8-8df3-68560931b2af.png)

**Comment by abraxxa** [comment]
In the pod of https://docs.perl6.org/type/DateTime#method_Str `the formatter` links to the nonexisting anchor `https://docs.perl6.org/type/DateTime#method_formatter` instead of `https://docs.perl6.org/type/DateTime#(Dateish)_method_formatter`

**Comment by JJ** [comment]
@abraxxa thanks a lot for the report, but there are so many, that it's difficult to know where to start...

**Comment by JJ** [comment]
Most 404 are now done, but now heading titles have drifted from their links, like in #2146 . Whenever you're working on a page, please check outgoing anchors for correctness.

**Comment by JJ** [comment]
@AlexDaniel can you run this again?

**Comment by AlexDaniel** [comment]
@JJ thanks for pinging, updated.

**Comment by JJ** [comment]
So it got worse...

**Comment by JJ** [comment]
Maybe we should check this again...

**Comment by AlexDaniel** [comment]
@JJ updated. But there's not much of use updating it unless somebody wants to actively work on fixing the issues.

**Comment by AlexDaniel** [comment]
A lot of broken links seem to be caused by a different directory structure:

Things like:

> https://github.com/perl6/doc/blob/master/doc/Type/X::Proc::Async::AlreadyStarted.pod6
> -> https://github.com/Raku/doc/blob/master/doc/Type/X::Proc::Async::AlreadyStarted.pod6	
>  Line: 224
>  Code: 301 -> 404 Not Found

It doesn't mind the redirect (although we should avoid it anyway), but the link should have ``Type/X/Proc/Async/AlreadyStarted.pod6`` (without `::`).

**Comment by antoniogamiz** [comment]
Where have you found that link?

**Comment by AlexDaniel** [comment]
@antoniogamiz you can [see it in the output](https://gist.githubusercontent.com/AlexDaniel/fc6cb8d6f66516c837268d43ecc47c33/raw/1946a36c23d35fe1cb6a994684fa6ec06ff878e7/doc.perl6_checklink) yourself.

In this case it's the 🖉 link (Edit this page) from https://docs.raku.org/type/X::Proc::Async::AlreadyStarted.

**Comment by JJ** [comment]
Thanks, Aleks. In many cases, broken links are the result of errors in HTML
that might or might not have been fixed; I was curious about that. And, of
course, I don't think there's been any check after the Big Change (TM).
I'm also going to start a round of bugfixes, so I just wanted to know the
state of this. Again, thanks, I appreciate it.

**Comment by antoniogamiz** [comment]
In reality, output is a little bit smaller, because if you take a look at:
~~~
Processing	https://docs.raku.org/type.html


List of broken links and other issues:
https://webchat.freenode.net/?channels=	
  Line: 50
  Code: 200 OK
 To do: Some of the links to this resource point to broken URI fragments
	(such as index.html#fragment).
The following fragments need to be fixed:
	raku                          	Line: 50

https://github.com/Raku/doc/blob/master/CONTRIBUTING.md	
  Line: 78
  Code: 200 OK
 To do: Some of the links to this resource point to broken URI fragments
	(such as index.html#fragment).
The following fragments need to be fixed:
	reporting-bugs                	Line: 78
~~~

You that is reporting 

- https://github.com/Raku/doc/blob/master/CONTRIBUTING.md#reporting-bugs
- https://webchat.freenode.net/?channels=#raku

But these links work perfectly. I do not know what those appear as broken fragments.

**Comment by JJ** [comment]
Because there are HTML errors and these are converted for some reason into
missing links.

**Comment by antoniogamiz** [comment]
Hum, that's a weird behavior. Anyway, I'm using this command `checklink -s -b -r --exclude "(webchat|CONTRIBUTING)" docs.raku.org`. And errors in edit links will be solved in the next `Documentable` release.

**Comment by AlexDaniel** [comment]
Yeah, I'm not sure about these particular ones. The link to webchat can be changed to have `%23raku` instead, it will both work and be a bit more correct I think.

**Comment by coke** [comment]
Will track in https://github.com/Raku/doc-website/issues/72 on new site.
