### ISSUE TITLE
Explanation of the "Single Arg Rule"

### ISSUE THREAD

**Issue by zoffixznet** [Raku/doc#600]
It either needs to be documented, or if it is, indexed/made indexable by search engines.

**Comment by pmichaud** [comment]
I know I've been out of many recent conversations, but what is meant by "Single Arg Rule" here?  Can you point to an example or discussion thread?

**Comment by zoffixznet** [comment]
The stuff where you put a comma after a single thing to make it do what you intend. That's what I heard it referred to as, but I don't know all the details of it, which is why I was trying to find the docs.

```perl6
<Zoffix> m: my @list = (1,),; dd @list
<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [(1,),]␤»
<Zoffix> m: my @list = (1),; dd @list
<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»
<Zoffix> m: my @list = (1); dd @list
<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»
<Zoffix> m: my @list = 1,; dd @list
<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»
<Zoffix> m: my $list = 1,; dd $list
<camelia> rakudo-moar 2126ed: OUTPUT«Int $list = 1␤»
<Zoffix> m: my $list = (1,); dd $list
<camelia> rakudo-moar 2126ed: OUTPUT«List $list = $(1,)␤»
<Zoffix> m: my $list = (1,),; dd $list
<camelia> rakudo-moar 2126ed: OUTPUT«List $list = $(1,)␤»
```

**Comment by stmuk** [comment]
I tried to explain this (probably not very well) in

https://perl6advent.wordpress.com/2015/12/14/day-15-2015-the-year-of-the-great-list-refactor/

Also there are details in S07 I think

S

On 17 June 2016 at 00:25, Zoffix Znet <notifications@github.com> wrote:

> The stuff where you put a comma after a single thing to make it do what
> you intend. That's what I heard it referred to as, but I don't know all the
> details of it, which is why I was trying to find the docs.
>
> <Zoffix> m: my @list = (1,),; dd @list<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [(1,),]␤»<Zoffix> m: my @list = (1),; dd @list<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»<Zoffix> m: my @list = (1); dd @list<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»<Zoffix> m: my @list = 1,; dd @list<camelia> rakudo-moar 2126ed: OUTPUT«Array @list = [1]␤»<Zoffix> m: my $list = 1,; dd $list<camelia> rakudo-moar 2126ed: OUTPUT«Int $list = 1␤»<Zoffix> m: my $list = (1,); dd $list<camelia> rakudo-moar 2126ed: OUTPUT«List $list = $(1,)␤»<Zoffix> m: my $list = (1,),; dd $list<camelia> rakudo-moar 2126ed: OUTPUT«List $list = $(1,)␤»
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/perl6/doc/issues/600#issuecomment-226642265>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEUuY2gd2K59EXR8S1_TujP1Xi7VhM7qks5qMdt9gaJpZM4I34Gh>
> .
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by zoffixznet** [comment]
Yes, it's in S07: https://design.perl6.org/S07.html#The_single_argument_rule

**Comment by JJ** [comment]
Where should this go then? List?

**Comment by AlexDaniel** [comment]
Wait, but we have this? https://docs.perl6.org/type/Signature#index-entry-%2B_%28Single_Argument_Rule_Slurpy%29

**Comment by JJ** [comment]
Reopened to address @AlexDaniel concerns.

**Comment by JJ** [comment]
Reopening this because #3268
