### ISSUE TITLE
Cache generated documentation

### ISSUE THREAD

**Issue by Altai-man** [Raku/doc#717]
Figure out a way to cache and update the documentation registry, and when to or not to regenerate individual pages.

This seems not so hard. We can just take a hash(even simple will be fine, faster is better) for every file, gather it in something like `hashes.txt`, then while building we check every page for a change of hash and re-generate/pass. We must, of course, update `hashes.txt` if some page was re-generated.

This issue is a part of TODO.

**Comment by Altai-man** [comment]
I thought about it for some time, so if my description above is good enough, I'm ready to assign myself for this issue.

**Comment by zoffixznet** [comment]
Is there a way to do it cleanly, though? For example, I see [/todo.html](https://docs.perl6.org/todo.html) page is generated during build, but it's not a separate file [in the source](https://github.com/perl6/doc/tree/master/doc). 

So, if we add the cache and I go and modify `/testing` POD. Will it now be smart enough to know to remove `/todo.html`?

**Comment by Altai-man** [comment]
I suppose - no.
If we have dynamic pages(and we have them, obviously), then we should keep something like dependency graph, which is not so simple.

But plain hash system(without dynamic pages) will cover many cases when you just want to change, for example, Operators.pod and re-generate *only* Operators.html, not all in the world types/exceptions/etc.

If someone willing to help with dependency graph, it's great, of course.

**Comment by AlexDaniel** [comment]
Sounds like a good start.

**Comment by Altai-man** [comment]
Basic implementation can be seen and tested here - https://github.com/perl6/doc/pull/725

**Comment by JJ** [comment]
#725 was rejected. Is this going to to proceed in any way?

**Comment by Altai-man** [comment]
Not sure about this one. The main idea is that you do not want to re-generate all pages if you fixed a typo in a single one.
With dynamic site / documentation database, this ticket seems redundant to me(but we do not have one yet).

**Comment by JJ** [comment]
We do have #1823. This kind of thing would have to go through that.

**Comment by Altai-man** [comment]
Re-open if needed.

**Comment by JJ** [comment]
See also #2542

**Comment by Altai-man** [comment]
@JJ the Pod is already cached with help of Documentable++, I am somehow sure this can be closed now. Is there anything preventing closing?

**Comment by JJ** [comment]
Let me check and find a suitable thing to do so that it can be closed from a commit.
