### ISSUE TITLE
generate .pod6 before .html

### ISSUE THREAD

**Issue by gfldex** [Raku/doc#729]
this would allow disambiguation files and lists to be shared between different renderers, greatly simplifying generation of portable and printable versions. p6doc may also benefit.

**Comment by JJ** [comment]
Do you mean generate them as well as .html? Because the website has to be generated anyway...

**Comment by coke** [comment]
I think the ask is to generate pod6 first, and then html from that, allowing us to split up the organization from the rendering.

**Comment by JJ** [comment]
Is it worth the while? We have #1823 too...

**Comment by coke** [comment]
Yes. Separate but related

**Comment by coke** [comment]
With Documentable now spun off from this repo, I don't think there's anything left for this item here.

Please followup on https://github.com/Raku/Documentable if needed.
