### ISSUE TITLE
Separate pod in modules - how to have it installed

### ISSUE THREAD

**Issue by Tux** [Raku/doc#832]
Maybe this is more a panda/zef issue, but given a module that has a separate .pod/.pod6 file, neither zef nor panda install that file, so p6doc cannot find it.
Next question would be: would p6doc find/use it if it were installed?
Main question is: where should I specify (if at all, I think it should be automatic) that I have a seperate file with docs

```
$ ls -l lib/Text
total 144
-rw-rw-r-- 1 merijn users 64484 Aug 10 08:19 CSV.pm
-rw-rw-r-- 1 merijn users   246 Dec 21  2015 CSV.pm.rev-deps
-rw-rw-r-- 1 merijn users 75341 Aug 10 08:56 CSV.pod6
$ cat META6.json
{ "name"         : "Text::CSV",
  "version"      : "0.006",
  "perl"         : "6.c",
  "description"  : "Handle CSV data. API based on Text::CSV_XS",
  "auth"         : "github:Tux",
  "authors"      : [ "H.Merijn Brand (Tux)"       ],
  "tags"         : [ "CSV"                        ],
  "depends"      : [ "Slang::Tuxic", "File::Temp" ],
  "test-depends" : [ "Test"                       ],
  "provides"     : {
    "Text::CSV"  : "lib/Text/CSV.pm"
    },
  "repo-type"    : "git",
  "source-url"   : "git://github.com/Tux/CSV.git",
  "license"      : "http://www.perlfoundation.org/artistic_license_2_0",
  "support"      : {
    "irc"        : "irc://irc.perl.org/#csv"
    }
  }
```

**Comment by JJ** [comment]
As you say, this is a p6doc and/or zef issue. Have you tried to submit it there? Please close this one when you do. I can't see how we can help here.

**Comment by JJ** [comment]
Do you mean the `bin/p6doc` that's included here? Or `perl6 --doc`?

**Comment by coke** [comment]
p6doc has been split off from this repo for some time, added to the list of tickets for that, closing this one.
